// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_engine.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAIEngine = `-- name: CreateAIEngine :one
INSERT INTO ai_engine (name, provider, supported_languages, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, provider, supported_languages, is_active, created_at
`

type CreateAIEngineParams struct {
	Name               string   `json:"name"`
	Provider           string   `json:"provider"`
	SupportedLanguages []string `json:"supported_languages"`
	IsActive           bool     `json:"is_active"`
}

func (q *Queries) CreateAIEngine(ctx context.Context, arg CreateAIEngineParams) (AiEngine, error) {
	row := q.db.QueryRow(ctx, createAIEngine,
		arg.Name,
		arg.Provider,
		arg.SupportedLanguages,
		arg.IsActive,
	)
	var i AiEngine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.SupportedLanguages,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAIEngine = `-- name: DeleteAIEngine :execrows
DELETE FROM ai_engine WHERE id = $1
`

func (q *Queries) DeleteAIEngine(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAIEngine, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAIEngine = `-- name: GetAIEngine :one
SELECT id, name, provider, supported_languages, is_active, created_at FROM ai_engine WHERE id = $1
`

func (q *Queries) GetAIEngine(ctx context.Context, id uuid.UUID) (AiEngine, error) {
	row := q.db.QueryRow(ctx, getAIEngine, id)
	var i AiEngine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.SupportedLanguages,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultAIEngine = `-- name: GetDefaultAIEngine :one
SELECT id, name, provider, supported_languages, is_active, created_at FROM ai_engine WHERE is_active = TRUE ORDER BY name LIMIT 1
`

func (q *Queries) GetDefaultAIEngine(ctx context.Context) (AiEngine, error) {
	row := q.db.QueryRow(ctx, getDefaultAIEngine)
	var i AiEngine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.SupportedLanguages,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAIEngines = `-- name: ListAIEngines :many
SELECT id, name, provider, supported_languages, is_active, created_at FROM ai_engine
WHERE ($1::bool IS NOT TRUE OR is_active = TRUE)
ORDER BY name
`

func (q *Queries) ListAIEngines(ctx context.Context, onlyActive *bool) ([]AiEngine, error) {
	rows, err := q.db.Query(ctx, listAIEngines, onlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiEngine{}
	for rows.Next() {
		var i AiEngine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.SupportedLanguages,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIEngine = `-- name: UpdateAIEngine :one
UPDATE ai_engine
SET name                = COALESCE($1, name),
    provider            = COALESCE($2, provider),
    supported_languages = COALESCE($3, supported_languages),
    is_active           = COALESCE($4, is_active)
WHERE id = $5
RETURNING id, name, provider, supported_languages, is_active, created_at
`

type UpdateAIEngineParams struct {
	Name               *string   `json:"name"`
	Provider           *string   `json:"provider"`
	SupportedLanguages []string  `json:"supported_languages"`
	IsActive           *bool     `json:"is_active"`
	ID                 uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAIEngine(ctx context.Context, arg UpdateAIEngineParams) (AiEngine, error) {
	row := q.db.QueryRow(ctx, updateAIEngine,
		arg.Name,
		arg.Provider,
		arg.SupportedLanguages,
		arg.IsActive,
		arg.ID,
	)
	var i AiEngine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.SupportedLanguages,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
