// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_usage.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAIUsageBefore = `-- name: DeleteAIUsageBefore :execrows
DELETE FROM ai_usage WHERE at < $1
`

func (q *Queries) DeleteAIUsageBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAIUsageBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAIUsageDaily = `-- name: ListAIUsageDaily :many
SELECT
  date_trunc('day', at)::date                  AS day,
  kind,
  provider,
  model,
  COUNT(*)::bigint                             AS calls,
  COUNT(*) FILTER (WHERE NOT ok)::bigint       AS failed,
  COALESCE(SUM(input_tokens), 0)::bigint       AS input_tokens,
  COALESCE(SUM(output_tokens), 0)::bigint      AS output_tokens,
  COALESCE(SUM(characters), 0)::bigint         AS characters,
  COALESCE(SUM(audio_seconds), 0)::float8      AS audio_seconds
FROM ai_usage
WHERE at >= now() - make_interval(days => $1::int)
GROUP BY 1, 2, 3, 4
ORDER BY 1 DESC, 2, 3, 4
`

type ListAIUsageDailyRow struct {
	Day          pgtype.Date `json:"day"`
	Kind         string      `json:"kind"`
	Provider     string      `json:"provider"`
	Model        string      `json:"model"`
	Calls        int64       `json:"calls"`
	Failed       int64       `json:"failed"`
	InputTokens  int64       `json:"input_tokens"`
	OutputTokens int64       `json:"output_tokens"`
	Characters   int64       `json:"characters"`
	AudioSeconds float64     `json:"audio_seconds"`
}

// Gộp theo ngày + model: đủ chi tiết để so hai model với nhau, đủ thô để bảng
// không dài hơn một màn hình sau một tuần chạy thật.
func (q *Queries) ListAIUsageDaily(ctx context.Context, days int32) ([]ListAIUsageDailyRow, error) {
	rows, err := q.db.Query(ctx, listAIUsageDaily, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAIUsageDailyRow{}
	for rows.Next() {
		var i ListAIUsageDailyRow
		if err := rows.Scan(
			&i.Day,
			&i.Kind,
			&i.Provider,
			&i.Model,
			&i.Calls,
			&i.Failed,
			&i.InputTokens,
			&i.OutputTokens,
			&i.Characters,
			&i.AudioSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAIUsage = `-- name: RecordAIUsage :exec
INSERT INTO ai_usage (
  kind, provider, model, user_id, input_tokens, output_tokens, characters, audio_seconds, ok
) VALUES (
  $1, $2, $3, $9, $4, $5, $6, $7, $8
)
`

type RecordAIUsageParams struct {
	Kind         string     `json:"kind"`
	Provider     string     `json:"provider"`
	Model        string     `json:"model"`
	InputTokens  int64      `json:"input_tokens"`
	OutputTokens int64      `json:"output_tokens"`
	Characters   int64      `json:"characters"`
	AudioSeconds float64    `json:"audio_seconds"`
	Ok           bool       `json:"ok"`
	UserID       *uuid.UUID `json:"user_id"`
}

func (q *Queries) RecordAIUsage(ctx context.Context, arg RecordAIUsageParams) error {
	_, err := q.db.Exec(ctx, recordAIUsage,
		arg.Kind,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Characters,
		arg.AudioSeconds,
		arg.Ok,
		arg.UserID,
	)
	return err
}
