// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const clearUserMultimeToken = `-- name: ClearUserMultimeToken :exec
UPDATE app_user
SET multime_access_token = NULL, multime_refresh_token = NULL
WHERE id = $1
`

// Token hết hiệu lực và refresh cũng thất bại -> buộc user đăng nhập lại.
func (q *Queries) ClearUserMultimeToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserMultimeToken, id)
	return err
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM app_user WHERE role = 'admin' AND is_active = TRUE
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM app_user
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, is_active, created_at, role, strongbody_user_id, avatar_url, multime_access_token, multime_refresh_token, multime_token_at, last_login_at FROM app_user WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.Role,
		&i.StrongbodyUserID,
		&i.AvatarUrl,
		&i.MultimeAccessToken,
		&i.MultimeRefreshToken,
		&i.MultimeTokenAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, is_active, created_at, role, strongbody_user_id, avatar_url, multime_access_token, multime_refresh_token, multime_token_at, last_login_at FROM app_user WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.Role,
		&i.StrongbodyUserID,
		&i.AvatarUrl,
		&i.MultimeAccessToken,
		&i.MultimeRefreshToken,
		&i.MultimeTokenAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, full_name, is_active, created_at, role, strongbody_user_id, avatar_url, multime_access_token, multime_refresh_token, multime_token_at, last_login_at FROM app_user
ORDER BY
  CASE WHEN $1::text = 'asc' THEN created_at END ASC,
  created_at DESC
LIMIT $3 OFFSET $2
`

type ListUsersParams struct {
	Dir string `json:"dir"`
	Off int32  `json:"off"`
	Lim int32  `json:"lim"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Dir, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUser{}
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.IsActive,
			&i.CreatedAt,
			&i.Role,
			&i.StrongbodyUserID,
			&i.AvatarUrl,
			&i.MultimeAccessToken,
			&i.MultimeRefreshToken,
			&i.MultimeTokenAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE app_user SET is_active = $2 WHERE id = $1 RETURNING id, email, password_hash, full_name, is_active, created_at, role, strongbody_user_id, avatar_url, multime_access_token, multime_refresh_token, multime_token_at, last_login_at
`

type SetUserActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.IsActive)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.Role,
		&i.StrongbodyUserID,
		&i.AvatarUrl,
		&i.MultimeAccessToken,
		&i.MultimeRefreshToken,
		&i.MultimeTokenAt,
		&i.LastLoginAt,
	)
	return i, err
}

const setUserMultimeToken = `-- name: SetUserMultimeToken :exec
UPDATE app_user
SET multime_access_token = $2, multime_token_at = now()
WHERE id = $1
`

type SetUserMultimeTokenParams struct {
	ID                 uuid.UUID `json:"id"`
	MultimeAccessToken *string   `json:"multime_access_token"`
}

// Cập nhật access token sau khi refresh với strongbody.
func (q *Queries) SetUserMultimeToken(ctx context.Context, arg SetUserMultimeTokenParams) error {
	_, err := q.db.Exec(ctx, setUserMultimeToken, arg.ID, arg.MultimeAccessToken)
	return err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE app_user SET role = $2 WHERE id = $1 RETURNING id, email, password_hash, full_name, is_active, created_at, role, strongbody_user_id, avatar_url, multime_access_token, multime_refresh_token, multime_token_at, last_login_at
`

type SetUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, setUserRole, arg.ID, arg.Role)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.Role,
		&i.StrongbodyUserID,
		&i.AvatarUrl,
		&i.MultimeAccessToken,
		&i.MultimeRefreshToken,
		&i.MultimeTokenAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertUserFromSSO = `-- name: UpsertUserFromSSO :one
INSERT INTO app_user (
  strongbody_user_id, email, full_name, avatar_url, role,
  multime_access_token, multime_refresh_token, multime_token_at, last_login_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, now(), now()
)
ON CONFLICT (email) DO UPDATE SET
  strongbody_user_id    = EXCLUDED.strongbody_user_id,
  full_name             = COALESCE(EXCLUDED.full_name, app_user.full_name),
  avatar_url            = COALESCE(EXCLUDED.avatar_url, app_user.avatar_url),
  multime_access_token  = EXCLUDED.multime_access_token,
  multime_refresh_token = EXCLUDED.multime_refresh_token,
  multime_token_at      = now(),
  last_login_at         = now(),
  is_active             = TRUE
RETURNING id, email, password_hash, full_name, is_active, created_at, role, strongbody_user_id, avatar_url, multime_access_token, multime_refresh_token, multime_token_at, last_login_at
`

type UpsertUserFromSSOParams struct {
	StrongbodyUserID    *int64  `json:"strongbody_user_id"`
	Email               string  `json:"email"`
	FullName            *string `json:"full_name"`
	AvatarUrl           *string `json:"avatar_url"`
	Role                string  `json:"role"`
	MultimeAccessToken  *string `json:"multime_access_token"`
	MultimeRefreshToken *string `json:"multime_refresh_token"`
}

// Đăng nhập bằng strongbody: tạo user nếu chưa có, cập nhật thông tin + token
// nếu đã có. Role của lần tạo đầu do $5 quyết định, các lần sau KHÔNG ghi đè
// (admin đã cấp quyền thì giữ nguyên).
func (q *Queries) UpsertUserFromSSO(ctx context.Context, arg UpsertUserFromSSOParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, upsertUserFromSSO,
		arg.StrongbodyUserID,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
		arg.Role,
		arg.MultimeAccessToken,
		arg.MultimeRefreshToken,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.CreatedAt,
		&i.Role,
		&i.StrongbodyUserID,
		&i.AvatarUrl,
		&i.MultimeAccessToken,
		&i.MultimeRefreshToken,
		&i.MultimeTokenAt,
		&i.LastLoginAt,
	)
	return i, err
}
