// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_setting.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getAppSetting = `-- name: GetAppSetting :one
SELECT key, value, updated_by, updated_at FROM app_setting WHERE key = $1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSetting, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value, updated_by, updated_at FROM app_setting ORDER BY key
`

func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.Query(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppSetting = `-- name: UpsertAppSetting :one
INSERT INTO app_setting (key, value, updated_by, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING key, value, updated_by, updated_at
`

type UpsertAppSettingParams struct {
	Key       string     `json:"key"`
	Value     []byte     `json:"value"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, upsertAppSetting, arg.Key, arg.Value, arg.UpdatedBy)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
