// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (user_id, action, object_type, object_id, changes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, action, object_type, object_id, changes, created_at
`

type CreateAuditLogParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Action     string    `json:"action"`
	ObjectType string    `json:"object_type"`
	ObjectID   uuid.UUID `json:"object_id"`
	Changes    []byte    `json:"changes"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.Changes,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ObjectType,
		&i.ObjectID,
		&i.Changes,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, object_type, object_id, changes, created_at FROM audit_log
WHERE ($1::varchar IS NULL OR object_type = $1)
  AND ($2::uuid      IS NULL OR object_id   = $2)
  AND ($3::uuid        IS NULL OR user_id     = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListAuditLogsParams struct {
	ObjectType *string    `json:"object_type"`
	ObjectID   *uuid.UUID `json:"object_id"`
	UserID     *uuid.UUID `json:"user_id"`
	Off        int32      `json:"off"`
	Lim        int32      `json:"lim"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ObjectType,
		arg.ObjectID,
		arg.UserID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ObjectType,
			&i.ObjectID,
			&i.Changes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
