// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog_cache.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countriesSyncedAt = `-- name: CountriesSyncedAt :one
SELECT COALESCE(MIN(synced_at), 'epoch'::timestamptz)::timestamptz AS synced_at,
       COUNT(*)::bigint AS total
FROM country
`

type CountriesSyncedAtRow struct {
	SyncedAt time.Time `json:"synced_at"`
	Total    int64     `json:"total"`
}

// Mốc đồng bộ cũ nhất trong bảng: chỉ cần 1 bản ghi quá hạn là đồng bộ lại cả
// danh mục, vì chúng luôn được ghi cùng một lượt.
func (q *Queries) CountriesSyncedAt(ctx context.Context) (CountriesSyncedAtRow, error) {
	row := q.db.QueryRow(ctx, countriesSyncedAt)
	var i CountriesSyncedAtRow
	err := row.Scan(&i.SyncedAt, &i.Total)
	return i, err
}

const hashtagsSyncedAt = `-- name: HashtagsSyncedAt :one
SELECT COALESCE(MIN(synced_at), 'epoch'::timestamptz)::timestamptz AS synced_at,
       COUNT(*)::bigint AS total
FROM hashtag
`

type HashtagsSyncedAtRow struct {
	SyncedAt time.Time `json:"synced_at"`
	Total    int64     `json:"total"`
}

func (q *Queries) HashtagsSyncedAt(ctx context.Context) (HashtagsSyncedAtRow, error) {
	row := q.db.QueryRow(ctx, hashtagsSyncedAt)
	var i HashtagsSyncedAtRow
	err := row.Scan(&i.SyncedAt, &i.Total)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT id, name, code, sort_order, synced_at FROM country ORDER BY sort_order, name
`

// Thứ tự nghiệp vụ trước, rồi alphabet cho phần còn lại — xem cột sort_order.
func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.SortOrder,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHashtags = `-- name: ListHashtags :many
SELECT id, name, normalized_name, slug, voice_tag_kind, is_featured
FROM hashtag
WHERE $1::text = ''
   OR normalized_name LIKE $1::text || '%'
   OR lower(name) LIKE '%' || $1::text || '%'
ORDER BY
  -- Khớp từ đầu chuỗi đứng trước khớp ở giữa: gõ "new" thì "News" phải lên
  -- trước "Renewable".
  (normalized_name LIKE $1::text || '%') DESC,
  is_featured DESC,
  voice_tag_kind,
  ordering,
  name
LIMIT $2
`

type ListHashtagsParams struct {
	Q   string `json:"q"`
	Lim int32  `json:"lim"`
}

type ListHashtagsRow struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
	Slug           string `json:"slug"`
	VoiceTagKind   string `json:"voice_tag_kind"`
	IsFeatured     bool   `json:"is_featured"`
}

// Danh sách cho ô chọn: tag MultiMe tuyển chọn (is_featured, rồi `system`) lên
// trước, phần còn lại theo ordering/tên.
//
// `q` rỗng = lấy phần đầu danh mục. Có `q` thì lọc ngay trong DB: danh mục có
// ~94.000 tag nên không thể đẩy hết về trình duyệt để lọc tại chỗ.
func (q *Queries) ListHashtags(ctx context.Context, arg ListHashtagsParams) ([]ListHashtagsRow, error) {
	rows, err := q.db.Query(ctx, listHashtags, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHashtagsRow{}
	for rows.Next() {
		var i ListHashtagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Slug,
			&i.VoiceTagKind,
			&i.IsFeatured,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickCountryForLanguage = `-- name: PickCountryForLanguage :one
SELECT id FROM country
WHERE lower(btrim(name)) = ANY($1::text[])
ORDER BY sort_order, name
LIMIT 1
`

// Bốc 1 quốc gia trong nhóm nói cùng một ngôn ngữ, ưu tiên theo sort_order.
//
// Dùng cho kênh bật "Random author": bài đọc bằng tiếng Việt mà đứng tên tài
// khoản Nhật thì người nghe thấy ngay là sai, nên việc bốc phải bị chặn lại
// trong đúng nhóm quốc gia của ngôn ngữ đó. Tên quốc gia do
// domain.CountriesForLanguage đưa xuống.
//
// So khớp không phân biệt hoa thường và bỏ khoảng trắng thừa: `country.name`
// là bản sao từ Strongbody, không phải chuỗi ta tự kiểm soát.
func (q *Queries) PickCountryForLanguage(ctx context.Context, names []string) (int64, error) {
	row := q.db.QueryRow(ctx, pickCountryForLanguage, names)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setVoiceAuthor = `-- name: SetVoiceAuthor :exec
UPDATE voice
SET author_id = $1, author_email = $2
WHERE id = $3
`

type SetVoiceAuthorParams struct {
	AuthorID    *int64    `json:"author_id"`
	AuthorEmail *string   `json:"author_email"`
	ID          uuid.UUID `json:"id"`
}

// Ghi lại tài khoản đã BỐC lúc đăng. Không dùng UpdateVoice vì đây là worker
// chốt kết quả của một lần bốc, không phải người dùng sửa metadata.
func (q *Queries) SetVoiceAuthor(ctx context.Context, arg SetVoiceAuthorParams) error {
	_, err := q.db.Exec(ctx, setVoiceAuthor, arg.AuthorID, arg.AuthorEmail, arg.ID)
	return err
}

const upsertCountry = `-- name: UpsertCountry :exec
INSERT INTO country (id, name, code, sort_order, synced_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, code = EXCLUDED.code,
    sort_order = EXCLUDED.sort_order, synced_at = now()
`

type UpsertCountryParams struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	Code      *string `json:"code"`
	SortOrder int32   `json:"sort_order"`
}

func (q *Queries) UpsertCountry(ctx context.Context, arg UpsertCountryParams) error {
	_, err := q.db.Exec(ctx, upsertCountry,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.SortOrder,
	)
	return err
}

const upsertHashtag = `-- name: UpsertHashtag :exec
INSERT INTO hashtag (id, name, normalized_name, slug, voice_tag_kind, is_featured, ordering, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (id) DO UPDATE
SET name            = EXCLUDED.name,
    normalized_name = EXCLUDED.normalized_name,
    slug            = EXCLUDED.slug,
    voice_tag_kind  = EXCLUDED.voice_tag_kind,
    is_featured     = EXCLUDED.is_featured,
    ordering        = EXCLUDED.ordering,
    synced_at       = now()
`

type UpsertHashtagParams struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	NormalizedName string `json:"normalized_name"`
	Slug           string `json:"slug"`
	VoiceTagKind   string `json:"voice_tag_kind"`
	IsFeatured     bool   `json:"is_featured"`
	Ordering       int64  `json:"ordering"`
}

func (q *Queries) UpsertHashtag(ctx context.Context, arg UpsertHashtagParams) error {
	_, err := q.db.Exec(ctx, upsertHashtag,
		arg.ID,
		arg.Name,
		arg.NormalizedName,
		arg.Slug,
		arg.VoiceTagKind,
		arg.IsFeatured,
		arg.Ordering,
	)
	return err
}
