// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fetch_error_stat.sql

package repository

import (
	"context"
)

const bumpFetchErrorStat = `-- name: BumpFetchErrorStat :exec
INSERT INTO fetch_error_stat (day, platform, kind, count, last_at)
VALUES (CURRENT_DATE, $1, $2, 1, now())
ON CONFLICT (day, platform, kind) DO UPDATE
SET count = fetch_error_stat.count + 1, last_at = now()
`

type BumpFetchErrorStatParams struct {
	Platform string `json:"platform"`
	Kind     string `json:"kind"`
}

// Đếm 1 lần bị nền tảng chặn. Gộp theo ngày nên bảng không phình theo từng lỗi,
// và vẫn đủ để trả lời câu hỏi duy nhất nó sinh ra để trả lời: nền tảng nào
// đang bị chặn nhiều tới mức đáng mua proxy.
func (q *Queries) BumpFetchErrorStat(ctx context.Context, arg BumpFetchErrorStatParams) error {
	_, err := q.db.Exec(ctx, bumpFetchErrorStat, arg.Platform, arg.Kind)
	return err
}

const listFetchErrorStats = `-- name: ListFetchErrorStats :many
SELECT day, platform, kind, count, last_at FROM fetch_error_stat
WHERE day >= CURRENT_DATE - $1::int
ORDER BY day DESC, platform, kind
`

func (q *Queries) ListFetchErrorStats(ctx context.Context, days int32) ([]FetchErrorStat, error) {
	rows, err := q.db.Query(ctx, listFetchErrorStats, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchErrorStat{}
	for rows.Next() {
		var i FetchErrorStat
		if err := rows.Scan(
			&i.Day,
			&i.Platform,
			&i.Kind,
			&i.Count,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
