// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_breaking.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cascadeLanguageFromListBreaking = `-- name: CascadeLanguageFromListBreaking :execrows
UPDATE source_post SET language = $1
WHERE list_breaking_id = $2
  AND language <> $1
`

type CascadeLanguageFromListBreakingParams struct {
	Language string     `json:"language"`
	ListID   *uuid.UUID `json:"list_id"`
}

// Đối xứng với CascadeLanguageFromListScheduled — xem lý do ở đó.
func (q *Queries) CascadeLanguageFromListBreaking(ctx context.Context, arg CascadeLanguageFromListBreakingParams) (int64, error) {
	result, err := q.db.Exec(ctx, cascadeLanguageFromListBreaking, arg.Language, arg.ListID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cascadeVoiceLanguageFromListBreaking = `-- name: CascadeVoiceLanguageFromListBreaking :execrows
UPDATE voice v SET language = $1
FROM source_post sp
WHERE sp.id = v.source_post_id
  AND sp.list_breaking_id = $2
  AND v.voice_file_url IS NULL
  AND v.language <> $1
`

type CascadeVoiceLanguageFromListBreakingParams struct {
	Language string     `json:"language"`
	ListID   *uuid.UUID `json:"list_id"`
}

func (q *Queries) CascadeVoiceLanguageFromListBreaking(ctx context.Context, arg CascadeVoiceLanguageFromListBreakingParams) (int64, error) {
	result, err := q.db.Exec(ctx, cascadeVoiceLanguageFromListBreaking, arg.Language, arg.ListID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countListBreakings = `-- name: CountListBreakings :one
SELECT COUNT(*)
FROM list_breaking lb
WHERE ($1::varchar   IS NULL OR lb.status     = $1)
  AND ($2::varchar IS NULL OR lb.platform   = $2)
  AND ($3::uuid  IS NULL OR lb.created_by = $3)
  AND ($4::text      IS NULL OR lb.source_url ~* $4)
`

type CountListBreakingsParams struct {
	Status    *string    `json:"status"`
	Platform  *string    `json:"platform"`
	CreatedBy *uuid.UUID `json:"created_by"`
	Search    *string    `json:"search"`
}

// Tổng số kênh khớp bộ lọc, để bảng phân trang biết có bao nhiêu trang.
func (q *Queries) CountListBreakings(ctx context.Context, arg CountListBreakingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListBreakings,
		arg.Status,
		arg.Platform,
		arg.CreatedBy,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListBreaking = `-- name: CreateListBreaking :one
INSERT INTO list_breaking (
  source_url, platform, content_type, collect_mode, prompt_id, regex_patterns,
  language_default, auto_process, auto_publish, status, scan_limit, scan_interval,
  created_by, llm_api_set_id,
  timezone, active_from_min, active_to_min, active_weekdays,
  backfill_limit, max_posts_per_run
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
  $14, $15,
  $16, $17, $18,
  $19, $20
)
RETURNING id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, backfill_limit, backfill_done_at, backfill_excluded_ids, max_posts_per_run, last_error
`

type CreateListBreakingParams struct {
	SourceUrl       string          `json:"source_url"`
	Platform        string          `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     string          `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	RegexPatterns   []string        `json:"regex_patterns"`
	LanguageDefault string          `json:"language_default"`
	AutoProcess     bool            `json:"auto_process"`
	AutoPublish     bool            `json:"auto_publish"`
	Status          string          `json:"status"`
	ScanLimit       int32           `json:"scan_limit"`
	ScanInterval    pgtype.Interval `json:"scan_interval"`
	CreatedBy       uuid.UUID       `json:"created_by"`
	LlmApiSetID     *uuid.UUID      `json:"llm_api_set_id"`
	Timezone        string          `json:"timezone"`
	ActiveFromMin   *int16          `json:"active_from_min"`
	ActiveToMin     *int16          `json:"active_to_min"`
	ActiveWeekdays  []int16         `json:"active_weekdays"`
	BackfillLimit   int32           `json:"backfill_limit"`
	MaxPostsPerRun  *int32          `json:"max_posts_per_run"`
}

func (q *Queries) CreateListBreaking(ctx context.Context, arg CreateListBreakingParams) (ListBreaking, error) {
	row := q.db.QueryRow(ctx, createListBreaking,
		arg.SourceUrl,
		arg.Platform,
		arg.ContentType,
		arg.CollectMode,
		arg.PromptID,
		arg.RegexPatterns,
		arg.LanguageDefault,
		arg.AutoProcess,
		arg.AutoPublish,
		arg.Status,
		arg.ScanLimit,
		arg.ScanInterval,
		arg.CreatedBy,
		arg.LlmApiSetID,
		arg.Timezone,
		arg.ActiveFromMin,
		arg.ActiveToMin,
		arg.ActiveWeekdays,
		arg.BackfillLimit,
		arg.MaxPostsPerRun,
	)
	var i ListBreaking
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.LanguageDefault,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RegexPatterns,
		&i.ScanLimit,
		&i.ScanInterval,
		&i.LastScannedAt,
		&i.LlmApiSetID,
		&i.Timezone,
		&i.ActiveFromMin,
		&i.ActiveToMin,
		&i.ActiveWeekdays,
		&i.BackfillLimit,
		&i.BackfillDoneAt,
		&i.BackfillExcludedIds,
		&i.MaxPostsPerRun,
		&i.LastError,
	)
	return i, err
}

const deleteListBreaking = `-- name: DeleteListBreaking :execrows
DELETE FROM list_breaking WHERE id = $1
`

func (q *Queries) DeleteListBreaking(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteListBreaking, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getListBreaking = `-- name: GetListBreaking :one
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, backfill_limit, backfill_done_at, backfill_excluded_ids, max_posts_per_run, last_error FROM list_breaking WHERE id = $1
`

func (q *Queries) GetListBreaking(ctx context.Context, id uuid.UUID) (ListBreaking, error) {
	row := q.db.QueryRow(ctx, getListBreaking, id)
	var i ListBreaking
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.LanguageDefault,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RegexPatterns,
		&i.ScanLimit,
		&i.ScanInterval,
		&i.LastScannedAt,
		&i.LlmApiSetID,
		&i.Timezone,
		&i.ActiveFromMin,
		&i.ActiveToMin,
		&i.ActiveWeekdays,
		&i.BackfillLimit,
		&i.BackfillDoneAt,
		&i.BackfillExcludedIds,
		&i.MaxPostsPerRun,
		&i.LastError,
	)
	return i, err
}

const listActiveListBreakings = `-- name: ListActiveListBreakings :many
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, backfill_limit, backfill_done_at, backfill_excluded_ids, max_posts_per_run, last_error FROM list_breaking WHERE status = 'active' ORDER BY created_at
`

func (q *Queries) ListActiveListBreakings(ctx context.Context) ([]ListBreaking, error) {
	rows, err := q.db.Query(ctx, listActiveListBreakings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBreaking{}
	for rows.Next() {
		var i ListBreaking
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.LanguageDefault,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RegexPatterns,
			&i.ScanLimit,
			&i.ScanInterval,
			&i.LastScannedAt,
			&i.LlmApiSetID,
			&i.Timezone,
			&i.ActiveFromMin,
			&i.ActiveToMin,
			&i.ActiveWeekdays,
			&i.BackfillLimit,
			&i.BackfillDoneAt,
			&i.BackfillExcludedIds,
			&i.MaxPostsPerRun,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueListBreakings = `-- name: ListDueListBreakings :many
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, backfill_limit, backfill_done_at, backfill_excluded_ids, max_posts_per_run, last_error FROM list_breaking
WHERE status = 'active'
  AND (
    last_scanned_at IS NULL
    OR last_scanned_at + COALESCE(scan_interval, $1::interval) <= now()
  )
ORDER BY last_scanned_at ASC NULLS FIRST
`

// Chỉ lấy kênh đã quá khoảng nghỉ của chính nó (scan_interval), fallback về
// khoảng nghỉ mặc định của hệ thống khi kênh không cấu hình riêng.
func (q *Queries) ListDueListBreakings(ctx context.Context, defaultInterval pgtype.Interval) ([]ListBreaking, error) {
	rows, err := q.db.Query(ctx, listDueListBreakings, defaultInterval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBreaking{}
	for rows.Next() {
		var i ListBreaking
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.LanguageDefault,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RegexPatterns,
			&i.ScanLimit,
			&i.ScanInterval,
			&i.LastScannedAt,
			&i.LlmApiSetID,
			&i.Timezone,
			&i.ActiveFromMin,
			&i.ActiveToMin,
			&i.ActiveWeekdays,
			&i.BackfillLimit,
			&i.BackfillDoneAt,
			&i.BackfillExcludedIds,
			&i.MaxPostsPerRun,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListBreakings = `-- name: ListListBreakings :many
SELECT lb.id, lb.source_url, lb.platform, lb.content_type, lb.collect_mode, lb.prompt_id, lb.language_default, lb.auto_process, lb.auto_publish, lb.status, lb.created_by, lb.created_at, lb.regex_patterns, lb.scan_limit, lb.scan_interval, lb.last_scanned_at, lb.llm_api_set_id, lb.timezone, lb.active_from_min, lb.active_to_min, lb.active_weekdays, lb.backfill_limit, lb.backfill_done_at, lb.backfill_excluded_ids, lb.max_posts_per_run, lb.last_error, u.email AS created_by_email,
       (SELECT COUNT(*) FROM source_post sp
         WHERE sp.list_breaking_id = lb.id) AS post_count,
       (SELECT COUNT(*) FROM voice v
          JOIN source_post sp2 ON sp2.id = v.source_post_id
         WHERE sp2.list_breaking_id = lb.id) AS voice_count
FROM list_breaking lb
JOIN app_user u ON u.id = lb.created_by
WHERE ($1::varchar   IS NULL OR lb.status     = $1)
  AND ($2::varchar IS NULL OR lb.platform   = $2)
  AND ($3::uuid  IS NULL OR lb.created_by = $3)
  AND ($4::text      IS NULL OR lb.source_url ~* $4)
ORDER BY
  CASE WHEN $5::text = 'last_scanned_at' AND $6::text = 'asc'
       THEN lb.last_scanned_at END ASC NULLS LAST,
  CASE WHEN $5::text = 'last_scanned_at' AND $6::text = 'desc'
       THEN lb.last_scanned_at END DESC NULLS LAST,
  CASE WHEN $6::text = 'asc' AND $5::text <> 'last_scanned_at'
       THEN lb.created_at END ASC,
  lb.created_at DESC
LIMIT $8 OFFSET $7
`

type ListListBreakingsParams struct {
	Status    *string    `json:"status"`
	Platform  *string    `json:"platform"`
	CreatedBy *uuid.UUID `json:"created_by"`
	Search    *string    `json:"search"`
	Sort      string     `json:"sort"`
	Dir       string     `json:"dir"`
	Off       int32      `json:"off"`
	Lim       int32      `json:"lim"`
}

type ListListBreakingsRow struct {
	ID                  uuid.UUID       `json:"id"`
	SourceUrl           string          `json:"source_url"`
	Platform            string          `json:"platform"`
	ContentType         *string         `json:"content_type"`
	CollectMode         string          `json:"collect_mode"`
	PromptID            *uuid.UUID      `json:"prompt_id"`
	LanguageDefault     string          `json:"language_default"`
	AutoProcess         bool            `json:"auto_process"`
	AutoPublish         bool            `json:"auto_publish"`
	Status              string          `json:"status"`
	CreatedBy           uuid.UUID       `json:"created_by"`
	CreatedAt           time.Time       `json:"created_at"`
	RegexPatterns       []string        `json:"regex_patterns"`
	ScanLimit           int32           `json:"scan_limit"`
	ScanInterval        pgtype.Interval `json:"scan_interval"`
	LastScannedAt       *time.Time      `json:"last_scanned_at"`
	LlmApiSetID         *uuid.UUID      `json:"llm_api_set_id"`
	Timezone            string          `json:"timezone"`
	ActiveFromMin       *int16          `json:"active_from_min"`
	ActiveToMin         *int16          `json:"active_to_min"`
	ActiveWeekdays      []int16         `json:"active_weekdays"`
	BackfillLimit       int32           `json:"backfill_limit"`
	BackfillDoneAt      *time.Time      `json:"backfill_done_at"`
	BackfillExcludedIds []string        `json:"backfill_excluded_ids"`
	MaxPostsPerRun      *int32          `json:"max_posts_per_run"`
	LastError           *string         `json:"last_error"`
	CreatedByEmail      string          `json:"created_by_email"`
	PostCount           int64           `json:"post_count"`
	VoiceCount          int64           `json:"voice_count"`
}

// Hai số đếm, cùng lý do và cùng cách dựng với ListListScheduleds.
// Sắp xếp động theo cột thời gian đang chọn; mặc định kênh mới nhất trước.
func (q *Queries) ListListBreakings(ctx context.Context, arg ListListBreakingsParams) ([]ListListBreakingsRow, error) {
	rows, err := q.db.Query(ctx, listListBreakings,
		arg.Status,
		arg.Platform,
		arg.CreatedBy,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListBreakingsRow{}
	for rows.Next() {
		var i ListListBreakingsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.LanguageDefault,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RegexPatterns,
			&i.ScanLimit,
			&i.ScanInterval,
			&i.LastScannedAt,
			&i.LlmApiSetID,
			&i.Timezone,
			&i.ActiveFromMin,
			&i.ActiveToMin,
			&i.ActiveWeekdays,
			&i.BackfillLimit,
			&i.BackfillDoneAt,
			&i.BackfillExcludedIds,
			&i.MaxPostsPerRun,
			&i.LastError,
			&i.CreatedByEmail,
			&i.PostCount,
			&i.VoiceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markListBreakingBackfilled = `-- name: MarkListBreakingBackfilled :exec
UPDATE list_breaking
SET backfill_done_at = now(), backfill_excluded_ids = $1
WHERE id = $2
`

type MarkListBreakingBackfilledParams struct {
	ExcludedIds []string  `json:"excluded_ids"`
	ID          uuid.UUID `json:"id"`
}

// Đóng vòng quét đầu: ghi mốc và nhớ những id đã cố tình bỏ qua.
//
// Kênh Breaking không có mốc đồng bộ nên nếu không nhớ, chính những bài này sẽ
// quay lại ở vòng sau như thể vừa đăng.
func (q *Queries) MarkListBreakingBackfilled(ctx context.Context, arg MarkListBreakingBackfilledParams) error {
	_, err := q.db.Exec(ctx, markListBreakingBackfilled, arg.ExcludedIds, arg.ID)
	return err
}

const setListBreakingScanError = `-- name: SetListBreakingScanError :exec
UPDATE list_breaking SET last_error = $1 WHERE id = $2
`

type SetListBreakingScanErrorParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

// Ghi lỗi của vòng quét gần nhất lên kênh, hoặc xoá nó khi vòng quét chạy sạch.
// Người dùng chỉ nhìn thấy bảng kênh, không nhìn thấy log worker.
func (q *Queries) SetListBreakingScanError(ctx context.Context, arg SetListBreakingScanErrorParams) error {
	_, err := q.db.Exec(ctx, setListBreakingScanError, arg.LastError, arg.ID)
	return err
}

const touchListBreakingScanned = `-- name: TouchListBreakingScanned :exec
UPDATE list_breaking SET last_scanned_at = now() WHERE id = $1
`

func (q *Queries) TouchListBreakingScanned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchListBreakingScanned, id)
	return err
}

const updateListBreaking = `-- name: UpdateListBreaking :one
UPDATE list_breaking
SET source_url       = COALESCE($1, source_url),
    platform         = COALESCE($2, platform),
    content_type     = COALESCE($3, content_type),
    collect_mode     = COALESCE($4, collect_mode),
    prompt_id        = COALESCE($5, prompt_id),
    regex_patterns   = COALESCE($6, regex_patterns),
    language_default = COALESCE($7, language_default),
    auto_process     = COALESCE($8, auto_process),
    auto_publish     = COALESCE($9, auto_publish),
    status           = COALESCE($10, status),
    scan_limit       = COALESCE($11, scan_limit),
    scan_interval    = COALESCE($12, scan_interval),
    llm_api_set_id   = COALESCE($13, llm_api_set_id),
    timezone         = COALESCE($14, timezone),
    active_from_min  = CASE WHEN $15::bool THEN NULL
                            ELSE COALESCE($16, active_from_min) END,
    active_to_min    = CASE WHEN $15::bool THEN NULL
                            ELSE COALESCE($17, active_to_min) END,
    active_weekdays  = COALESCE($18, active_weekdays),
    backfill_limit   = COALESCE($19, backfill_limit),
    -- Cùng lý do với khung giờ: NULL ở max_posts_per_run nghĩa là "không giới
    -- hạn", nên chỉ COALESCE thì người dùng đặt trần rồi không gỡ ra được nữa.
    max_posts_per_run = CASE WHEN $20::bool THEN NULL
                             ELSE COALESCE($21, max_posts_per_run) END
WHERE id = $22
RETURNING id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, backfill_limit, backfill_done_at, backfill_excluded_ids, max_posts_per_run, last_error
`

type UpdateListBreakingParams struct {
	SourceUrl       *string         `json:"source_url"`
	Platform        *string         `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     *string         `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	RegexPatterns   []string        `json:"regex_patterns"`
	LanguageDefault *string         `json:"language_default"`
	AutoProcess     *bool           `json:"auto_process"`
	AutoPublish     *bool           `json:"auto_publish"`
	Status          *string         `json:"status"`
	ScanLimit       *int32          `json:"scan_limit"`
	ScanInterval    pgtype.Interval `json:"scan_interval"`
	LlmApiSetID     *uuid.UUID      `json:"llm_api_set_id"`
	Timezone        *string         `json:"timezone"`
	ClearWindow     bool            `json:"clear_window"`
	ActiveFromMin   *int16          `json:"active_from_min"`
	ActiveToMin     *int16          `json:"active_to_min"`
	ActiveWeekdays  []int16         `json:"active_weekdays"`
	BackfillLimit   *int32          `json:"backfill_limit"`
	ClearMaxPosts   bool            `json:"clear_max_posts"`
	MaxPostsPerRun  *int32          `json:"max_posts_per_run"`
	ID              uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateListBreaking(ctx context.Context, arg UpdateListBreakingParams) (ListBreaking, error) {
	row := q.db.QueryRow(ctx, updateListBreaking,
		arg.SourceUrl,
		arg.Platform,
		arg.ContentType,
		arg.CollectMode,
		arg.PromptID,
		arg.RegexPatterns,
		arg.LanguageDefault,
		arg.AutoProcess,
		arg.AutoPublish,
		arg.Status,
		arg.ScanLimit,
		arg.ScanInterval,
		arg.LlmApiSetID,
		arg.Timezone,
		arg.ClearWindow,
		arg.ActiveFromMin,
		arg.ActiveToMin,
		arg.ActiveWeekdays,
		arg.BackfillLimit,
		arg.ClearMaxPosts,
		arg.MaxPostsPerRun,
		arg.ID,
	)
	var i ListBreaking
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.LanguageDefault,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RegexPatterns,
		&i.ScanLimit,
		&i.ScanInterval,
		&i.LastScannedAt,
		&i.LlmApiSetID,
		&i.Timezone,
		&i.ActiveFromMin,
		&i.ActiveToMin,
		&i.ActiveWeekdays,
		&i.BackfillLimit,
		&i.BackfillDoneAt,
		&i.BackfillExcludedIds,
		&i.MaxPostsPerRun,
		&i.LastError,
	)
	return i, err
}
