// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_breaking.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createListBreaking = `-- name: CreateListBreaking :one
INSERT INTO list_breaking (
  source_url, platform, content_type, collect_mode, prompt_id, regex_patterns,
  language_default, auto_process, auto_publish, status, scan_limit, scan_interval,
  created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at
`

type CreateListBreakingParams struct {
	SourceUrl       string          `json:"source_url"`
	Platform        string          `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     string          `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	RegexPatterns   []string        `json:"regex_patterns"`
	LanguageDefault string          `json:"language_default"`
	AutoProcess     bool            `json:"auto_process"`
	AutoPublish     bool            `json:"auto_publish"`
	Status          string          `json:"status"`
	ScanLimit       int32           `json:"scan_limit"`
	ScanInterval    pgtype.Interval `json:"scan_interval"`
	CreatedBy       uuid.UUID       `json:"created_by"`
}

func (q *Queries) CreateListBreaking(ctx context.Context, arg CreateListBreakingParams) (ListBreaking, error) {
	row := q.db.QueryRow(ctx, createListBreaking,
		arg.SourceUrl,
		arg.Platform,
		arg.ContentType,
		arg.CollectMode,
		arg.PromptID,
		arg.RegexPatterns,
		arg.LanguageDefault,
		arg.AutoProcess,
		arg.AutoPublish,
		arg.Status,
		arg.ScanLimit,
		arg.ScanInterval,
		arg.CreatedBy,
	)
	var i ListBreaking
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.LanguageDefault,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RegexPatterns,
		&i.ScanLimit,
		&i.ScanInterval,
		&i.LastScannedAt,
	)
	return i, err
}

const deleteListBreaking = `-- name: DeleteListBreaking :execrows
DELETE FROM list_breaking WHERE id = $1
`

func (q *Queries) DeleteListBreaking(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteListBreaking, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getListBreaking = `-- name: GetListBreaking :one
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at FROM list_breaking WHERE id = $1
`

func (q *Queries) GetListBreaking(ctx context.Context, id uuid.UUID) (ListBreaking, error) {
	row := q.db.QueryRow(ctx, getListBreaking, id)
	var i ListBreaking
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.LanguageDefault,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RegexPatterns,
		&i.ScanLimit,
		&i.ScanInterval,
		&i.LastScannedAt,
	)
	return i, err
}

const listActiveListBreakings = `-- name: ListActiveListBreakings :many
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at FROM list_breaking WHERE status = 'active' ORDER BY created_at
`

func (q *Queries) ListActiveListBreakings(ctx context.Context) ([]ListBreaking, error) {
	rows, err := q.db.Query(ctx, listActiveListBreakings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBreaking{}
	for rows.Next() {
		var i ListBreaking
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.LanguageDefault,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RegexPatterns,
			&i.ScanLimit,
			&i.ScanInterval,
			&i.LastScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueListBreakings = `-- name: ListDueListBreakings :many
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at FROM list_breaking
WHERE status = 'active'
  AND (
    last_scanned_at IS NULL
    OR last_scanned_at + COALESCE(scan_interval, $1::interval) <= now()
  )
ORDER BY last_scanned_at ASC NULLS FIRST
`

// Chỉ lấy kênh đã quá khoảng nghỉ của chính nó (scan_interval), fallback về
// khoảng nghỉ mặc định của hệ thống khi kênh không cấu hình riêng.
func (q *Queries) ListDueListBreakings(ctx context.Context, defaultInterval pgtype.Interval) ([]ListBreaking, error) {
	rows, err := q.db.Query(ctx, listDueListBreakings, defaultInterval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBreaking{}
	for rows.Next() {
		var i ListBreaking
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.LanguageDefault,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RegexPatterns,
			&i.ScanLimit,
			&i.ScanInterval,
			&i.LastScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListBreakings = `-- name: ListListBreakings :many
SELECT lb.id, lb.source_url, lb.platform, lb.content_type, lb.collect_mode, lb.prompt_id, lb.language_default, lb.auto_process, lb.auto_publish, lb.status, lb.created_by, lb.created_at, lb.regex_patterns, lb.scan_limit, lb.scan_interval, lb.last_scanned_at, u.email AS created_by_email
FROM list_breaking lb
JOIN app_user u ON u.id = lb.created_by
WHERE ($1::varchar   IS NULL OR lb.status     = $1)
  AND ($2::varchar IS NULL OR lb.platform   = $2)
  AND ($3::uuid  IS NULL OR lb.created_by = $3)
  AND ($4::text      IS NULL OR lb.source_url ~* $4)
ORDER BY lb.created_at DESC
LIMIT $6 OFFSET $5
`

type ListListBreakingsParams struct {
	Status    *string    `json:"status"`
	Platform  *string    `json:"platform"`
	CreatedBy *uuid.UUID `json:"created_by"`
	Search    *string    `json:"search"`
	Off       int32      `json:"off"`
	Lim       int32      `json:"lim"`
}

type ListListBreakingsRow struct {
	ID              uuid.UUID       `json:"id"`
	SourceUrl       string          `json:"source_url"`
	Platform        string          `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     string          `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	LanguageDefault string          `json:"language_default"`
	AutoProcess     bool            `json:"auto_process"`
	AutoPublish     bool            `json:"auto_publish"`
	Status          string          `json:"status"`
	CreatedBy       uuid.UUID       `json:"created_by"`
	CreatedAt       time.Time       `json:"created_at"`
	RegexPatterns   []string        `json:"regex_patterns"`
	ScanLimit       int32           `json:"scan_limit"`
	ScanInterval    pgtype.Interval `json:"scan_interval"`
	LastScannedAt   *time.Time      `json:"last_scanned_at"`
	CreatedByEmail  string          `json:"created_by_email"`
}

func (q *Queries) ListListBreakings(ctx context.Context, arg ListListBreakingsParams) ([]ListListBreakingsRow, error) {
	rows, err := q.db.Query(ctx, listListBreakings,
		arg.Status,
		arg.Platform,
		arg.CreatedBy,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListBreakingsRow{}
	for rows.Next() {
		var i ListListBreakingsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.LanguageDefault,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RegexPatterns,
			&i.ScanLimit,
			&i.ScanInterval,
			&i.LastScannedAt,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchListBreakingScanned = `-- name: TouchListBreakingScanned :exec
UPDATE list_breaking SET last_scanned_at = now() WHERE id = $1
`

func (q *Queries) TouchListBreakingScanned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchListBreakingScanned, id)
	return err
}

const updateListBreaking = `-- name: UpdateListBreaking :one
UPDATE list_breaking
SET source_url       = COALESCE($1, source_url),
    platform         = COALESCE($2, platform),
    content_type     = COALESCE($3, content_type),
    collect_mode     = COALESCE($4, collect_mode),
    prompt_id        = COALESCE($5, prompt_id),
    regex_patterns   = COALESCE($6, regex_patterns),
    language_default = COALESCE($7, language_default),
    auto_process     = COALESCE($8, auto_process),
    auto_publish     = COALESCE($9, auto_publish),
    status           = COALESCE($10, status),
    scan_limit       = COALESCE($11, scan_limit),
    scan_interval    = COALESCE($12, scan_interval)
WHERE id = $13
RETURNING id, source_url, platform, content_type, collect_mode, prompt_id, language_default, auto_process, auto_publish, status, created_by, created_at, regex_patterns, scan_limit, scan_interval, last_scanned_at
`

type UpdateListBreakingParams struct {
	SourceUrl       *string         `json:"source_url"`
	Platform        *string         `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     *string         `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	RegexPatterns   []string        `json:"regex_patterns"`
	LanguageDefault *string         `json:"language_default"`
	AutoProcess     *bool           `json:"auto_process"`
	AutoPublish     *bool           `json:"auto_publish"`
	Status          *string         `json:"status"`
	ScanLimit       *int32          `json:"scan_limit"`
	ScanInterval    pgtype.Interval `json:"scan_interval"`
	ID              uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateListBreaking(ctx context.Context, arg UpdateListBreakingParams) (ListBreaking, error) {
	row := q.db.QueryRow(ctx, updateListBreaking,
		arg.SourceUrl,
		arg.Platform,
		arg.ContentType,
		arg.CollectMode,
		arg.PromptID,
		arg.RegexPatterns,
		arg.LanguageDefault,
		arg.AutoProcess,
		arg.AutoPublish,
		arg.Status,
		arg.ScanLimit,
		arg.ScanInterval,
		arg.ID,
	)
	var i ListBreaking
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.LanguageDefault,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RegexPatterns,
		&i.ScanLimit,
		&i.ScanInterval,
		&i.LastScannedAt,
	)
	return i, err
}
