// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_scheduled.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cascadeLanguageFromListScheduled = `-- name: CascadeLanguageFromListScheduled :execrows
UPDATE source_post SET language = $1
WHERE list_scheduled_id = $2
  AND language <> $1
`

type CascadeLanguageFromListScheduledParams struct {
	Language string     `json:"language"`
	ListID   *uuid.UUID `json:"list_id"`
}

// Đổi ngôn ngữ của kênh thì các Bài Post của kênh đó đi theo.
//
// Vì sao phải lan xuống: ngôn ngữ được chốt MỘT LẦN lúc bài được tạo, nên sửa
// ở kênh mà không lan thì mọi bài đã lấy về vẫn đọc bằng tiếng cũ — đúng thứ
// người dùng vừa sửa để tránh.
func (q *Queries) CascadeLanguageFromListScheduled(ctx context.Context, arg CascadeLanguageFromListScheduledParams) (int64, error) {
	result, err := q.db.Exec(ctx, cascadeLanguageFromListScheduled, arg.Language, arg.ListID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cascadeVoiceLanguageFromListScheduled = `-- name: CascadeVoiceLanguageFromListScheduled :execrows
UPDATE voice v SET language = $1
FROM source_post sp
WHERE sp.id = v.source_post_id
  AND sp.list_scheduled_id = $2
  AND v.voice_file_url IS NULL
  AND v.language <> $1
`

type CascadeVoiceLanguageFromListScheduledParams struct {
	Language string     `json:"language"`
	ListID   *uuid.UUID `json:"list_id"`
}

// Chỉ những Voice CHƯA có file: ngôn ngữ của voice đã ghi xong là mô tả của
// một file audio có thật, đổi nhãn không đổi được tiếng trong file. Voice đang
// chờ/đang lỗi thì chạy lại sẽ đọc bằng tiếng mới, nên sửa là đúng.
func (q *Queries) CascadeVoiceLanguageFromListScheduled(ctx context.Context, arg CascadeVoiceLanguageFromListScheduledParams) (int64, error) {
	result, err := q.db.Exec(ctx, cascadeVoiceLanguageFromListScheduled, arg.Language, arg.ListID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countListScheduleds = `-- name: CountListScheduleds :one
SELECT COUNT(*)
FROM list_scheduled ls
WHERE ($1::varchar   IS NULL OR ls.status     = $1)
  AND ($2::varchar IS NULL OR ls.platform   = $2)
  AND ($3::uuid  IS NULL OR ls.created_by = $3)
  AND ($4::text      IS NULL OR ls.source_url ~* $4)
`

type CountListScheduledsParams struct {
	Status    *string    `json:"status"`
	Platform  *string    `json:"platform"`
	CreatedBy *uuid.UUID `json:"created_by"`
	Search    *string    `json:"search"`
}

// Tổng số kênh khớp bộ lọc, để bảng phân trang biết có bao nhiêu trang.
func (q *Queries) CountListScheduleds(ctx context.Context, arg CountListScheduledsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListScheduleds,
		arg.Status,
		arg.Platform,
		arg.CreatedBy,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListScheduled = `-- name: CreateListScheduled :one
INSERT INTO list_scheduled (
  source_url, platform, content_type, collect_mode, prompt_id, scan_frequency,
  language_default, auto_process, auto_publish, status, scan_limit,
  max_posts_per_run, created_by, llm_api_set_id,
  timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min,
  backfill_limit, random_author,
  country_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
  $14, $15,
  $16, $17,
  $18, $19,
  $20, $21,
  $22
)
RETURNING id, source_url, platform, content_type, collect_mode, prompt_id, scan_frequency, language_default, last_synced_post_id, auto_process, auto_publish, status, created_by, created_at, scan_limit, max_posts_per_run, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min, backfill_limit, backfill_done_at, last_error, random_author, country_id
`

type CreateListScheduledParams struct {
	SourceUrl       string          `json:"source_url"`
	Platform        string          `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     string          `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	ScanFrequency   pgtype.Interval `json:"scan_frequency"`
	LanguageDefault string          `json:"language_default"`
	AutoProcess     bool            `json:"auto_process"`
	AutoPublish     bool            `json:"auto_publish"`
	Status          string          `json:"status"`
	ScanLimit       int32           `json:"scan_limit"`
	MaxPostsPerRun  *int32          `json:"max_posts_per_run"`
	CreatedBy       uuid.UUID       `json:"created_by"`
	LlmApiSetID     *uuid.UUID      `json:"llm_api_set_id"`
	Timezone        string          `json:"timezone"`
	ActiveFromMin   *int16          `json:"active_from_min"`
	ActiveToMin     *int16          `json:"active_to_min"`
	ActiveWeekdays  []int16         `json:"active_weekdays"`
	FixedTimesMin   []int16         `json:"fixed_times_min"`
	BackfillLimit   int32           `json:"backfill_limit"`
	RandomAuthor    bool            `json:"random_author"`
	CountryID       *int64          `json:"country_id"`
}

func (q *Queries) CreateListScheduled(ctx context.Context, arg CreateListScheduledParams) (ListScheduled, error) {
	row := q.db.QueryRow(ctx, createListScheduled,
		arg.SourceUrl,
		arg.Platform,
		arg.ContentType,
		arg.CollectMode,
		arg.PromptID,
		arg.ScanFrequency,
		arg.LanguageDefault,
		arg.AutoProcess,
		arg.AutoPublish,
		arg.Status,
		arg.ScanLimit,
		arg.MaxPostsPerRun,
		arg.CreatedBy,
		arg.LlmApiSetID,
		arg.Timezone,
		arg.ActiveFromMin,
		arg.ActiveToMin,
		arg.ActiveWeekdays,
		arg.FixedTimesMin,
		arg.BackfillLimit,
		arg.RandomAuthor,
		arg.CountryID,
	)
	var i ListScheduled
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.ScanFrequency,
		&i.LanguageDefault,
		&i.LastSyncedPostID,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ScanLimit,
		&i.MaxPostsPerRun,
		&i.LastScannedAt,
		&i.LlmApiSetID,
		&i.Timezone,
		&i.ActiveFromMin,
		&i.ActiveToMin,
		&i.ActiveWeekdays,
		&i.FixedTimesMin,
		&i.BackfillLimit,
		&i.BackfillDoneAt,
		&i.LastError,
		&i.RandomAuthor,
		&i.CountryID,
	)
	return i, err
}

const deleteListScheduled = `-- name: DeleteListScheduled :execrows
DELETE FROM list_scheduled WHERE id = $1
`

func (q *Queries) DeleteListScheduled(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteListScheduled, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getListScheduled = `-- name: GetListScheduled :one
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, scan_frequency, language_default, last_synced_post_id, auto_process, auto_publish, status, created_by, created_at, scan_limit, max_posts_per_run, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min, backfill_limit, backfill_done_at, last_error, random_author, country_id FROM list_scheduled WHERE id = $1
`

func (q *Queries) GetListScheduled(ctx context.Context, id uuid.UUID) (ListScheduled, error) {
	row := q.db.QueryRow(ctx, getListScheduled, id)
	var i ListScheduled
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.ScanFrequency,
		&i.LanguageDefault,
		&i.LastSyncedPostID,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ScanLimit,
		&i.MaxPostsPerRun,
		&i.LastScannedAt,
		&i.LlmApiSetID,
		&i.Timezone,
		&i.ActiveFromMin,
		&i.ActiveToMin,
		&i.ActiveWeekdays,
		&i.FixedTimesMin,
		&i.BackfillLimit,
		&i.BackfillDoneAt,
		&i.LastError,
		&i.RandomAuthor,
		&i.CountryID,
	)
	return i, err
}

const listActiveListScheduleds = `-- name: ListActiveListScheduleds :many
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, scan_frequency, language_default, last_synced_post_id, auto_process, auto_publish, status, created_by, created_at, scan_limit, max_posts_per_run, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min, backfill_limit, backfill_done_at, last_error, random_author, country_id FROM list_scheduled WHERE status = 'active' ORDER BY created_at
`

func (q *Queries) ListActiveListScheduleds(ctx context.Context) ([]ListScheduled, error) {
	rows, err := q.db.Query(ctx, listActiveListScheduleds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduled{}
	for rows.Next() {
		var i ListScheduled
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.ScanFrequency,
			&i.LanguageDefault,
			&i.LastSyncedPostID,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ScanLimit,
			&i.MaxPostsPerRun,
			&i.LastScannedAt,
			&i.LlmApiSetID,
			&i.Timezone,
			&i.ActiveFromMin,
			&i.ActiveToMin,
			&i.ActiveWeekdays,
			&i.FixedTimesMin,
			&i.BackfillLimit,
			&i.BackfillDoneAt,
			&i.LastError,
			&i.RandomAuthor,
			&i.CountryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListScheduleds = `-- name: ListListScheduleds :many
SELECT ls.id, ls.source_url, ls.platform, ls.content_type, ls.collect_mode, ls.prompt_id, ls.scan_frequency, ls.language_default, ls.last_synced_post_id, ls.auto_process, ls.auto_publish, ls.status, ls.created_by, ls.created_at, ls.scan_limit, ls.max_posts_per_run, ls.last_scanned_at, ls.llm_api_set_id, ls.timezone, ls.active_from_min, ls.active_to_min, ls.active_weekdays, ls.fixed_times_min, ls.backfill_limit, ls.backfill_done_at, ls.last_error, ls.random_author, ls.country_id, u.email AS created_by_email,
       (SELECT COUNT(*) FROM source_post sp
         WHERE sp.list_scheduled_id = ls.id) AS post_count,
       (SELECT COUNT(*) FROM voice v
          JOIN source_post sp2 ON sp2.id = v.source_post_id
         WHERE sp2.list_scheduled_id = ls.id) AS voice_count,
       -- Vòng quét GẦN NHẤT của kênh: 'running' = đang quét, 'success' =
       -- vừa quét xong, 'error' = vòng vừa rồi hỏng, '' = chưa quét lần nào.
       --
       -- Đọc từ scan_run chứ không thêm cột "đang quét" lên kênh: một cột như
       -- vậy phải được XOÁ bởi chính tiến trình vừa chết, nên nó sẽ kẹt ở
       -- "đang quét" đúng lúc người ta cần tin nó nhất. Ở đây dòng 'running'
       -- treo lại chỉ sống tới vòng quét kế tiếp, vì câu này luôn đọc dòng mới
       -- nhất.
       --
       -- COALESCE về chuỗi rỗng vì sqlc suy ra subquery vô hướng là NOT NULL:
       -- kênh chưa quét lần nào trả NULL, và quét NULL vào ` + "`" + `string` + "`" + ` là lỗi
       -- runtime ngay ở kênh vừa thêm (xem ghi chú tương tự ở source_post.sql).
       COALESCE((SELECT r.status FROM scan_run r
                  WHERE r.list_scheduled_id = ls.id
                  ORDER BY r.started_at DESC LIMIT 1), '')::text AS last_run_status
FROM list_scheduled ls
JOIN app_user u ON u.id = ls.created_by
WHERE ($1::varchar   IS NULL OR ls.status     = $1)
  AND ($2::varchar IS NULL OR ls.platform   = $2)
  AND ($3::uuid  IS NULL OR ls.created_by = $3)
  AND ($4::text      IS NULL OR ls.source_url ~* $4)
ORDER BY
  CASE WHEN $5::text = 'last_scanned_at' AND $6::text = 'asc'
       THEN ls.last_scanned_at END ASC NULLS LAST,
  CASE WHEN $5::text = 'last_scanned_at' AND $6::text = 'desc'
       THEN ls.last_scanned_at END DESC NULLS LAST,
  CASE WHEN $6::text = 'asc' AND $5::text <> 'last_scanned_at'
       THEN ls.created_at END ASC,
  ls.created_at DESC
LIMIT $8 OFFSET $7
`

type ListListScheduledsParams struct {
	Status    *string    `json:"status"`
	Platform  *string    `json:"platform"`
	CreatedBy *uuid.UUID `json:"created_by"`
	Search    *string    `json:"search"`
	Sort      string     `json:"sort"`
	Dir       string     `json:"dir"`
	Off       int32      `json:"off"`
	Lim       int32      `json:"lim"`
}

type ListListScheduledsRow struct {
	ID               uuid.UUID       `json:"id"`
	SourceUrl        string          `json:"source_url"`
	Platform         string          `json:"platform"`
	ContentType      *string         `json:"content_type"`
	CollectMode      string          `json:"collect_mode"`
	PromptID         *uuid.UUID      `json:"prompt_id"`
	ScanFrequency    pgtype.Interval `json:"scan_frequency"`
	LanguageDefault  string          `json:"language_default"`
	LastSyncedPostID *string         `json:"last_synced_post_id"`
	AutoProcess      bool            `json:"auto_process"`
	AutoPublish      bool            `json:"auto_publish"`
	Status           string          `json:"status"`
	CreatedBy        uuid.UUID       `json:"created_by"`
	CreatedAt        time.Time       `json:"created_at"`
	ScanLimit        int32           `json:"scan_limit"`
	MaxPostsPerRun   *int32          `json:"max_posts_per_run"`
	LastScannedAt    *time.Time      `json:"last_scanned_at"`
	LlmApiSetID      *uuid.UUID      `json:"llm_api_set_id"`
	Timezone         string          `json:"timezone"`
	ActiveFromMin    *int16          `json:"active_from_min"`
	ActiveToMin      *int16          `json:"active_to_min"`
	ActiveWeekdays   []int16         `json:"active_weekdays"`
	FixedTimesMin    []int16         `json:"fixed_times_min"`
	BackfillLimit    int32           `json:"backfill_limit"`
	BackfillDoneAt   *time.Time      `json:"backfill_done_at"`
	LastError        *string         `json:"last_error"`
	RandomAuthor     bool            `json:"random_author"`
	CountryID        *int64          `json:"country_id"`
	CreatedByEmail   string          `json:"created_by_email"`
	PostCount        int64           `json:"post_count"`
	VoiceCount       int64           `json:"voice_count"`
	LastRunStatus    string          `json:"last_run_status"`
}

// Kèm hai số đếm để bảng trả lời được "kênh này có ra gì không" mà không phải
// mở màn Bài Post lọc theo kênh.
//
// Subquery vô hướng chứ không JOIN + GROUP BY: một kênh không có bài nào vẫn
// phải hiện 0 chứ không biến mất, và GROUP BY trên `ls.*` thì phải liệt kê lại
// toàn bộ cột mỗi lần thêm cột mới vào bảng. Cả hai đều đi qua chỉ mục riêng
// trên list_scheduled_id (migration 000021).
// Sắp xếp động theo cột thời gian đang chọn; mặc định kênh mới nhất trước.
func (q *Queries) ListListScheduleds(ctx context.Context, arg ListListScheduledsParams) ([]ListListScheduledsRow, error) {
	rows, err := q.db.Query(ctx, listListScheduleds,
		arg.Status,
		arg.Platform,
		arg.CreatedBy,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListScheduledsRow{}
	for rows.Next() {
		var i ListListScheduledsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.ScanFrequency,
			&i.LanguageDefault,
			&i.LastSyncedPostID,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ScanLimit,
			&i.MaxPostsPerRun,
			&i.LastScannedAt,
			&i.LlmApiSetID,
			&i.Timezone,
			&i.ActiveFromMin,
			&i.ActiveToMin,
			&i.ActiveWeekdays,
			&i.FixedTimesMin,
			&i.BackfillLimit,
			&i.BackfillDoneAt,
			&i.LastError,
			&i.RandomAuthor,
			&i.CountryID,
			&i.CreatedByEmail,
			&i.PostCount,
			&i.VoiceCount,
			&i.LastRunStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markListScheduledBackfilled = `-- name: MarkListScheduledBackfilled :exec
UPDATE list_scheduled SET backfill_done_at = now() WHERE id = $1
`

// Đóng vòng quét đầu. Cột riêng chứ không suy ra từ last_synced_post_id: kênh
// chưa có bài nào thì mốc đó vẫn NULL sau một vòng quét hoàn toàn hợp lệ.
func (q *Queries) MarkListScheduledBackfilled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markListScheduledBackfilled, id)
	return err
}

const setLastSyncedPostID = `-- name: SetLastSyncedPostID :exec
UPDATE list_scheduled
SET last_synced_post_id = $2, last_scanned_at = now()
WHERE id = $1
`

type SetLastSyncedPostIDParams struct {
	ID               uuid.UUID `json:"id"`
	LastSyncedPostID *string   `json:"last_synced_post_id"`
}

func (q *Queries) SetLastSyncedPostID(ctx context.Context, arg SetLastSyncedPostIDParams) error {
	_, err := q.db.Exec(ctx, setLastSyncedPostID, arg.ID, arg.LastSyncedPostID)
	return err
}

const setListScheduledScanError = `-- name: SetListScheduledScanError :exec
UPDATE list_scheduled SET last_error = $1 WHERE id = $2
`

type SetListScheduledScanErrorParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

// Ghi lỗi của vòng quét gần nhất lên kênh, hoặc xoá nó khi vòng quét chạy sạch.
// Người dùng chỉ nhìn thấy bảng kênh, không nhìn thấy log worker.
func (q *Queries) SetListScheduledScanError(ctx context.Context, arg SetListScheduledScanErrorParams) error {
	_, err := q.db.Exec(ctx, setListScheduledScanError, arg.LastError, arg.ID)
	return err
}

const touchListScheduledDue = `-- name: TouchListScheduledDue :exec
UPDATE list_scheduled SET last_scanned_at = NULL WHERE id = $1
`

// Ép kênh tới hạn quét NGAY: xoá mốc quét gần nhất.
//
// Dùng khi người dùng vừa BẬT LẠI một kênh đang tắt. Kênh tắt thì scheduler bỏ
// qua mọi vòng, nên nếu không có câu này thì sau khi bật, kênh phải chờ hết một
// chu kỳ nữa mới chạy — với kênh đặt tần suất 6 tiếng thì đó là 6 tiếng im lặng
// ngay sau một thao tác mà người dùng nghĩ là "cho chạy lại".
func (q *Queries) TouchListScheduledDue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchListScheduledDue, id)
	return err
}

const touchListScheduledScanned = `-- name: TouchListScheduledScanned :exec
UPDATE list_scheduled SET last_scanned_at = now() WHERE id = $1
`

func (q *Queries) TouchListScheduledScanned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchListScheduledScanned, id)
	return err
}

const updateListScheduled = `-- name: UpdateListScheduled :one
UPDATE list_scheduled
SET source_url        = COALESCE($1, source_url),
    platform          = COALESCE($2, platform),
    content_type      = COALESCE($3, content_type),
    collect_mode      = COALESCE($4, collect_mode),
    prompt_id         = COALESCE($5, prompt_id),
    scan_frequency    = COALESCE($6, scan_frequency),
    language_default  = COALESCE($7, language_default),
    auto_process      = COALESCE($8, auto_process),
    auto_publish      = COALESCE($9, auto_publish),
    status            = COALESCE($10, status),
    scan_limit        = COALESCE($11, scan_limit),
    backfill_limit    = COALESCE($12, backfill_limit),
    -- Cùng lý do với khung giờ: NULL ở max_posts_per_run nghĩa là "không giới
    -- hạn", nên chỉ COALESCE thì người dùng đặt trần rồi không gỡ ra được nữa.
    max_posts_per_run = CASE WHEN $13::bool THEN NULL
                             ELSE COALESCE($14, max_posts_per_run) END,
    llm_api_set_id    = COALESCE($15, llm_api_set_id),
    timezone          = COALESCE($16, timezone),
    -- Khung giờ dùng cờ ` + "`" + `clear_*` + "`" + ` chứ không chỉ COALESCE: NULL ở đây vừa có
    -- nghĩa "không sửa" vừa có nghĩa "bỏ khung giờ, quay lại 24/7", và chỉ
    -- COALESCE thì người dùng không bao giờ xoá được khung giờ đã đặt.
    active_from_min   = CASE WHEN $17::bool THEN NULL
                             ELSE COALESCE($18, active_from_min) END,
    active_to_min     = CASE WHEN $17::bool THEN NULL
                             ELSE COALESCE($19, active_to_min) END,
    active_weekdays   = COALESCE($20, active_weekdays),
    fixed_times_min   = COALESCE($21, fixed_times_min),
    random_author     = COALESCE($22, random_author),
    -- country_id: cùng lý do — NULL ở đây nghĩa là "kênh không chốt quốc gia,
    -- suy từ ngôn ngữ như cũ", không phải "không sửa".
    country_id        = CASE WHEN $23::bool
                             THEN $24 ELSE country_id END
WHERE id = $25
RETURNING id, source_url, platform, content_type, collect_mode, prompt_id, scan_frequency, language_default, last_synced_post_id, auto_process, auto_publish, status, created_by, created_at, scan_limit, max_posts_per_run, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min, backfill_limit, backfill_done_at, last_error, random_author, country_id
`

type UpdateListScheduledParams struct {
	SourceUrl       *string         `json:"source_url"`
	Platform        *string         `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     *string         `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	ScanFrequency   pgtype.Interval `json:"scan_frequency"`
	LanguageDefault *string         `json:"language_default"`
	AutoProcess     *bool           `json:"auto_process"`
	AutoPublish     *bool           `json:"auto_publish"`
	Status          *string         `json:"status"`
	ScanLimit       *int32          `json:"scan_limit"`
	BackfillLimit   *int32          `json:"backfill_limit"`
	ClearMaxPosts   bool            `json:"clear_max_posts"`
	MaxPostsPerRun  *int32          `json:"max_posts_per_run"`
	LlmApiSetID     *uuid.UUID      `json:"llm_api_set_id"`
	Timezone        *string         `json:"timezone"`
	ClearWindow     bool            `json:"clear_window"`
	ActiveFromMin   *int16          `json:"active_from_min"`
	ActiveToMin     *int16          `json:"active_to_min"`
	ActiveWeekdays  []int16         `json:"active_weekdays"`
	FixedTimesMin   []int16         `json:"fixed_times_min"`
	RandomAuthor    *bool           `json:"random_author"`
	SetCountry      bool            `json:"set_country"`
	CountryID       *int64          `json:"country_id"`
	ID              uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateListScheduled(ctx context.Context, arg UpdateListScheduledParams) (ListScheduled, error) {
	row := q.db.QueryRow(ctx, updateListScheduled,
		arg.SourceUrl,
		arg.Platform,
		arg.ContentType,
		arg.CollectMode,
		arg.PromptID,
		arg.ScanFrequency,
		arg.LanguageDefault,
		arg.AutoProcess,
		arg.AutoPublish,
		arg.Status,
		arg.ScanLimit,
		arg.BackfillLimit,
		arg.ClearMaxPosts,
		arg.MaxPostsPerRun,
		arg.LlmApiSetID,
		arg.Timezone,
		arg.ClearWindow,
		arg.ActiveFromMin,
		arg.ActiveToMin,
		arg.ActiveWeekdays,
		arg.FixedTimesMin,
		arg.RandomAuthor,
		arg.SetCountry,
		arg.CountryID,
		arg.ID,
	)
	var i ListScheduled
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.ScanFrequency,
		&i.LanguageDefault,
		&i.LastSyncedPostID,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ScanLimit,
		&i.MaxPostsPerRun,
		&i.LastScannedAt,
		&i.LlmApiSetID,
		&i.Timezone,
		&i.ActiveFromMin,
		&i.ActiveToMin,
		&i.ActiveWeekdays,
		&i.FixedTimesMin,
		&i.BackfillLimit,
		&i.BackfillDoneAt,
		&i.LastError,
		&i.RandomAuthor,
		&i.CountryID,
	)
	return i, err
}
