// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_scheduled.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countListScheduleds = `-- name: CountListScheduleds :one
SELECT COUNT(*)
FROM list_scheduled ls
WHERE ($1::varchar   IS NULL OR ls.status     = $1)
  AND ($2::varchar IS NULL OR ls.platform   = $2)
  AND ($3::uuid  IS NULL OR ls.created_by = $3)
  AND ($4::text      IS NULL OR ls.source_url ~* $4)
`

type CountListScheduledsParams struct {
	Status    *string    `json:"status"`
	Platform  *string    `json:"platform"`
	CreatedBy *uuid.UUID `json:"created_by"`
	Search    *string    `json:"search"`
}

// Tổng số kênh khớp bộ lọc, để bảng phân trang biết có bao nhiêu trang.
func (q *Queries) CountListScheduleds(ctx context.Context, arg CountListScheduledsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListScheduleds,
		arg.Status,
		arg.Platform,
		arg.CreatedBy,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListScheduled = `-- name: CreateListScheduled :one
INSERT INTO list_scheduled (
  source_url, platform, content_type, collect_mode, prompt_id, scan_frequency,
  language_default, auto_process, auto_publish, status, scan_limit,
  max_posts_per_run, created_by, llm_api_set_id,
  timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
  $14, $15,
  $16, $17,
  $18, $19
)
RETURNING id, source_url, platform, content_type, collect_mode, prompt_id, scan_frequency, language_default, last_synced_post_id, auto_process, auto_publish, status, created_by, created_at, scan_limit, max_posts_per_run, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min
`

type CreateListScheduledParams struct {
	SourceUrl       string          `json:"source_url"`
	Platform        string          `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     string          `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	ScanFrequency   pgtype.Interval `json:"scan_frequency"`
	LanguageDefault string          `json:"language_default"`
	AutoProcess     bool            `json:"auto_process"`
	AutoPublish     bool            `json:"auto_publish"`
	Status          string          `json:"status"`
	ScanLimit       int32           `json:"scan_limit"`
	MaxPostsPerRun  *int32          `json:"max_posts_per_run"`
	CreatedBy       uuid.UUID       `json:"created_by"`
	LlmApiSetID     *uuid.UUID      `json:"llm_api_set_id"`
	Timezone        string          `json:"timezone"`
	ActiveFromMin   *int16          `json:"active_from_min"`
	ActiveToMin     *int16          `json:"active_to_min"`
	ActiveWeekdays  []int16         `json:"active_weekdays"`
	FixedTimesMin   []int16         `json:"fixed_times_min"`
}

func (q *Queries) CreateListScheduled(ctx context.Context, arg CreateListScheduledParams) (ListScheduled, error) {
	row := q.db.QueryRow(ctx, createListScheduled,
		arg.SourceUrl,
		arg.Platform,
		arg.ContentType,
		arg.CollectMode,
		arg.PromptID,
		arg.ScanFrequency,
		arg.LanguageDefault,
		arg.AutoProcess,
		arg.AutoPublish,
		arg.Status,
		arg.ScanLimit,
		arg.MaxPostsPerRun,
		arg.CreatedBy,
		arg.LlmApiSetID,
		arg.Timezone,
		arg.ActiveFromMin,
		arg.ActiveToMin,
		arg.ActiveWeekdays,
		arg.FixedTimesMin,
	)
	var i ListScheduled
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.ScanFrequency,
		&i.LanguageDefault,
		&i.LastSyncedPostID,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ScanLimit,
		&i.MaxPostsPerRun,
		&i.LastScannedAt,
		&i.LlmApiSetID,
		&i.Timezone,
		&i.ActiveFromMin,
		&i.ActiveToMin,
		&i.ActiveWeekdays,
		&i.FixedTimesMin,
	)
	return i, err
}

const deleteListScheduled = `-- name: DeleteListScheduled :execrows
DELETE FROM list_scheduled WHERE id = $1
`

func (q *Queries) DeleteListScheduled(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteListScheduled, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getListScheduled = `-- name: GetListScheduled :one
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, scan_frequency, language_default, last_synced_post_id, auto_process, auto_publish, status, created_by, created_at, scan_limit, max_posts_per_run, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min FROM list_scheduled WHERE id = $1
`

func (q *Queries) GetListScheduled(ctx context.Context, id uuid.UUID) (ListScheduled, error) {
	row := q.db.QueryRow(ctx, getListScheduled, id)
	var i ListScheduled
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.ScanFrequency,
		&i.LanguageDefault,
		&i.LastSyncedPostID,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ScanLimit,
		&i.MaxPostsPerRun,
		&i.LastScannedAt,
		&i.LlmApiSetID,
		&i.Timezone,
		&i.ActiveFromMin,
		&i.ActiveToMin,
		&i.ActiveWeekdays,
		&i.FixedTimesMin,
	)
	return i, err
}

const listActiveListScheduleds = `-- name: ListActiveListScheduleds :many
SELECT id, source_url, platform, content_type, collect_mode, prompt_id, scan_frequency, language_default, last_synced_post_id, auto_process, auto_publish, status, created_by, created_at, scan_limit, max_posts_per_run, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min FROM list_scheduled WHERE status = 'active' ORDER BY created_at
`

func (q *Queries) ListActiveListScheduleds(ctx context.Context) ([]ListScheduled, error) {
	rows, err := q.db.Query(ctx, listActiveListScheduleds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduled{}
	for rows.Next() {
		var i ListScheduled
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.ScanFrequency,
			&i.LanguageDefault,
			&i.LastSyncedPostID,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ScanLimit,
			&i.MaxPostsPerRun,
			&i.LastScannedAt,
			&i.LlmApiSetID,
			&i.Timezone,
			&i.ActiveFromMin,
			&i.ActiveToMin,
			&i.ActiveWeekdays,
			&i.FixedTimesMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListScheduleds = `-- name: ListListScheduleds :many
SELECT ls.id, ls.source_url, ls.platform, ls.content_type, ls.collect_mode, ls.prompt_id, ls.scan_frequency, ls.language_default, ls.last_synced_post_id, ls.auto_process, ls.auto_publish, ls.status, ls.created_by, ls.created_at, ls.scan_limit, ls.max_posts_per_run, ls.last_scanned_at, ls.llm_api_set_id, ls.timezone, ls.active_from_min, ls.active_to_min, ls.active_weekdays, ls.fixed_times_min, u.email AS created_by_email
FROM list_scheduled ls
JOIN app_user u ON u.id = ls.created_by
WHERE ($1::varchar   IS NULL OR ls.status     = $1)
  AND ($2::varchar IS NULL OR ls.platform   = $2)
  AND ($3::uuid  IS NULL OR ls.created_by = $3)
  AND ($4::text      IS NULL OR ls.source_url ~* $4)
ORDER BY
  CASE WHEN $5::text = 'last_scanned_at' AND $6::text = 'asc'
       THEN ls.last_scanned_at END ASC NULLS LAST,
  CASE WHEN $5::text = 'last_scanned_at' AND $6::text = 'desc'
       THEN ls.last_scanned_at END DESC NULLS LAST,
  CASE WHEN $6::text = 'asc' AND $5::text <> 'last_scanned_at'
       THEN ls.created_at END ASC,
  ls.created_at DESC
LIMIT $8 OFFSET $7
`

type ListListScheduledsParams struct {
	Status    *string    `json:"status"`
	Platform  *string    `json:"platform"`
	CreatedBy *uuid.UUID `json:"created_by"`
	Search    *string    `json:"search"`
	Sort      string     `json:"sort"`
	Dir       string     `json:"dir"`
	Off       int32      `json:"off"`
	Lim       int32      `json:"lim"`
}

type ListListScheduledsRow struct {
	ID               uuid.UUID       `json:"id"`
	SourceUrl        string          `json:"source_url"`
	Platform         string          `json:"platform"`
	ContentType      *string         `json:"content_type"`
	CollectMode      string          `json:"collect_mode"`
	PromptID         *uuid.UUID      `json:"prompt_id"`
	ScanFrequency    pgtype.Interval `json:"scan_frequency"`
	LanguageDefault  string          `json:"language_default"`
	LastSyncedPostID *string         `json:"last_synced_post_id"`
	AutoProcess      bool            `json:"auto_process"`
	AutoPublish      bool            `json:"auto_publish"`
	Status           string          `json:"status"`
	CreatedBy        uuid.UUID       `json:"created_by"`
	CreatedAt        time.Time       `json:"created_at"`
	ScanLimit        int32           `json:"scan_limit"`
	MaxPostsPerRun   *int32          `json:"max_posts_per_run"`
	LastScannedAt    *time.Time      `json:"last_scanned_at"`
	LlmApiSetID      *uuid.UUID      `json:"llm_api_set_id"`
	Timezone         string          `json:"timezone"`
	ActiveFromMin    *int16          `json:"active_from_min"`
	ActiveToMin      *int16          `json:"active_to_min"`
	ActiveWeekdays   []int16         `json:"active_weekdays"`
	FixedTimesMin    []int16         `json:"fixed_times_min"`
	CreatedByEmail   string          `json:"created_by_email"`
}

// Sắp xếp động theo cột thời gian đang chọn; mặc định kênh mới nhất trước.
func (q *Queries) ListListScheduleds(ctx context.Context, arg ListListScheduledsParams) ([]ListListScheduledsRow, error) {
	rows, err := q.db.Query(ctx, listListScheduleds,
		arg.Status,
		arg.Platform,
		arg.CreatedBy,
		arg.Search,
		arg.Sort,
		arg.Dir,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListScheduledsRow{}
	for rows.Next() {
		var i ListListScheduledsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.CollectMode,
			&i.PromptID,
			&i.ScanFrequency,
			&i.LanguageDefault,
			&i.LastSyncedPostID,
			&i.AutoProcess,
			&i.AutoPublish,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ScanLimit,
			&i.MaxPostsPerRun,
			&i.LastScannedAt,
			&i.LlmApiSetID,
			&i.Timezone,
			&i.ActiveFromMin,
			&i.ActiveToMin,
			&i.ActiveWeekdays,
			&i.FixedTimesMin,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLastSyncedPostID = `-- name: SetLastSyncedPostID :exec
UPDATE list_scheduled
SET last_synced_post_id = $2, last_scanned_at = now()
WHERE id = $1
`

type SetLastSyncedPostIDParams struct {
	ID               uuid.UUID `json:"id"`
	LastSyncedPostID *string   `json:"last_synced_post_id"`
}

func (q *Queries) SetLastSyncedPostID(ctx context.Context, arg SetLastSyncedPostIDParams) error {
	_, err := q.db.Exec(ctx, setLastSyncedPostID, arg.ID, arg.LastSyncedPostID)
	return err
}

const touchListScheduledScanned = `-- name: TouchListScheduledScanned :exec
UPDATE list_scheduled SET last_scanned_at = now() WHERE id = $1
`

func (q *Queries) TouchListScheduledScanned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchListScheduledScanned, id)
	return err
}

const updateListScheduled = `-- name: UpdateListScheduled :one
UPDATE list_scheduled
SET source_url        = COALESCE($1, source_url),
    platform          = COALESCE($2, platform),
    content_type      = COALESCE($3, content_type),
    collect_mode      = COALESCE($4, collect_mode),
    prompt_id         = COALESCE($5, prompt_id),
    scan_frequency    = COALESCE($6, scan_frequency),
    language_default  = COALESCE($7, language_default),
    auto_process      = COALESCE($8, auto_process),
    auto_publish      = COALESCE($9, auto_publish),
    status            = COALESCE($10, status),
    scan_limit        = COALESCE($11, scan_limit),
    max_posts_per_run = COALESCE($12, max_posts_per_run),
    llm_api_set_id    = COALESCE($13, llm_api_set_id),
    timezone          = COALESCE($14, timezone),
    -- Khung giờ dùng cờ ` + "`" + `clear_*` + "`" + ` chứ không chỉ COALESCE: NULL ở đây vừa có
    -- nghĩa "không sửa" vừa có nghĩa "bỏ khung giờ, quay lại 24/7", và chỉ
    -- COALESCE thì người dùng không bao giờ xoá được khung giờ đã đặt.
    active_from_min   = CASE WHEN $15::bool THEN NULL
                             ELSE COALESCE($16, active_from_min) END,
    active_to_min     = CASE WHEN $15::bool THEN NULL
                             ELSE COALESCE($17, active_to_min) END,
    active_weekdays   = COALESCE($18, active_weekdays),
    fixed_times_min   = COALESCE($19, fixed_times_min)
WHERE id = $20
RETURNING id, source_url, platform, content_type, collect_mode, prompt_id, scan_frequency, language_default, last_synced_post_id, auto_process, auto_publish, status, created_by, created_at, scan_limit, max_posts_per_run, last_scanned_at, llm_api_set_id, timezone, active_from_min, active_to_min, active_weekdays, fixed_times_min
`

type UpdateListScheduledParams struct {
	SourceUrl       *string         `json:"source_url"`
	Platform        *string         `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     *string         `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	ScanFrequency   pgtype.Interval `json:"scan_frequency"`
	LanguageDefault *string         `json:"language_default"`
	AutoProcess     *bool           `json:"auto_process"`
	AutoPublish     *bool           `json:"auto_publish"`
	Status          *string         `json:"status"`
	ScanLimit       *int32          `json:"scan_limit"`
	MaxPostsPerRun  *int32          `json:"max_posts_per_run"`
	LlmApiSetID     *uuid.UUID      `json:"llm_api_set_id"`
	Timezone        *string         `json:"timezone"`
	ClearWindow     bool            `json:"clear_window"`
	ActiveFromMin   *int16          `json:"active_from_min"`
	ActiveToMin     *int16          `json:"active_to_min"`
	ActiveWeekdays  []int16         `json:"active_weekdays"`
	FixedTimesMin   []int16         `json:"fixed_times_min"`
	ID              uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateListScheduled(ctx context.Context, arg UpdateListScheduledParams) (ListScheduled, error) {
	row := q.db.QueryRow(ctx, updateListScheduled,
		arg.SourceUrl,
		arg.Platform,
		arg.ContentType,
		arg.CollectMode,
		arg.PromptID,
		arg.ScanFrequency,
		arg.LanguageDefault,
		arg.AutoProcess,
		arg.AutoPublish,
		arg.Status,
		arg.ScanLimit,
		arg.MaxPostsPerRun,
		arg.LlmApiSetID,
		arg.Timezone,
		arg.ClearWindow,
		arg.ActiveFromMin,
		arg.ActiveToMin,
		arg.ActiveWeekdays,
		arg.FixedTimesMin,
		arg.ID,
	)
	var i ListScheduled
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.CollectMode,
		&i.PromptID,
		&i.ScanFrequency,
		&i.LanguageDefault,
		&i.LastSyncedPostID,
		&i.AutoProcess,
		&i.AutoPublish,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ScanLimit,
		&i.MaxPostsPerRun,
		&i.LastScannedAt,
		&i.LlmApiSetID,
		&i.Timezone,
		&i.ActiveFromMin,
		&i.ActiveToMin,
		&i.ActiveWeekdays,
		&i.FixedTimesMin,
	)
	return i, err
}
