// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_api_set.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addLLMAPISetUser = `-- name: AddLLMAPISetUser :exec
INSERT INTO llm_api_set_user (set_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddLLMAPISetUserParams struct {
	SetID  uuid.UUID `json:"set_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddLLMAPISetUser(ctx context.Context, arg AddLLMAPISetUserParams) error {
	_, err := q.db.Exec(ctx, addLLMAPISetUser, arg.SetID, arg.UserID)
	return err
}

const canUseLLMAPISet = `-- name: CanUseLLMAPISet :one
SELECT s.id, s.name, s.note, s.visible_to_users, s.created_by, s.created_at, s.last_used_at FROM llm_api_set s
WHERE s.id = $1
  AND (s.visible_to_users
       OR s.created_by = $2
       OR EXISTS (
            SELECT 1 FROM llm_api_set_user su
            WHERE su.set_id = s.id AND su.user_id = $2
          ))
`

type CanUseLLMAPISetParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Câu hỏi của WORKER, không phải của UI: bộ này có thật sự dùng được cho người
// tạo voice không. Trả về bộ nếu được, không có dòng nào nếu không.
func (q *Queries) CanUseLLMAPISet(ctx context.Context, arg CanUseLLMAPISetParams) (LlmApiSet, error) {
	row := q.db.QueryRow(ctx, canUseLLMAPISet, arg.ID, arg.UserID)
	var i LlmApiSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Note,
		&i.VisibleToUsers,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const clearLLMAPISetUsers = `-- name: ClearLLMAPISetUsers :exec
DELETE FROM llm_api_set_user WHERE set_id = $1
`

func (q *Queries) ClearLLMAPISetUsers(ctx context.Context, setID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearLLMAPISetUsers, setID)
	return err
}

const countLLMAPIKeys = `-- name: CountLLMAPIKeys :one
SELECT COUNT(*)::bigint FROM llm_api_key
`

// Câu hỏi lúc KHỞI ĐỘNG: hệ thống có đường nào chạy được mode C không.
// Mode C cần LLM thật; trước đây điều đó chỉ đọc từ .env, nhưng giờ đường chính
// là Bộ API key trong DB — chỉ nhìn .env thì tắt nhầm mode C của cả hệ thống.
func (q *Queries) CountLLMAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLLMAPIKeys)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countLLMAPIKeysBySet = `-- name: CountLLMAPIKeysBySet :many
SELECT set_id, provider, COUNT(*)::bigint AS total
FROM llm_api_key
WHERE set_id = ANY($1::uuid[])
GROUP BY set_id, provider
`

type CountLLMAPIKeysBySetRow struct {
	SetID    uuid.UUID `json:"set_id"`
	Provider string    `json:"provider"`
	Total    int64     `json:"total"`
}

// Bảng danh sách bộ hiện "số key theo từng nhà" mà không phải tải hết key về.
func (q *Queries) CountLLMAPIKeysBySet(ctx context.Context, setIds []uuid.UUID) ([]CountLLMAPIKeysBySetRow, error) {
	rows, err := q.db.Query(ctx, countLLMAPIKeysBySet, setIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLLMAPIKeysBySetRow{}
	for rows.Next() {
		var i CountLLMAPIKeysBySetRow
		if err := rows.Scan(&i.SetID, &i.Provider, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createLLMAPIKey = `-- name: CreateLLMAPIKey :one

INSERT INTO llm_api_key (set_id, provider, api_key_encrypted, label, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, set_id, provider, api_key_encrypted, label, priority, disabled_at, cooldown_until, consecutive_failures, last_used_at, last_error, created_at
`

type CreateLLMAPIKeyParams struct {
	SetID           uuid.UUID `json:"set_id"`
	Provider        string    `json:"provider"`
	ApiKeyEncrypted string    `json:"api_key_encrypted"`
	Label           *string   `json:"label"`
	Priority        int32     `json:"priority"`
}

// ---------------------------------------------------------------------------
// Key trong bộ
// ---------------------------------------------------------------------------
func (q *Queries) CreateLLMAPIKey(ctx context.Context, arg CreateLLMAPIKeyParams) (LlmApiKey, error) {
	row := q.db.QueryRow(ctx, createLLMAPIKey,
		arg.SetID,
		arg.Provider,
		arg.ApiKeyEncrypted,
		arg.Label,
		arg.Priority,
	)
	var i LlmApiKey
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Provider,
		&i.ApiKeyEncrypted,
		&i.Label,
		&i.Priority,
		&i.DisabledAt,
		&i.CooldownUntil,
		&i.ConsecutiveFailures,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const createLLMAPISet = `-- name: CreateLLMAPISet :one
INSERT INTO llm_api_set (name, note, visible_to_users, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, note, visible_to_users, created_by, created_at, last_used_at
`

type CreateLLMAPISetParams struct {
	Name           string    `json:"name"`
	Note           *string   `json:"note"`
	VisibleToUsers bool      `json:"visible_to_users"`
	CreatedBy      uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateLLMAPISet(ctx context.Context, arg CreateLLMAPISetParams) (LlmApiSet, error) {
	row := q.db.QueryRow(ctx, createLLMAPISet,
		arg.Name,
		arg.Note,
		arg.VisibleToUsers,
		arg.CreatedBy,
	)
	var i LlmApiSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Note,
		&i.VisibleToUsers,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteLLMAPIKey = `-- name: DeleteLLMAPIKey :execrows
DELETE FROM llm_api_key WHERE id = $1
`

func (q *Queries) DeleteLLMAPIKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLLMAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLLMAPISet = `-- name: DeleteLLMAPISet :execrows
DELETE FROM llm_api_set WHERE id = $1
`

func (q *Queries) DeleteLLMAPISet(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLLMAPISet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLLMAPIKey = `-- name: GetLLMAPIKey :one
SELECT id, set_id, provider, api_key_encrypted, label, priority, disabled_at, cooldown_until, consecutive_failures, last_used_at, last_error, created_at FROM llm_api_key WHERE id = $1
`

func (q *Queries) GetLLMAPIKey(ctx context.Context, id uuid.UUID) (LlmApiKey, error) {
	row := q.db.QueryRow(ctx, getLLMAPIKey, id)
	var i LlmApiKey
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Provider,
		&i.ApiKeyEncrypted,
		&i.Label,
		&i.Priority,
		&i.DisabledAt,
		&i.CooldownUntil,
		&i.ConsecutiveFailures,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getLLMAPISet = `-- name: GetLLMAPISet :one
SELECT s.id, s.name, s.note, s.visible_to_users, s.created_by, s.created_at, s.last_used_at, u.email AS created_by_email
FROM llm_api_set s
JOIN app_user u ON u.id = s.created_by
WHERE s.id = $1
`

type GetLLMAPISetRow struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Note           *string    `json:"note"`
	VisibleToUsers bool       `json:"visible_to_users"`
	CreatedBy      uuid.UUID  `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	LastUsedAt     *time.Time `json:"last_used_at"`
	CreatedByEmail string     `json:"created_by_email"`
}

func (q *Queries) GetLLMAPISet(ctx context.Context, id uuid.UUID) (GetLLMAPISetRow, error) {
	row := q.db.QueryRow(ctx, getLLMAPISet, id)
	var i GetLLMAPISetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Note,
		&i.VisibleToUsers,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.CreatedByEmail,
	)
	return i, err
}

const listLLMAPIKeys = `-- name: ListLLMAPIKeys :many
SELECT id, set_id, provider, api_key_encrypted, label, priority, disabled_at, cooldown_until, consecutive_failures, last_used_at, last_error, created_at FROM llm_api_key
WHERE set_id = $1
ORDER BY provider, priority, id
`

// Thứ tự ở đây chính là thứ tự router thử key trong cùng 1 nhà: priority nhỏ
// trước, hoà thì theo id cho TẤT ĐỊNH — router không được xoay ngẫu nhiên.
func (q *Queries) ListLLMAPIKeys(ctx context.Context, setID uuid.UUID) ([]LlmApiKey, error) {
	rows, err := q.db.Query(ctx, listLLMAPIKeys, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmApiKey{}
	for rows.Next() {
		var i LlmApiKey
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.Provider,
			&i.ApiKeyEncrypted,
			&i.Label,
			&i.Priority,
			&i.DisabledAt,
			&i.CooldownUntil,
			&i.ConsecutiveFailures,
			&i.LastUsedAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMAPISetUsers = `-- name: ListLLMAPISetUsers :many

SELECT su.set_id, su.user_id, u.email
FROM llm_api_set_user su
JOIN app_user u ON u.id = su.user_id
WHERE su.set_id = ANY($1::uuid[])
ORDER BY u.email
`

type ListLLMAPISetUsersRow struct {
	SetID  uuid.UUID `json:"set_id"`
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
}

// ---------------------------------------------------------------------------
// Chia sẻ bộ cho người dùng
// ---------------------------------------------------------------------------
func (q *Queries) ListLLMAPISetUsers(ctx context.Context, setIds []uuid.UUID) ([]ListLLMAPISetUsersRow, error) {
	rows, err := q.db.Query(ctx, listLLMAPISetUsers, setIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLLMAPISetUsersRow{}
	for rows.Next() {
		var i ListLLMAPISetUsersRow
		if err := rows.Scan(&i.SetID, &i.UserID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMAPISets = `-- name: ListLLMAPISets :many
SELECT s.id, s.name, s.note, s.visible_to_users, s.created_by, s.created_at, s.last_used_at, u.email AS created_by_email
FROM llm_api_set s
JOIN app_user u ON u.id = s.created_by
WHERE $1::uuid IS NULL
   OR s.visible_to_users
   OR s.created_by = $1
   OR EXISTS (
        SELECT 1 FROM llm_api_set_user su
        WHERE su.set_id = s.id AND su.user_id = $1
      )
ORDER BY s.name
`

type ListLLMAPISetsRow struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Note           *string    `json:"note"`
	VisibleToUsers bool       `json:"visible_to_users"`
	CreatedBy      uuid.UUID  `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	LastUsedAt     *time.Time `json:"last_used_at"`
	CreatedByEmail string     `json:"created_by_email"`
}

// `viewer` NULL = xem tất cả (admin). Người dùng thường được service truyền
// chính id của họ vào, và chỉ thấy bộ mình tạo / được chia sẻ / admin đã bật
// hiển thị — chặn ở SQL chứ không chỉ ẩn trên UI.
func (q *Queries) ListLLMAPISets(ctx context.Context, viewer *uuid.UUID) ([]ListLLMAPISetsRow, error) {
	rows, err := q.db.Query(ctx, listLLMAPISets, viewer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLLMAPISetsRow{}
	for rows.Next() {
		var i ListLLMAPISetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Note,
			&i.VisibleToUsers,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLLMAPIKeyCooldown = `-- name: MarkLLMAPIKeyCooldown :exec
UPDATE llm_api_key
SET cooldown_until       = $1,
    consecutive_failures = consecutive_failures + 1,
    last_error           = $2
WHERE id = $3
`

type MarkLLMAPIKeyCooldownParams struct {
	CooldownUntil *time.Time `json:"cooldown_until"`
	LastError     *string    `json:"last_error"`
	ID            uuid.UUID  `json:"id"`
}

// Hết quota / bị rate-limit: key vẫn đúng, chỉ cần CHỜ. Không đụng disabled_at.
func (q *Queries) MarkLLMAPIKeyCooldown(ctx context.Context, arg MarkLLMAPIKeyCooldownParams) error {
	_, err := q.db.Exec(ctx, markLLMAPIKeyCooldown, arg.CooldownUntil, arg.LastError, arg.ID)
	return err
}

const markLLMAPIKeyDisabled = `-- name: MarkLLMAPIKeyDisabled :exec
UPDATE llm_api_key
SET disabled_at          = now(),
    consecutive_failures = consecutive_failures + 1,
    last_error           = $1
WHERE id = $2
`

type MarkLLMAPIKeyDisabledParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

// Key sai / bị thu hồi: chờ bao lâu cũng không tự khỏi, phải có người dán key
// mới. Tách khỏi cooldown vì hai tình huống này xử lý khác hẳn nhau.
func (q *Queries) MarkLLMAPIKeyDisabled(ctx context.Context, arg MarkLLMAPIKeyDisabledParams) error {
	_, err := q.db.Exec(ctx, markLLMAPIKeyDisabled, arg.LastError, arg.ID)
	return err
}

const markLLMAPIKeyFailure = `-- name: MarkLLMAPIKeyFailure :exec
UPDATE llm_api_key
SET consecutive_failures = consecutive_failures + 1,
    last_error           = $1
WHERE id = $2
`

type MarkLLMAPIKeyFailureParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

// Lỗi tạm thời (5xx, mạng): chỉ đếm và ghi lý do, không tắt cũng không bắt nghỉ.
func (q *Queries) MarkLLMAPIKeyFailure(ctx context.Context, arg MarkLLMAPIKeyFailureParams) error {
	_, err := q.db.Exec(ctx, markLLMAPIKeyFailure, arg.LastError, arg.ID)
	return err
}

const markLLMAPIKeyOK = `-- name: MarkLLMAPIKeyOK :exec
UPDATE llm_api_key
SET last_used_at         = now(),
    consecutive_failures = 0,
    last_error           = NULL,
    cooldown_until       = NULL
WHERE id = $1
`

// Gọi sau mỗi lần gọi LLM THÀNH CÔNG: xoá sạch dấu vết hỏng hóc cũ. Không reset
// consecutive_failures ở đây thì một key thỉnh thoảng lỗi sẽ tích dần số đếm
// qua nhiều ngày rồi bị tắt oan.
func (q *Queries) MarkLLMAPIKeyOK(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markLLMAPIKeyOK, id)
	return err
}

const touchLLMAPISetUsed = `-- name: TouchLLMAPISetUsed :exec
UPDATE llm_api_set SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchLLMAPISetUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchLLMAPISetUsed, id)
	return err
}

const updateLLMAPIKey = `-- name: UpdateLLMAPIKey :one
UPDATE llm_api_key
SET provider          = COALESCE($1, provider),
    api_key_encrypted = COALESCE($2, api_key_encrypted),
    label             = COALESCE($3, label),
    priority          = COALESCE($4, priority),
    disabled_at          = CASE WHEN $2 IS NULL THEN disabled_at          ELSE NULL END,
    cooldown_until       = CASE WHEN $2 IS NULL THEN cooldown_until       ELSE NULL END,
    consecutive_failures = CASE WHEN $2 IS NULL THEN consecutive_failures ELSE 0    END,
    last_error           = CASE WHEN $2 IS NULL THEN last_error           ELSE NULL END
WHERE id = $5
RETURNING id, set_id, provider, api_key_encrypted, label, priority, disabled_at, cooldown_until, consecutive_failures, last_used_at, last_error, created_at
`

type UpdateLLMAPIKeyParams struct {
	Provider        *string   `json:"provider"`
	ApiKeyEncrypted *string   `json:"api_key_encrypted"`
	Label           *string   `json:"label"`
	Priority        *int32    `json:"priority"`
	ID              uuid.UUID `json:"id"`
}

// api_key_encrypted dùng COALESCE: bỏ trống ô API key ở form nghĩa là "giữ key
// cũ" — key thật không bao giờ gửi về trình duyệt nên không có gì để gửi lại.
//
// Sửa key cũng là RESET SỨC KHOẺ: người dùng vào đây vì key hỏng, dán key mới
// mà vẫn còn disabled_at thì router tiếp tục bỏ qua nó và họ không hiểu vì sao.
func (q *Queries) UpdateLLMAPIKey(ctx context.Context, arg UpdateLLMAPIKeyParams) (LlmApiKey, error) {
	row := q.db.QueryRow(ctx, updateLLMAPIKey,
		arg.Provider,
		arg.ApiKeyEncrypted,
		arg.Label,
		arg.Priority,
		arg.ID,
	)
	var i LlmApiKey
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Provider,
		&i.ApiKeyEncrypted,
		&i.Label,
		&i.Priority,
		&i.DisabledAt,
		&i.CooldownUntil,
		&i.ConsecutiveFailures,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const updateLLMAPISet = `-- name: UpdateLLMAPISet :one
UPDATE llm_api_set
SET name             = COALESCE($1, name),
    note             = COALESCE($2, note),
    visible_to_users = COALESCE($3, visible_to_users)
WHERE id = $4
RETURNING id, name, note, visible_to_users, created_by, created_at, last_used_at
`

type UpdateLLMAPISetParams struct {
	Name           *string   `json:"name"`
	Note           *string   `json:"note"`
	VisibleToUsers *bool     `json:"visible_to_users"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateLLMAPISet(ctx context.Context, arg UpdateLLMAPISetParams) (LlmApiSet, error) {
	row := q.db.QueryRow(ctx, updateLLMAPISet,
		arg.Name,
		arg.Note,
		arg.VisibleToUsers,
		arg.ID,
	)
	var i LlmApiSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Note,
		&i.VisibleToUsers,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
