// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiEngine struct {
	ID              uuid.UUID  `json:"id"`
	Provider        string     `json:"provider"`
	CreatedAt       time.Time  `json:"created_at"`
	ApiKeyEncrypted string     `json:"api_key_encrypted"`
	VoiceID         *string    `json:"voice_id"`
	CreatedBy       uuid.UUID  `json:"created_by"`
	UserID          uuid.UUID  `json:"user_id"`
	LastUsedAt      *time.Time `json:"last_used_at"`
}

type AppUser struct {
	ID                  uuid.UUID  `json:"id"`
	Email               string     `json:"email"`
	PasswordHash        *string    `json:"password_hash"`
	FullName            *string    `json:"full_name"`
	IsActive            bool       `json:"is_active"`
	CreatedAt           time.Time  `json:"created_at"`
	Role                string     `json:"role"`
	StrongbodyUserID    *int64     `json:"strongbody_user_id"`
	AvatarUrl           *string    `json:"avatar_url"`
	MultimeAccessToken  *string    `json:"multime_access_token"`
	MultimeRefreshToken *string    `json:"multime_refresh_token"`
	MultimeTokenAt      *time.Time `json:"multime_token_at"`
	LastLoginAt         *time.Time `json:"last_login_at"`
}

type AuditLog struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Action     string    `json:"action"`
	ObjectType string    `json:"object_type"`
	ObjectID   uuid.UUID `json:"object_id"`
	Changes    []byte    `json:"changes"`
	CreatedAt  time.Time `json:"created_at"`
}

type ListBreaking struct {
	ID              uuid.UUID       `json:"id"`
	SourceUrl       string          `json:"source_url"`
	Platform        string          `json:"platform"`
	ContentType     *string         `json:"content_type"`
	CollectMode     string          `json:"collect_mode"`
	PromptID        *uuid.UUID      `json:"prompt_id"`
	LanguageDefault string          `json:"language_default"`
	AutoProcess     bool            `json:"auto_process"`
	AutoPublish     bool            `json:"auto_publish"`
	Status          string          `json:"status"`
	CreatedBy       uuid.UUID       `json:"created_by"`
	CreatedAt       time.Time       `json:"created_at"`
	RegexPatterns   []string        `json:"regex_patterns"`
	ScanLimit       int32           `json:"scan_limit"`
	ScanInterval    pgtype.Interval `json:"scan_interval"`
	LastScannedAt   *time.Time      `json:"last_scanned_at"`
}

type ListScheduled struct {
	ID               uuid.UUID       `json:"id"`
	SourceUrl        string          `json:"source_url"`
	Platform         string          `json:"platform"`
	ContentType      *string         `json:"content_type"`
	CollectMode      string          `json:"collect_mode"`
	PromptID         *uuid.UUID      `json:"prompt_id"`
	ScanFrequency    pgtype.Interval `json:"scan_frequency"`
	LanguageDefault  string          `json:"language_default"`
	LastSyncedPostID *string         `json:"last_synced_post_id"`
	AutoProcess      bool            `json:"auto_process"`
	AutoPublish      bool            `json:"auto_publish"`
	Status           string          `json:"status"`
	CreatedBy        uuid.UUID       `json:"created_by"`
	CreatedAt        time.Time       `json:"created_at"`
	ScanLimit        int32           `json:"scan_limit"`
	MaxPostsPerRun   *int32          `json:"max_posts_per_run"`
	LastScannedAt    *time.Time      `json:"last_scanned_at"`
}

type Prompt struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Content   string    `json:"content"`
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

type SkippedLog struct {
	ID             uuid.UUID `json:"id"`
	ListBreakingID uuid.UUID `json:"list_breaking_id"`
	PostIDExternal string    `json:"post_id_external"`
	Reason         string    `json:"reason"`
	CheckedAt      time.Time `json:"checked_at"`
}

type SourcePost struct {
	ID              uuid.UUID  `json:"id"`
	SourceType      string     `json:"source_type"`
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	SourceUrl       string     `json:"source_url"`
	Platform        string     `json:"platform"`
	ContentType     *string    `json:"content_type"`
	PostIDExtracted *string    `json:"post_id_extracted"`
	ExtractedText   *string    `json:"extracted_text"`
	CollectMode     string     `json:"collect_mode"`
	PromptID        *uuid.UUID `json:"prompt_id"`
	Language        string     `json:"language"`
	Status          string     `json:"status"`
	LastError       *string    `json:"last_error"`
	CreatedBy       uuid.UUID  `json:"created_by"`
	CreatedAt       time.Time  `json:"created_at"`
	Title           *string    `json:"title"`
	Hashtags        []string   `json:"hashtags"`
	ThumbnailUrl    *string    `json:"thumbnail_url"`
	AuthorName      *string    `json:"author_name"`
	PostedAt        *time.Time `json:"posted_at"`
}

type Voice struct {
	ID               uuid.UUID  `json:"id"`
	SourcePostID     *uuid.UUID `json:"source_post_id"`
	AiEngineID       *uuid.UUID `json:"ai_engine_id"`
	VoiceFileUrl     *string    `json:"voice_file_url"`
	DurationSeconds  *int32     `json:"duration_seconds"`
	Hashtag          *string    `json:"hashtag"`
	Language         string     `json:"language"`
	ImageUrl         *string    `json:"image_url"`
	PublishStatus    string     `json:"publish_status"`
	MultimePostUrl   *string    `json:"multime_post_url"`
	LastError        *string    `json:"last_error"`
	CreatedBy        uuid.UUID  `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	PublishedAt      *time.Time `json:"published_at"`
	Title            *string    `json:"title"`
	MimeType         *string    `json:"mime_type"`
	SizeBytes        *int64     `json:"size_bytes"`
	SampleRate       *int32     `json:"sample_rate"`
	InputText        *string    `json:"input_text"`
	CollectMode      *string    `json:"collect_mode"`
	PromptID         *uuid.UUID `json:"prompt_id"`
	AuthorID         *int64     `json:"author_id"`
	AuthorEmail      *string    `json:"author_email"`
	ImageUploaded    bool       `json:"image_uploaded"`
	AuthorGender     *string    `json:"author_gender"`
	PublishWhenReady bool       `json:"publish_when_ready"`
	NoImage          bool       `json:"no_image"`
}
