// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countPrompts = `-- name: CountPrompts :one
SELECT COUNT(*) FROM prompt
`

func (q *Queries) CountPrompts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPrompts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPrompt = `-- name: CreatePrompt :one
INSERT INTO prompt (name, content, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, content, created_by, created_at
`

type CreatePromptParams struct {
	Name      string    `json:"name"`
	Content   string    `json:"content"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, createPrompt, arg.Name, arg.Content, arg.CreatedBy)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePrompt = `-- name: DeletePrompt :execrows
DELETE FROM prompt WHERE id = $1
`

func (q *Queries) DeletePrompt(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePrompt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPrompt = `-- name: GetPrompt :one
SELECT id, name, content, created_by, created_at FROM prompt WHERE id = $1
`

func (q *Queries) GetPrompt(ctx context.Context, id uuid.UUID) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPrompt, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPrompts = `-- name: ListPrompts :many
SELECT id, name, content, created_by, created_at FROM prompt
ORDER BY
  CASE WHEN $1::text = 'asc' THEN created_at END ASC,
  created_at DESC
LIMIT $3 OFFSET $2
`

type ListPromptsParams struct {
	Dir string `json:"dir"`
	Off int32  `json:"off"`
	Lim int32  `json:"lim"`
}

func (q *Queries) ListPrompts(ctx context.Context, arg ListPromptsParams) ([]Prompt, error) {
	rows, err := q.db.Query(ctx, listPrompts, arg.Dir, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrompt = `-- name: UpdatePrompt :one
UPDATE prompt
SET name    = COALESCE($1, name),
    content = COALESCE($2, content)
WHERE id = $3
RETURNING id, name, content, created_by, created_at
`

type UpdatePromptParams struct {
	Name    *string   `json:"name"`
	Content *string   `json:"content"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePrompt(ctx context.Context, arg UpdatePromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, updatePrompt, arg.Name, arg.Content, arg.ID)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
