// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Chỉ 1 worker được xử lý 1 bài tại 1 thời điểm (idempotent khi Asynq retry).
	ClaimSourcePostForProcessing(ctx context.Context, id uuid.UUID) (SourcePost, error)
	// Nhận Voice về để đọc. Chỉ nhận khi voice đang `processing` hoặc đã `failed`:
	// Asynq retry lần sau vẫn nhặt lại được, còn voice đã ra file (draft/ready) thì
	// không đọc đè lên — muốn đọc lại phải đi qua SetVoiceContent, nơi người dùng
	// chốt lại lời đọc. Voice đã publish thì không bao giờ đụng vào.
	ClaimVoiceForProcessing(ctx context.Context, id uuid.UUID) (Voice, error)
	// Token hết hiệu lực và refresh cũng thất bại -> buộc user đăng nhập lại.
	ClearUserMultimeToken(ctx context.Context, id uuid.UUID) error
	CountAdmins(ctx context.Context) (int64, error)
	// Tổng số bản ghi khớp bộ lọc, để bảng phân trang biết có bao nhiêu trang.
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	// Tổng số kênh khớp bộ lọc, để bảng phân trang biết có bao nhiêu trang.
	CountListBreakings(ctx context.Context, arg CountListBreakingsParams) (int64, error)
	// Tổng số kênh khớp bộ lọc, để bảng phân trang biết có bao nhiêu trang.
	CountListScheduleds(ctx context.Context, arg CountListScheduledsParams) (int64, error)
	CountPrompts(ctx context.Context) (int64, error)
	// Tỉ lệ bỏ qua giúp đánh giá regex có quá chặt/quá lỏng hay không.
	CountSkippedLogsSince(ctx context.Context, arg CountSkippedLogsSinceParams) (int64, error)
	CountSourcePosts(ctx context.Context, arg CountSourcePostsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Lọc theo trạng thái NGƯỜI DÙNG THẤY, không phải cột thô: voice còn thiếu điều
	// kiện đăng (chưa chọn author, chưa có hashtag/tiêu đề, audio ngắn hơn mức
	// multime nhận) hiện badge "Chưa đủ điều kiện", nên chọn trạng thái đó phải ra
	// đúng những dòng ấy — và "Nháp"/"Chờ đăng" thì không được lẫn chúng.
	//
	// 'incomplete' KHÔNG phải giá trị có trong cột publish_status: nó là trạng thái
	// suy ra lúc đọc. Thiếu hashtag là việc người dùng chưa điền xong, khác hẳn
	// 'failed' (đã gửi lên multime và bị từ chối), nên không gộp chung.
	CountVoices(ctx context.Context, arg CountVoicesParams) (int64, error)
	// user_id là CHỦ SỞ HỮU key (worker chạy TTS của người đó bằng key này),
	// created_by là người bấm nút — khác nhau khi admin khai hộ.
	CreateAIEngine(ctx context.Context, arg CreateAIEngineParams) (AiEngine, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateListBreaking(ctx context.Context, arg CreateListBreakingParams) (ListBreaking, error)
	CreateListScheduled(ctx context.Context, arg CreateListScheduledParams) (ListScheduled, error)
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error)
	CreateSkippedLog(ctx context.Context, arg CreateSkippedLogParams) error
	CreateSourcePost(ctx context.Context, arg CreateSourcePostParams) (SourcePost, error)
	// Voice gõ tay: không có Bài Post nào đứng sau, nội dung nằm thẳng trên Voice.
	// Tạo ở trạng thái `processing` để người dùng thấy ngay dòng voice đang chạy,
	// worker điền file + metadata vào đúng dòng đó (FinishVoice).
	CreateTextVoice(ctx context.Context, arg CreateTextVoiceParams) (Voice, error)
	CreateVoice(ctx context.Context, arg CreateVoiceParams) (Voice, error)
	DeleteAIEngine(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteListBreaking(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteListScheduled(ctx context.Context, id uuid.UUID) (int64, error)
	DeletePrompt(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSkippedLogsBefore(ctx context.Context, before time.Time) (int64, error)
	DeleteSourcePost(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteVoice(ctx context.Context, id uuid.UUID) (int64, error)
	// Tra cứu bài trùng theo ID bài đăng trên nền tảng (KHÔNG theo URL): cùng 1
	// bài có nhiều dạng URL khác nhau nhưng chỉ 1 id.
	// Trả bản CŨ NHẤT để thông báo trùng luôn trỏ về bài gốc.
	FindSourcePostByPostID(ctx context.Context, arg FindSourcePostByPostIDParams) (SourcePost, error)
	// Worker điền kết quả vào record `processing` đã tạo sẵn lúc enqueue.
	// Metadata dùng COALESCE: fetch không ra tiêu đề thì giữ nguyên phần đã điền
	// sẵn từ Bài Post, không xoá trắng.
	FinishVoice(ctx context.Context, arg FinishVoiceParams) (Voice, error)
	GetAIEngine(ctx context.Context, id uuid.UUID) (GetAIEngineRow, error)
	// Key mà worker dùng khi chạy TTS cho voice của user này: key mới khai nhất
	// (thay key thì key mới thắng ngay, không phải xoá key cũ trước).
	GetAIEngineForUser(ctx context.Context, userID uuid.UUID) (AiEngine, error)
	GetListBreaking(ctx context.Context, id uuid.UUID) (ListBreaking, error)
	GetListScheduled(ctx context.Context, id uuid.UUID) (ListScheduled, error)
	GetPrompt(ctx context.Context, id uuid.UUID) (Prompt, error)
	GetSourcePost(ctx context.Context, id uuid.UUID) (SourcePost, error)
	GetUserByEmail(ctx context.Context, email string) (AppUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AppUser, error)
	GetVoice(ctx context.Context, id uuid.UUID) (Voice, error)
	// `owner` NULL = xem tất cả (admin). User thường luôn được service ép owner =
	// chính mình, nên không đọc được key của người khác dù gọi thẳng API.
	ListAIEngines(ctx context.Context, owner *uuid.UUID) ([]ListAIEnginesRow, error)
	ListActiveListBreakings(ctx context.Context) ([]ListBreaking, error)
	ListActiveListScheduleds(ctx context.Context) ([]ListScheduled, error)
	// Kèm email người thao tác để bảng nhật ký hiện được "ai làm" mà không phải
	// gọi thêm API. LEFT JOIN cho chắc: bản ghi audit không được mất chỉ vì user
	// tham chiếu không đọc được.
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	// Chỉ lấy kênh đã quá khoảng nghỉ của chính nó (scan_interval), fallback về
	// khoảng nghỉ mặc định của hệ thống khi kênh không cấu hình riêng.
	ListDueListBreakings(ctx context.Context, defaultInterval pgtype.Interval) ([]ListBreaking, error)
	// Sắp xếp động theo cột thời gian đang chọn; mặc định kênh mới nhất trước.
	ListListBreakings(ctx context.Context, arg ListListBreakingsParams) ([]ListListBreakingsRow, error)
	// Sắp xếp động theo cột thời gian đang chọn; mặc định kênh mới nhất trước.
	ListListScheduleds(ctx context.Context, arg ListListScheduledsParams) ([]ListListScheduledsRow, error)
	ListPrompts(ctx context.Context, arg ListPromptsParams) ([]Prompt, error)
	ListSkippedLogs(ctx context.Context, arg ListSkippedLogsParams) ([]SkippedLog, error)
	// Sắp xếp động: chỉ có 1 cột thời gian nên chỉ cần chiều. Nhánh CASE toàn
	// NULL khi dir='desc' -> rơi về mặc định mới nhất trước.
	ListSourcePosts(ctx context.Context, arg ListSourcePostsParams) ([]ListSourcePostsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]AppUser, error)
	// Trả kèm nền tảng nguồn + email người tạo để bảng Voice hiển thị và lọc được
	// mà không phải gọi thêm API (prompt.md mục 3, 4, 8).
	// Lọc theo trạng thái NGƯỜI DÙNG THẤY, không phải cột thô: voice còn thiếu điều
	// kiện đăng (chưa chọn author, chưa có hashtag/tiêu đề, audio ngắn hơn mức
	// multime nhận) hiện badge "Chưa đủ điều kiện", nên chọn trạng thái đó phải ra
	// đúng những dòng ấy — và "Nháp"/"Chờ đăng" thì không được lẫn chúng.
	//
	// 'incomplete' KHÔNG phải giá trị có trong cột publish_status: nó là trạng thái
	// suy ra lúc đọc. Thiếu hashtag là việc người dùng chưa điền xong, khác hẳn
	// 'failed' (đã gửi lên multime và bị từ chối), nên không gộp chung.
	// Sắp xếp động: mỗi nhánh CASE chỉ có giá trị khi đúng cột + đúng chiều đang
	// chọn, các nhánh còn lại toàn NULL nên không ảnh hưởng thứ tự. Dòng cuối là
	// mặc định (mới nhất trước) và cũng là nhánh sort=created_at + dir=desc.
	ListVoices(ctx context.Context, arg ListVoicesParams) ([]ListVoicesRow, error)
	ListVoicesBySourcePost(ctx context.Context, sourcePostID *uuid.UUID) ([]Voice, error)
	// Business rule #2: publish thành công -> xoá file S3 và set voice_file_url = NULL,
	// chỉ giữ multime_post_url làm nguồn tham chiếu duy nhất.
	// Ảnh bìa tải từ máy cũng bị xoá theo cùng lý do: multime đã giữ bản của nó,
	// bản trong bucket của mình không còn ai đọc nữa. Ảnh lấy từ URL bài gốc không
	// nằm trong bucket nên giữ nguyên link.
	MarkVoicePublished(ctx context.Context, arg MarkVoicePublishedParams) (Voice, error)
	SetLastSyncedPostID(ctx context.Context, arg SetLastSyncedPostIDParams) error
	SetSourcePostStatus(ctx context.Context, arg SetSourcePostStatusParams) (SourcePost, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (AppUser, error)
	// Cập nhật access token sau khi refresh với strongbody.
	SetUserMultimeToken(ctx context.Context, arg SetUserMultimeTokenParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) (AppUser, error)
	// Chốt lời đọc mới cho 1 Voice rồi đưa lại vào hàng đợi.
	//
	// Đặt luôn publish_status='processing' trong cùng câu lệnh: người dùng bấm
	// "Tạo lại" là thấy dòng voice chuyển sang đang xử lý ngay, không có khoảng
	// giữa mà bảng vẫn hiện voice cũ như chưa có gì xảy ra.
	SetVoiceContent(ctx context.Context, arg SetVoiceContentParams) (Voice, error)
	// Ảnh bìa tải từ máy: image_uploaded = TRUE đánh dấu file nằm trong storage của
	// mình, để sau khi đăng lên multime thì xoá đi cho đỡ tốn dung lượng.
	SetVoiceImage(ctx context.Context, arg SetVoiceImageParams) (Voice, error)
	SetVoicePublishStatus(ctx context.Context, arg SetVoicePublishStatusParams) (Voice, error)
	// Đóng dấu thời điểm key thật sự đọc ra audio. Chỉ gọi sau khi TTS thành công:
	// cột này để người dùng biết key nào còn sống, key nào khai xong bỏ đó.
	TouchAIEngineUsed(ctx context.Context, id uuid.UUID) error
	TouchListBreakingScanned(ctx context.Context, id uuid.UUID) error
	TouchListScheduledScanned(ctx context.Context, id uuid.UUID) error
	// api_key_encrypted dùng COALESCE: bỏ trống ô API key ở form nghĩa là "giữ key
	// cũ" — key thật không bao giờ gửi về trình duyệt nên không có gì để gửi lại.
	UpdateAIEngine(ctx context.Context, arg UpdateAIEngineParams) (AiEngine, error)
	UpdateListBreaking(ctx context.Context, arg UpdateListBreakingParams) (ListBreaking, error)
	UpdateListScheduled(ctx context.Context, arg UpdateListScheduledParams) (ListScheduled, error)
	UpdatePrompt(ctx context.Context, arg UpdatePromptParams) (Prompt, error)
	UpdateSourcePost(ctx context.Context, arg UpdateSourcePostParams) (SourcePost, error)
	// Worker ghi lại metadata gốc lấy được từ nền tảng để Voice và form đăng bài
	// auto-fill từ đây.
	//
	// `title` là TOÀN BỘ nội dung bài (trừ hashtag) — hệ thống không còn trường mô
	// tả riêng. COALESCE để lần fetch không ra thì giữ nguyên phần đã có.
	UpdateSourcePostMetadata(ctx context.Context, arg UpdateSourcePostMetadataParams) (SourcePost, error)
	// author_id/author_email/author_gender đi thành một bộ: bốc tác giả là nhận cả
	// ba, nên không COALESCE riêng lẻ để tránh trạng thái id của người này còn
	// email/giới tính của người kia.
	UpdateVoiceMetadata(ctx context.Context, arg UpdateVoiceMetadataParams) (Voice, error)
	// Đăng nhập bằng strongbody: tạo user nếu chưa có, cập nhật thông tin + token
	// nếu đã có. Role của lần tạo đầu do $5 quyết định, các lần sau KHÔNG ghi đè
	// (admin đã cấp quyền thì giữ nguyên).
	UpsertUserFromSSO(ctx context.Context, arg UpsertUserFromSSOParams) (AppUser, error)
}

var _ Querier = (*Queries)(nil)
