// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Bật key mới nhất cho người này, CHỈ KHI họ không còn key nào đang bật.
	//
	// Gọi sau khi xoá hoặc chuyển đi key đang bật: trước khi có công tắc, xoá key
	// đang dùng thì key còn lại tự động thế chỗ (luật "key mới nhất thắng"). Không
	// làm vậy nữa thì một thao tác xoá lại lặng lẽ làm chết mọi voice tiếp theo.
	ActivateLatestAIEngine(ctx context.Context, userID uuid.UUID) error
	AddLLMAPISetUser(ctx context.Context, arg AddLLMAPISetUserParams) error
	// Đếm 1 lần bị nền tảng chặn. Gộp theo ngày nên bảng không phình theo từng lỗi,
	// và vẫn đủ để trả lời câu hỏi duy nhất nó sinh ra để trả lời: nền tảng nào
	// đang bị chặn nhiều tới mức đáng mua proxy.
	BumpFetchErrorStat(ctx context.Context, arg BumpFetchErrorStatParams) error
	// Câu hỏi của WORKER, không phải của UI: bộ này có thật sự dùng được cho người
	// tạo voice không. Trả về bộ nếu được, không có dòng nào nếu không.
	CanUseLLMAPISet(ctx context.Context, arg CanUseLLMAPISetParams) (LlmApiSet, error)
	// Đối xứng với CascadeLanguageFromListScheduled — xem lý do ở đó.
	CascadeLanguageFromListBreaking(ctx context.Context, arg CascadeLanguageFromListBreakingParams) (int64, error)
	// Đổi ngôn ngữ của kênh thì các Bài Post của kênh đó đi theo.
	//
	// Vì sao phải lan xuống: ngôn ngữ được chốt MỘT LẦN lúc bài được tạo, nên sửa
	// ở kênh mà không lan thì mọi bài đã lấy về vẫn đọc bằng tiếng cũ — đúng thứ
	// người dùng vừa sửa để tránh.
	CascadeLanguageFromListScheduled(ctx context.Context, arg CascadeLanguageFromListScheduledParams) (int64, error)
	CascadeVoiceLanguageFromListBreaking(ctx context.Context, arg CascadeVoiceLanguageFromListBreakingParams) (int64, error)
	// Chỉ những Voice CHƯA có file: ngôn ngữ của voice đã ghi xong là mô tả của
	// một file audio có thật, đổi nhãn không đổi được tiếng trong file. Voice đang
	// chờ/đang lỗi thì chạy lại sẽ đọc bằng tiếng mới, nên sửa là đúng.
	CascadeVoiceLanguageFromListScheduled(ctx context.Context, arg CascadeVoiceLanguageFromListScheduledParams) (int64, error)
	// Đổi ngôn ngữ của Bài Post thì các Voice CHƯA có file của bài đó đi theo.
	//
	// Cùng ranh giới với cascade từ kênh: voice đã ghi xong file là mô tả của một
	// file audio có thật, đổi nhãn không đổi được tiếng đã đọc trong file.
	CascadeVoiceLanguageFromPost(ctx context.Context, arg CascadeVoiceLanguageFromPostParams) (int64, error)
	// Nhận proxy cho MỘT request: nghỉ lâu nhất trước. Chọn-và-đánh-dấu trong một
	// câu, cùng lý do với ClaimScrapeVia.
	//
	// `platform IS NULL` lọt vào kết quả: đó là gateway residential dùng chung cho
	// mọi nền tảng. Proxy gán đích danh nền tảng được ưu tiên hơn (ORDER BY đẩy
	// `platform IS NULL` xuống sau) vì gán đích danh là có chủ đích.
	//
	// Chỉ lấy `active`: `degraded` và `dead` đứng ngoài vòng chọn cho tới khi có
	// người bật lại tay. Xem MarkScrapeProxyBlocked.
	ClaimScrapeProxy(ctx context.Context, platform *string) (ScrapeProxy, error)
	// Nhận via cho MỘT lượt quét: nghỉ lâu nhất trước (round-robin theo thời gian
	// nghỉ), trong nhóm còn khoẻ và còn hạn mức ngày.
	//
	// CHỌN VÀ ĐÁNH DẤU TRONG MỘT CÂU, không phải SELECT rồi UPDATE. Hai worker quét
	// song song mà đọc rồi mới ghi thì cả hai cùng thấy một via "nghỉ lâu nhất" và
	// cùng dùng nó — vòng xoay đứng im, một via gánh hết tải, đúng thứ cần tránh
	// nhất khi tài sản quý là số via còn sống. Một câu UPDATE thì Postgres tự khoá
	// dòng, worker thứ hai thấy last_used_at đã đổi và nhận via kế tiếp.
	//
	// SKIP LOCKED ở subquery: worker thứ hai nhảy sang via kế thay vì xếp hàng chờ
	// — có vài trăm kênh cần quét thì chờ nhau là tự dồn burst về cuối hàng.
	//
	// Chỉ đặt last_used_at ở đây, KHÔNG trừ hạn mức: hạn mức trừ khi lượt quét
	// thành công (xem MarkScrapeViaUsed). Một request bị proxy làm hỏng không phải
	// lỗi của via và không đáng lấy mất một suất của nó.
	//
	// `daily_used_date < CURRENT_DATE` cũng được coi là CÒN hạn mức: bộ đếm của
	// ngày hôm qua không phải hạn mức của hôm nay. Nhờ vậy việc reset tự liền ngay
	// cả khi job cron lỡ nhịp.
	ClaimScrapeVia(ctx context.Context, platform string) (ScrapeVia, error)
	// Chỉ 1 worker được xử lý 1 bài tại 1 thời điểm (idempotent khi Asynq retry).
	ClaimSourcePostForProcessing(ctx context.Context, id uuid.UUID) (SourcePost, error)
	// Nhận Voice về để đọc. Chỉ nhận khi voice đang `processing` hoặc đã `failed`:
	// Asynq retry lần sau vẫn nhặt lại được, còn voice đã ra file (draft/ready) thì
	// không đọc đè lên — muốn đọc lại phải đi qua SetVoiceContent, nơi người dùng
	// chốt lại lời đọc. Voice đã publish thì không bao giờ đụng vào.
	ClaimVoiceForProcessing(ctx context.Context, id uuid.UUID) (Voice, error)
	ClearLLMAPISetUsers(ctx context.Context, setID uuid.UUID) error
	// Token hết hiệu lực và refresh cũng thất bại -> buộc user đăng nhập lại.
	ClearUserMultimeToken(ctx context.Context, id uuid.UUID) error
	// Người này có đang bật key nào không — dùng lúc thêm key mới để quyết định
	// key đó vào ở trạng thái bật hay tắt.
	CountActiveAIEngines(ctx context.Context, userID uuid.UUID) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	// Tổng số bản ghi khớp bộ lọc, để bảng phân trang biết có bao nhiêu trang.
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	// Câu hỏi lúc KHỞI ĐỘNG: hệ thống có đường nào chạy được mode C không.
	// Mode C cần LLM thật; trước đây điều đó chỉ đọc từ .env, nhưng giờ đường chính
	// là Bộ API key trong DB — chỉ nhìn .env thì tắt nhầm mode C của cả hệ thống.
	CountLLMAPIKeys(ctx context.Context) (int64, error)
	// Bảng danh sách bộ hiện "số key theo từng nhà" mà không phải tải hết key về.
	CountLLMAPIKeysBySet(ctx context.Context, setIds []uuid.UUID) ([]CountLLMAPIKeysBySetRow, error)
	// Tổng số kênh khớp bộ lọc, để bảng phân trang biết có bao nhiêu trang.
	CountListBreakings(ctx context.Context, arg CountListBreakingsParams) (int64, error)
	// Tổng số kênh khớp bộ lọc, để bảng phân trang biết có bao nhiêu trang.
	CountListScheduleds(ctx context.Context, arg CountListScheduledsParams) (int64, error)
	CountPrompts(ctx context.Context) (int64, error)
	CountScanRuns(ctx context.Context, arg CountScanRunsParams) (int64, error)
	// Bảng tổng quan trên màn Cài đặt: bao nhiêu via sống/chết theo từng nền tảng.
	//
	// Đếm theo đúng phạm vi người xem được nhìn (`owner` NULL = cả hệ thống, chỉ
	// admin): một editor thấy 3 via của mình mà ô tổng quan nói 40 thì con số đó
	// không trả lời được câu hỏi duy nhất họ có — "via CỦA TÔI còn đủ không".
	CountScrapeViasByStatus(ctx context.Context, owner *uuid.UUID) ([]CountScrapeViasByStatusRow, error)
	CountSkippedLogs(ctx context.Context, listBreakingID uuid.UUID) (int64, error)
	// Tỉ lệ bỏ qua giúp đánh giá regex có quá chặt/quá lỏng hay không.
	CountSkippedLogsSince(ctx context.Context, arg CountSkippedLogsSinceParams) (int64, error)
	CountSourcePosts(ctx context.Context, arg CountSourcePostsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountViaUsageLogs(ctx context.Context, arg CountViaUsageLogsParams) (int64, error)
	// Lọc theo trạng thái NGƯỜI DÙNG THẤY, không phải cột thô: voice còn thiếu điều
	// kiện đăng (chưa chọn author, chưa có hashtag/tiêu đề, audio ngắn hơn mức
	// multime nhận) hiện badge "Chưa đủ điều kiện", nên chọn trạng thái đó phải ra
	// đúng những dòng ấy — và "Nháp"/"Chờ đăng" thì không được lẫn chúng.
	//
	// 'incomplete' KHÔNG phải giá trị có trong cột publish_status: nó là trạng thái
	// suy ra lúc đọc. Thiếu hashtag là việc người dùng chưa điền xong, khác hẳn
	// 'failed' (đã gửi lên multime và bị từ chối), nên không gộp chung.
	CountVoices(ctx context.Context, arg CountVoicesParams) (int64, error)
	// Mốc đồng bộ cũ nhất trong bảng: chỉ cần 1 bản ghi quá hạn là đồng bộ lại cả
	// danh mục, vì chúng luôn được ghi cùng một lượt.
	CountriesSyncedAt(ctx context.Context) (CountriesSyncedAtRow, error)
	// user_id là CHỦ SỞ HỮU key (worker chạy TTS của người đó bằng key này),
	// created_by là người bấm nút — khác nhau khi admin khai hộ.
	//
	// is_active do service quyết định: key ĐẦU TIÊN của một người thì bật luôn
	// (không thì họ khai key xong voice vẫn báo "chưa bật key nào"), còn người đã
	// có key đang chạy thì key mới vào ở trạng thái tắt — thêm một key dự phòng
	// không được âm thầm đổi giọng đọc của họ.
	CreateAIEngine(ctx context.Context, arg CreateAIEngineParams) (AiEngine, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// ---------------------------------------------------------------------------
	// Key trong bộ
	// ---------------------------------------------------------------------------
	CreateLLMAPIKey(ctx context.Context, arg CreateLLMAPIKeyParams) (LlmApiKey, error)
	CreateLLMAPISet(ctx context.Context, arg CreateLLMAPISetParams) (LlmApiSet, error)
	CreateListBreaking(ctx context.Context, arg CreateListBreakingParams) (ListBreaking, error)
	CreateListScheduled(ctx context.Context, arg CreateListScheduledParams) (ListScheduled, error)
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error)
	// ---------------------------------------------------------------------------
	// Proxy (lối ra mạng cho các request quét)
	// ---------------------------------------------------------------------------
	// user_id là CHỦ SỞ HỮU, created_by là người khai — xem CreateScrapeVia.
	CreateScrapeProxy(ctx context.Context, arg CreateScrapeProxyParams) (ScrapeProxy, error)
	// ---------------------------------------------------------------------------
	// Via (phiên đăng nhập dùng để quét trang công khai)
	// ---------------------------------------------------------------------------
	// user_id là CHỦ SỞ HỮU (người thấy và sửa được via này), created_by là người
	// bấm nút — khác nhau khi admin khai hộ. Cùng ý nghĩa với ai_engine.
	CreateScrapeVia(ctx context.Context, arg CreateScrapeViaParams) (ScrapeVia, error)
	CreateSkippedLog(ctx context.Context, arg CreateSkippedLogParams) error
	CreateSourcePost(ctx context.Context, arg CreateSourcePostParams) (SourcePost, error)
	// Voice gõ tay: không có Bài Post nào đứng sau, nội dung nằm thẳng trên Voice.
	// Tạo ở trạng thái `processing` để người dùng thấy ngay dòng voice đang chạy,
	// worker điền file + metadata vào đúng dòng đó (FinishVoice).
	CreateTextVoice(ctx context.Context, arg CreateTextVoiceParams) (Voice, error)
	// ---------------------------------------------------------------------------
	// via_usage_log
	// ---------------------------------------------------------------------------
	CreateViaUsageLog(ctx context.Context, arg CreateViaUsageLogParams) error
	// Metadata người dùng điền sẵn ở màn tạo Voice đi vào ngay từ đây (title,
	// hashtag, author, ảnh): worker sau đó chỉ ĐIỀN VÀO CHỖ TRỐNG chứ không ghi đè,
	// nên giá trị người dùng gõ luôn thắng giá trị lấy từ bài gốc.
	CreateVoice(ctx context.Context, arg CreateVoiceParams) (Voice, error)
	// Tắt mọi key khác của cùng một người. Tách thành câu riêng chạy TRƯỚC câu bật
	// vì unique index kiểm tra ngay trên từng dòng: gộp thành một UPDATE
	// `is_active = (id = $1)` có thể chạm đúng lúc hai dòng cùng bật và văng lỗi.
	DeactivateOtherAIEngines(ctx context.Context, arg DeactivateOtherAIEnginesParams) error
	DeleteAIEngine(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteAIUsageBefore(ctx context.Context, before time.Time) (int64, error)
	DeleteLLMAPIKey(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteLLMAPISet(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteListBreaking(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteListScheduled(ctx context.Context, id uuid.UUID) (int64, error)
	DeletePrompt(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteScanRunsBefore(ctx context.Context, before time.Time) (int64, error)
	DeleteScrapeProxy(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteScrapeVia(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSkippedLogsBefore(ctx context.Context, before time.Time) (int64, error)
	DeleteSourcePost(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteViaUsageLogsBefore(ctx context.Context, before time.Time) (int64, error)
	DeleteVoice(ctx context.Context, id uuid.UUID) (int64, error)
	// Đóng những vòng quét không bao giờ kết thúc.
	//
	// Worker bị kill giữa vòng quét thì không ai chạy FinishScanRun, và dòng đó
	// nằm lại ở 'running' vĩnh viễn. Trên bảng kênh nó chỉ sai cho tới vòng kế
	// tiếp (bảng đọc vòng MỚI NHẤT), nhưng trong tab lịch sử thì nó sai mãi — và
	// một dòng "đang quét" từ tuần trước là thứ khiến người đọc mất lòng tin vào
	// cả bảng.
	FailStaleScanRuns(ctx context.Context, before time.Time) (int64, error)
	// Tra cứu bài trùng theo ID bài đăng trên nền tảng (KHÔNG theo URL): cùng 1
	// bài có nhiều dạng URL khác nhau nhưng chỉ 1 id.
	// Trả bản CŨ NHẤT để thông báo trùng luôn trỏ về bài gốc.
	FindSourcePostByPostID(ctx context.Context, arg FindSourcePostByPostIDParams) (SourcePost, error)
	// Đóng vòng quét kèm kết quả. Ghi một lần ở cuối chứ không cộng dồn từng bài:
	// vòng quét đã có sẵn bộ đếm trong bộ nhớ, và mỗi bài một UPDATE thì một kênh
	// scan_limit=200 thành 200 lượt ghi cho một dòng.
	FinishScanRun(ctx context.Context, arg FinishScanRunParams) error
	// Worker điền kết quả vào record `processing` đã tạo sẵn lúc enqueue.
	// Metadata dùng COALESCE: fetch không ra tiêu đề thì giữ nguyên phần đã điền
	// sẵn từ Bài Post, không xoá trắng.
	FinishVoice(ctx context.Context, arg FinishVoiceParams) (Voice, error)
	GetAIEngine(ctx context.Context, id uuid.UUID) (GetAIEngineRow, error)
	// Key mà worker dùng khi chạy TTS cho voice của user này: key ĐANG BẬT.
	//
	// Chỉ số ít (uq_ai_engine_active_per_user bảo đảm mỗi người nhiều nhất 1 key
	// bật), nhưng vẫn LIMIT 1 để query không phụ thuộc vào index đó còn tồn tại.
	// Không có dòng nào = người này chưa khai key, hoặc đã tắt hết — cả hai đều
	// không chạy TTS được, và ttsFor nói ra đúng câu đó.
	GetAIEngineForUser(ctx context.Context, userID uuid.UUID) (AiEngine, error)
	GetAppSetting(ctx context.Context, key string) (AppSetting, error)
	// Ba con số trả lời "hệ thống có đang hỏng âm thầm không", gộp trong 1 lượt đọc
	// vì chúng luôn được hỏi cùng nhau (thanh cảnh báo trên giao diện).
	GetHealthCounters(ctx context.Context) (GetHealthCountersRow, error)
	GetLLMAPIKey(ctx context.Context, id uuid.UUID) (LlmApiKey, error)
	GetLLMAPISet(ctx context.Context, id uuid.UUID) (GetLLMAPISetRow, error)
	GetListBreaking(ctx context.Context, id uuid.UUID) (ListBreaking, error)
	GetListScheduled(ctx context.Context, id uuid.UUID) (ListScheduled, error)
	GetPrompt(ctx context.Context, id uuid.UUID) (Prompt, error)
	GetScrapeProxy(ctx context.Context, id uuid.UUID) (ScrapeProxy, error)
	GetScrapeVia(ctx context.Context, id uuid.UUID) (ScrapeVia, error)
	GetSourcePost(ctx context.Context, id uuid.UUID) (SourcePost, error)
	GetUserByEmail(ctx context.Context, email string) (AppUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AppUser, error)
	GetVoice(ctx context.Context, id uuid.UUID) (Voice, error)
	HashtagsSyncedAt(ctx context.Context) (HashtagsSyncedAtRow, error)
	// Prompt mẫu + Bộ API mà CHÍNH người này dùng gần đây nhất ở hình thức C.
	//
	// Để form tạo voice chọn sẵn thay vì bắt chọn lại mỗi lần: gần như ai cũng chạy
	// đi chạy lại cùng một prompt, và hai ô bắt buộc phải tự tay chọn ở mỗi lần tạo
	// là hai lần bấm thừa cộng một lần quên.
	//
	// Hai cột lấy ĐỘC LẬP, mỗi cột từ voice gần nhất có giá trị: chúng được chọn
	// riêng, nên voice gần nhất có prompt chưa chắc là voice gần nhất có bộ API.
	LastUsedPromptAndSet(ctx context.Context, userID uuid.UUID) (LastUsedPromptAndSetRow, error)
	// `owner` NULL = xem tất cả (admin). User thường luôn được service ép owner =
	// chính mình, nên không đọc được key của người khác dù gọi thẳng API.
	//
	// Xếp theo THỜI GIAN TẠO, mới nhất trước — giống mọi bảng khác trong hệ thống.
	// Trước đây admin thấy danh sách gom theo email: key vừa thêm rơi vào giữa
	// bảng theo thứ tự chữ cái, nên thao tác thường gặp nhất (khai key xong xem nó
	// đã vào chưa) lại là thao tác khó nhất.
	ListAIEngines(ctx context.Context, owner *uuid.UUID) ([]ListAIEnginesRow, error)
	// Gộp theo ngày + model: đủ chi tiết để so hai model với nhau, đủ thô để bảng
	// không dài hơn một màn hình sau một tuần chạy thật.
	ListAIUsageDaily(ctx context.Context, days int32) ([]ListAIUsageDailyRow, error)
	ListActiveListBreakings(ctx context.Context) ([]ListBreaking, error)
	ListActiveListScheduleds(ctx context.Context) ([]ListScheduled, error)
	ListAppSettings(ctx context.Context) ([]AppSetting, error)
	// Kèm email người thao tác để bảng nhật ký hiện được "ai làm" mà không phải
	// gọi thêm API. LEFT JOIN cho chắc: bản ghi audit không được mất chỉ vì user
	// tham chiếu không đọc được.
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	// Thứ tự nghiệp vụ trước, rồi alphabet cho phần còn lại — xem cột sort_order.
	ListCountries(ctx context.Context) ([]Country, error)
	// Chỉ lấy kênh đã quá khoảng nghỉ của chính nó (scan_interval), fallback về
	// khoảng nghỉ mặc định của hệ thống khi kênh không cấu hình riêng.
	ListDueListBreakings(ctx context.Context, defaultInterval pgtype.Interval) ([]ListBreaking, error)
	ListFetchErrorStats(ctx context.Context, days int32) ([]FetchErrorStat, error)
	// Danh sách cho ô chọn: tag MultiMe tuyển chọn (is_featured, rồi `system`) lên
	// trước, phần còn lại theo ordering/tên.
	//
	// `q` rỗng = lấy phần đầu danh mục. Có `q` thì lọc ngay trong DB: danh mục có
	// ~94.000 tag nên không thể đẩy hết về trình duyệt để lọc tại chỗ.
	ListHashtags(ctx context.Context, arg ListHashtagsParams) ([]ListHashtagsRow, error)
	// Thứ tự ở đây chính là thứ tự router thử key trong cùng 1 nhà: priority nhỏ
	// trước, hoà thì theo id cho TẤT ĐỊNH — router không được xoay ngẫu nhiên.
	ListLLMAPIKeys(ctx context.Context, setID uuid.UUID) ([]LlmApiKey, error)
	// ---------------------------------------------------------------------------
	// Chia sẻ bộ cho người dùng
	// ---------------------------------------------------------------------------
	ListLLMAPISetUsers(ctx context.Context, setIds []uuid.UUID) ([]ListLLMAPISetUsersRow, error)
	// `viewer` NULL = xem tất cả (admin). Người dùng thường được service truyền
	// chính id của họ vào, và chỉ thấy bộ mình tạo / được chia sẻ / admin đã bật
	// hiển thị — chặn ở SQL chứ không chỉ ẩn trên UI.
	ListLLMAPISets(ctx context.Context, viewer *uuid.UUID) ([]ListLLMAPISetsRow, error)
	// Hai số đếm, cùng lý do và cùng cách dựng với ListListScheduleds.
	// Sắp xếp động theo cột thời gian đang chọn; mặc định kênh mới nhất trước.
	ListListBreakings(ctx context.Context, arg ListListBreakingsParams) ([]ListListBreakingsRow, error)
	// Kèm hai số đếm để bảng trả lời được "kênh này có ra gì không" mà không phải
	// mở màn Bài Post lọc theo kênh.
	//
	// Subquery vô hướng chứ không JOIN + GROUP BY: một kênh không có bài nào vẫn
	// phải hiện 0 chứ không biến mất, và GROUP BY trên `ls.*` thì phải liệt kê lại
	// toàn bộ cột mỗi lần thêm cột mới vào bảng. Cả hai đều đi qua chỉ mục riêng
	// trên list_scheduled_id (migration 000021).
	// Sắp xếp động theo cột thời gian đang chọn; mặc định kênh mới nhất trước.
	ListListScheduleds(ctx context.Context, arg ListListScheduledsParams) ([]ListListScheduledsRow, error)
	ListPrompts(ctx context.Context, arg ListPromptsParams) ([]Prompt, error)
	// Lịch sử của ĐÚNG MỘT kênh — service luôn truyền đúng một trong hai id.
	ListScanRuns(ctx context.Context, arg ListScanRunsParams) ([]ListScanRunsRow, error)
	// `owner` NULL = xem tất cả (chỉ admin) — xem ListScrapeVias.
	//
	// Bộ lọc nền tảng nằm trong DẤU NGOẶC riêng: không có nó thì `OR platform IS
	// NULL` cũng nuốt luôn điều kiện chủ sở hữu, và mọi proxy dùng chung của người
	// khác lọt vào danh sách của một editor.
	ListScrapeProxies(ctx context.Context, arg ListScrapeProxiesParams) ([]ListScrapeProxiesRow, error)
	// Bảng quản lý trên màn Cài đặt. Sắp theo nền tảng rồi nhãn để danh sách đứng
	// yên giữa các lần tải — sắp theo trạng thái thì dòng nhảy chỗ mỗi lần một via
	// vào cooldown, đúng lúc người ta đang nhìn nó.
	//
	// `owner` NULL = xem tất cả (chỉ admin). Editor luôn bị service ép owner =
	// chính mình, nên không đọc được via của người khác dù gọi thẳng API.
	ListScrapeVias(ctx context.Context, arg ListScrapeViasParams) ([]ListScrapeViasRow, error)
	ListSkippedLogs(ctx context.Context, arg ListSkippedLogsParams) ([]SkippedLog, error)
	// Bài Post đi kèm URL của kênh đã đẻ ra nó. Kênh không có cột tên, nên thứ
	// nhận diện được một kênh trên giao diện vẫn là source_url của nó.
	//
	// LEFT JOIN cả hai bảng kênh chứ không JOIN theo source_type: một bài chỉ
	// gắn được vào ĐÚNG MỘT loại kênh (ck_source_post_origin ở migration 000001
	// ép như vậy), nên COALESCE hai nhánh luôn ra nhiều nhất một giá trị, và bài
	// F1 nhập tay thì cả hai nhánh đều NULL.
	//
	// Nhánh '' cuối cùng là để cột này KHÔNG BAO GIỜ NULL: sqlc suy ra COALESCE là
	// NOT NULL nên sinh ra `string`, quét NULL vào đó là lỗi runtime ngay ở bài F1
	// đầu tiên. Rỗng = không đến từ kênh nào.
	// Sắp xếp động: chỉ có 1 cột thời gian nên chỉ cần chiều. Nhánh CASE toàn
	// NULL khi dir='desc' -> rơi về mặc định mới nhất trước.
	ListSourcePosts(ctx context.Context, arg ListSourcePostsParams) ([]ListSourcePostsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]AppUser, error)
	ListViaUsageLogs(ctx context.Context, arg ListViaUsageLogsParams) ([]ListViaUsageLogsRow, error)
	// Trả kèm nền tảng nguồn + email người tạo để bảng Voice hiển thị và lọc được
	// mà không phải gọi thêm API (prompt.md mục 3, 4, 8).
	// Lọc theo trạng thái NGƯỜI DÙNG THẤY, không phải cột thô: voice còn thiếu điều
	// kiện đăng (chưa chọn author, chưa có hashtag/tiêu đề, audio ngắn hơn mức
	// multime nhận) hiện badge "Chưa đủ điều kiện", nên chọn trạng thái đó phải ra
	// đúng những dòng ấy — và "Nháp"/"Chờ đăng" thì không được lẫn chúng.
	//
	// 'incomplete' KHÔNG phải giá trị có trong cột publish_status: nó là trạng thái
	// suy ra lúc đọc. Thiếu hashtag là việc người dùng chưa điền xong, khác hẳn
	// 'failed' (đã gửi lên multime và bị từ chối), nên không gộp chung.
	// Sắp xếp động: mỗi nhánh CASE chỉ có giá trị khi đúng cột + đúng chiều đang
	// chọn, các nhánh còn lại toàn NULL nên không ảnh hưởng thứ tự. Dòng cuối là
	// mặc định (mới nhất trước) và cũng là nhánh sort=created_at + dir=desc.
	ListVoices(ctx context.Context, arg ListVoicesParams) ([]ListVoicesRow, error)
	ListVoicesBySourcePost(ctx context.Context, sourcePostID *uuid.UUID) ([]Voice, error)
	// Hết quota / bị rate-limit: key vẫn đúng, chỉ cần CHỜ. Không đụng disabled_at.
	MarkLLMAPIKeyCooldown(ctx context.Context, arg MarkLLMAPIKeyCooldownParams) error
	// Key sai / bị thu hồi: chờ bao lâu cũng không tự khỏi, phải có người dán key
	// mới. Tách khỏi cooldown vì hai tình huống này xử lý khác hẳn nhau.
	MarkLLMAPIKeyDisabled(ctx context.Context, arg MarkLLMAPIKeyDisabledParams) error
	// Lỗi tạm thời (5xx, mạng): chỉ đếm và ghi lý do, không tắt cũng không bắt nghỉ.
	MarkLLMAPIKeyFailure(ctx context.Context, arg MarkLLMAPIKeyFailureParams) error
	// Gọi sau mỗi lần gọi LLM THÀNH CÔNG: xoá sạch dấu vết hỏng hóc cũ. Không reset
	// consecutive_failures ở đây thì một key thỉnh thoảng lỗi sẽ tích dần số đếm
	// qua nhiều ngày rồi bị tắt oan.
	MarkLLMAPIKeyOK(ctx context.Context, id uuid.UUID) error
	// Đóng vòng quét đầu: ghi mốc và nhớ những id đã cố tình bỏ qua.
	//
	// Kênh Breaking không có mốc đồng bộ nên nếu không nhớ, chính những bài này sẽ
	// quay lại ở vòng sau như thể vừa đăng.
	MarkListBreakingBackfilled(ctx context.Context, arg MarkListBreakingBackfilledParams) error
	// Đóng vòng quét đầu. Cột riêng chứ không suy ra từ last_synced_post_id: kênh
	// chưa có bài nào thì mốc đó vẫn NULL sau một vòng quét hoàn toàn hợp lệ.
	MarkListScheduledBackfilled(ctx context.Context, id uuid.UUID) error
	// Nền tảng chặn IP (`bot_block`): đây là lỗi của lối ra mạng.
	//
	//   chưa đủ ngưỡng      -> vẫn active
	//   đủ ngưỡng lần đầu   -> degraded (ra khỏi vòng chọn, còn cứu được bằng tay)
	//   vẫn hỏng tiếp       -> dead
	//
	// KHÔNG có đường tự hồi sinh theo thời gian, khác hẳn via: một IP đã bị Meta/X
	// liệt thì chờ bao lâu cũng vậy. Tự bật lại chỉ tạo ra một vòng lặp hỏng đều
	// đặn và làm nhiễu số liệu của các proxy còn tốt.
	MarkScrapeProxyBlocked(ctx context.Context, arg MarkScrapeProxyBlockedParams) (ScrapeProxy, error)
	// Request đi qua proxy này xong mà không bị chặn.
	MarkScrapeProxyUsed(ctx context.Context, id uuid.UUID) error
	// Nền tảng đòi đăng nhập — phiên của via này có vấn đề.
	//
	// Một câu UPDATE lo trọn máy trạng thái, thay vì đọc rồi tính rồi ghi: hai
	// worker cùng gặp lỗi trên một via sẽ chạy hai lượt, và đọc-tính-ghi thì lượt
	// sau ghi đè lượt trước, số đếm đứng yên và via không bao giờ chết.
	//
	//   chưa đủ ngưỡng          -> vẫn active, chỉ tăng số đếm
	//   đủ ngưỡng, lần đầu      -> cooldown, hẹn giờ thử lại
	//   lại hỏng sau cooldown   -> dead (đã cho một cơ hội rồi)
	//
	// Nhận ra "lại hỏng sau cooldown" bằng cooldown_until: cột này chỉ được đặt khi
	// via đã từng đi qua cooldown, và MarkScrapeViaUsed xoá nó khi via sống lại
	// thật. Còn giá trị nghĩa là lần cuối cùng ta cho nó cơ hội, nó vẫn hỏng.
	MarkScrapeViaLoginError(ctx context.Context, arg MarkScrapeViaLoginErrorParams) (ScrapeVia, error)
	// Sau một lượt quét THÀNH CÔNG: trừ hạn mức, xoá sạch dấu vết hỏng hóc cũ.
	//
	// Bộ đếm ngày tự liền ngay tại đây: gặp ngày lệch thì đặt lại về 1 thay vì cộng
	// tiếp vào con số của hôm qua.
	MarkScrapeViaUsed(ctx context.Context, id uuid.UUID) error
	// Business rule #2: publish thành công -> xoá file S3 và set voice_file_url = NULL,
	// chỉ giữ multime_post_url làm nguồn tham chiếu duy nhất.
	// Ảnh bìa tải từ máy cũng bị xoá theo cùng lý do: multime đã giữ bản của nó,
	// bản trong bucket của mình không còn ai đọc nữa. Ảnh lấy từ URL bài gốc không
	// nằm trong bucket nên giữ nguyên link.
	MarkVoicePublished(ctx context.Context, arg MarkVoicePublishedParams) (Voice, error)
	// Lỗi không quy được cho proxy: đếm vào tỉ lệ hỏng của ngày, không đụng trạng thái.
	NoteScrapeProxyError(ctx context.Context, arg NoteScrapeProxyErrorParams) error
	// Lỗi KHÔNG phải của via (bot_block, rate_limit, mạng đứt): ghi lại để đối
	// chiếu, nhưng không đụng tới máy trạng thái.
	//
	// Vì sao tách khỏi câu trên: đánh via chết vì một IP bị chặn là thay nhầm thứ
	// đang hỏng — via vẫn tốt, và ta vừa vứt đi một tài khoản còn dùng được.
	NoteScrapeViaError(ctx context.Context, arg NoteScrapeViaErrorParams) error
	// Bốc 1 quốc gia trong nhóm nói cùng một ngôn ngữ, ưu tiên theo sort_order.
	//
	// Dùng cho kênh bật "Random author": bài đọc bằng tiếng Việt mà đứng tên tài
	// khoản Nhật thì người nghe thấy ngay là sai, nên việc bốc phải bị chặn lại
	// trong đúng nhóm quốc gia của ngôn ngữ đó. Tên quốc gia do
	// domain.CountriesForLanguage đưa xuống.
	//
	// So khớp không phân biệt hoa thường và bỏ khoảng trắng thừa: `country.name`
	// là bản sao từ Strongbody, không phải chuỗi ta tự kiểm soát.
	PickCountryForLanguage(ctx context.Context, names []string) (int64, error)
	RecordAIUsage(ctx context.Context, arg RecordAIUsageParams) error
	ResetScrapeProxyDaily(ctx context.Context) (int64, error)
	// Job hằng ngày. Bộ đếm đã tự liền theo ngày ở MarkScrapeViaUsed, nên câu này
	// chỉ để bảng nhìn đúng trên giao diện trước lượt dùng đầu tiên của ngày mới.
	ResetScrapeViaDailyUsed(ctx context.Context) (int64, error)
	// Job định kỳ: via hết cooldown thì cho thử lại.
	//
	// GIỮ NGUYÊN cooldown_until (không xoá về NULL) vì nó chính là thứ đánh dấu
	// "via này đã được cho một cơ hội" — xem MarkScrapeViaLoginError. Xoá nó ở đây
	// thì via hỏng lại sẽ vào cooldown lần nữa, và lặp mãi không bao giờ chết.
	ReviveScrapeVias(ctx context.Context) (int64, error)
	// Số lượt quét theo GIỜ trong ngày, `days` ngày gần nhất.
	//
	// Biểu đồ này trả lời đúng một câu: lịch quét có bị dồn cục không. Vài trăm
	// kênh quét 1 lần/ngày mà tất cả rơi vào cùng một khung giờ thì nền tảng nhìn
	// thấy một đợt tấn công, còn bảng thống kê lỗi thì chỉ nói "bị chặn" mà không
	// nói vì sao — cột giờ này mới nói ra.
	//
	// `owner` NULL = cả hệ thống (chỉ admin); ngược lại chỉ đếm lượt đi qua via của
	// người đó. Biểu đồ nói về NHỊP QUÉT, và nhịp của cả hệ thống không phải thứ
	// một editor sửa được — họ chỉ rải lại lịch các kênh mình quét.
	ScrapeHourlyLoad(ctx context.Context, arg ScrapeHourlyLoadParams) ([]ScrapeHourlyLoadRow, error)
	// Bật/tắt MỘT key. Người gọi chịu trách nhiệm tắt các key khác TRƯỚC khi bật
	// key này (xem DeactivateOtherAIEngines) — làm ngược lại là đụng
	// uq_ai_engine_active_per_user.
	SetAIEngineActive(ctx context.Context, arg SetAIEngineActiveParams) (AiEngine, error)
	// Ghi lại điều vừa học được về key sau một lần gọi TTS.
	//
	// Chỉ gọi khi lần gọi đó THẬT SỰ nói lên điều gì về key (đọc được audio, hoặc
	// nhà cung cấp từ chối vì key/credit/rate limit). Lỗi mạng và lỗi 5xx của họ
	// không gọi vào đây: ghi 'unknown' đè lên một lần 402 là xoá mất đúng thông
	// tin người dùng cần.
	SetAIEngineStatus(ctx context.Context, arg SetAIEngineStatusParams) error
	SetLastSyncedPostID(ctx context.Context, arg SetLastSyncedPostIDParams) error
	// Ghi lỗi của vòng quét gần nhất lên kênh, hoặc xoá nó khi vòng quét chạy sạch.
	// Người dùng chỉ nhìn thấy bảng kênh, không nhìn thấy log worker.
	SetListBreakingScanError(ctx context.Context, arg SetListBreakingScanErrorParams) error
	// Ghi lỗi của vòng quét gần nhất lên kênh, hoặc xoá nó khi vòng quét chạy sạch.
	// Người dùng chỉ nhìn thấy bảng kênh, không nhìn thấy log worker.
	SetListScheduledScanError(ctx context.Context, arg SetListScheduledScanErrorParams) error
	SetSourcePostStatus(ctx context.Context, arg SetSourcePostStatusParams) (SourcePost, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (AppUser, error)
	// Cập nhật access token sau khi refresh với strongbody.
	SetUserMultimeToken(ctx context.Context, arg SetUserMultimeTokenParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) (AppUser, error)
	// Ghi lại tài khoản đã BỐC lúc đăng. Không dùng UpdateVoice vì đây là worker
	// chốt kết quả của một lần bốc, không phải người dùng sửa metadata.
	SetVoiceAuthor(ctx context.Context, arg SetVoiceAuthorParams) error
	// Chốt lời đọc mới cho 1 Voice rồi đưa lại vào hàng đợi.
	//
	// Đặt luôn publish_status='processing' trong cùng câu lệnh: người dùng bấm
	// "Tạo lại" là thấy dòng voice chuyển sang đang xử lý ngay, không có khoảng
	// giữa mà bảng vẫn hiện voice cũ như chưa có gì xảy ra.
	SetVoiceContent(ctx context.Context, arg SetVoiceContentParams) (Voice, error)
	// Ảnh bìa tải từ máy: image_uploaded = TRUE đánh dấu file nằm trong storage của
	// mình, để sau khi đăng lên multime thì xoá đi cho đỡ tốn dung lượng.
	SetVoiceImage(ctx context.Context, arg SetVoiceImageParams) (Voice, error)
	SetVoicePublishStatus(ctx context.Context, arg SetVoicePublishStatusParams) (Voice, error)
	// Mở 1 vòng quét. Dòng này hiện lên bảng kênh là "Đang quét" cho tới khi
	// FinishScanRun đóng nó lại.
	StartScanRun(ctx context.Context, arg StartScanRunParams) (ScanRun, error)
	// Tổng kết cửa sổ gần đây, hiện ở đầu tab Lịch sử quét. Cần vì một trang 20
	// dòng không trả lời được "kênh này mấy hôm nay có ra gì không" — mà đó mới là
	// câu hỏi người ta mở tab này để hỏi.
	SumScanRunsSince(ctx context.Context, arg SumScanRunsSinceParams) (SumScanRunsSinceRow, error)
	// Đóng dấu thời điểm key thật sự đọc ra audio. Chỉ gọi sau khi TTS thành công:
	// cột này để người dùng biết key nào còn sống, key nào khai xong bỏ đó.
	TouchAIEngineUsed(ctx context.Context, id uuid.UUID) error
	TouchLLMAPISetUsed(ctx context.Context, id uuid.UUID) error
	TouchListBreakingScanned(ctx context.Context, id uuid.UUID) error
	// Ép kênh tới hạn quét NGAY: xoá mốc quét gần nhất.
	//
	// Dùng khi người dùng vừa BẬT LẠI một kênh đang tắt. Kênh tắt thì scheduler bỏ
	// qua mọi vòng, nên nếu không có câu này thì sau khi bật, kênh phải chờ hết một
	// chu kỳ nữa mới chạy — với kênh đặt tần suất 6 tiếng thì đó là 6 tiếng im lặng
	// ngay sau một thao tác mà người dùng nghĩ là "cho chạy lại".
	TouchListScheduledDue(ctx context.Context, id uuid.UUID) error
	TouchListScheduledScanned(ctx context.Context, id uuid.UUID) error
	// api_key_encrypted dùng COALESCE: bỏ trống ô API key ở form nghĩa là "giữ key
	// cũ" — key thật không bao giờ gửi về trình duyệt nên không có gì để gửi lại.
	UpdateAIEngine(ctx context.Context, arg UpdateAIEngineParams) (AiEngine, error)
	// api_key_encrypted dùng COALESCE: bỏ trống ô API key ở form nghĩa là "giữ key
	// cũ" — key thật không bao giờ gửi về trình duyệt nên không có gì để gửi lại.
	//
	// Sửa key cũng là RESET SỨC KHOẺ: người dùng vào đây vì key hỏng, dán key mới
	// mà vẫn còn disabled_at thì router tiếp tục bỏ qua nó và họ không hiểu vì sao.
	UpdateLLMAPIKey(ctx context.Context, arg UpdateLLMAPIKeyParams) (LlmApiKey, error)
	UpdateLLMAPISet(ctx context.Context, arg UpdateLLMAPISetParams) (LlmApiSet, error)
	UpdateListBreaking(ctx context.Context, arg UpdateListBreakingParams) (ListBreaking, error)
	UpdateListScheduled(ctx context.Context, arg UpdateListScheduledParams) (ListScheduled, error)
	UpdatePrompt(ctx context.Context, arg UpdatePromptParams) (Prompt, error)
	// Dán endpoint mới cũng là reset sức khoẻ — cùng lý do với UpdateScrapeVia.
	UpdateScrapeProxy(ctx context.Context, arg UpdateScrapeProxyParams) (ScrapeProxy, error)
	// Sửa via. Dán cookies mới cũng là RESET SỨC KHOẺ: người vào đây là vì via
	// hỏng, dán cookies mới mà vẫn còn `dead` thì bộ chọn tiếp tục bỏ qua nó và họ
	// không hiểu vì sao (đúng bài học của UpdateLLMAPIKey).
	UpdateScrapeVia(ctx context.Context, arg UpdateScrapeViaParams) (ScrapeVia, error)
	UpdateSourcePost(ctx context.Context, arg UpdateSourcePostParams) (SourcePost, error)
	// Worker ghi lại metadata gốc lấy được từ nền tảng để Voice và form đăng bài
	// auto-fill từ đây.
	//
	// `title` là TOÀN BỘ nội dung bài (trừ hashtag) — hệ thống không còn trường mô
	// tả riêng. COALESCE để lần fetch không ra thì giữ nguyên phần đã có.
	UpdateSourcePostMetadata(ctx context.Context, arg UpdateSourcePostMetadataParams) (SourcePost, error)
	// Chọn giới tính KHÔNG còn kéo theo việc bốc tài khoản — việc đó lùi xuống bước
	// đăng. Vì thế author_gender giờ sửa được độc lập với author_id.
	//
	// `reset_author` là hệ quả bắt buộc của điều đó: đổi giới tính hoặc quốc gia mà
	// vẫn giữ tài khoản đã bốc trước đó nghĩa là bài lên multime dưới tên một người
	// không khớp thứ người dùng vừa chọn.
	UpdateVoiceMetadata(ctx context.Context, arg UpdateVoiceMetadataParams) (Voice, error)
	UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) (AppSetting, error)
	UpsertCountry(ctx context.Context, arg UpsertCountryParams) error
	UpsertHashtag(ctx context.Context, arg UpsertHashtagParams) error
	// Đăng nhập bằng strongbody: tạo user nếu chưa có, cập nhật thông tin + token
	// nếu đã có. Role của lần tạo đầu do $5 quyết định, các lần sau KHÔNG ghi đè
	// (admin đã cấp quyền thì giữ nguyên).
	UpsertUserFromSSO(ctx context.Context, arg UpsertUserFromSSOParams) (AppUser, error)
}

var _ Querier = (*Queries)(nil)
