// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan_run.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countScanRuns = `-- name: CountScanRuns :one
SELECT COUNT(*) FROM scan_run r
WHERE ($1::uuid  IS NOT NULL AND r.list_breaking_id  = $1)
   OR ($2::uuid IS NOT NULL AND r.list_scheduled_id = $2)
`

type CountScanRunsParams struct {
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
}

func (q *Queries) CountScanRuns(ctx context.Context, arg CountScanRunsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScanRuns, arg.ListBreakingID, arg.ListScheduledID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteScanRunsBefore = `-- name: DeleteScanRunsBefore :execrows
DELETE FROM scan_run WHERE started_at < $1
`

func (q *Queries) DeleteScanRunsBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScanRunsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStaleScanRuns = `-- name: FailStaleScanRuns :execrows
UPDATE scan_run
SET status      = 'error',
    finished_at = now(),
    error       = COALESCE(error, 'Vòng quét không kết thúc — worker dừng giữa chừng')
WHERE status = 'running' AND started_at < $1
`

// Đóng những vòng quét không bao giờ kết thúc.
//
// Worker bị kill giữa vòng quét thì không ai chạy FinishScanRun, và dòng đó
// nằm lại ở 'running' vĩnh viễn. Trên bảng kênh nó chỉ sai cho tới vòng kế
// tiếp (bảng đọc vòng MỚI NHẤT), nhưng trong tab lịch sử thì nó sai mãi — và
// một dòng "đang quét" từ tuần trước là thứ khiến người đọc mất lòng tin vào
// cả bảng.
func (q *Queries) FailStaleScanRuns(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleScanRuns, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishScanRun = `-- name: FinishScanRun :exec
UPDATE scan_run
SET finished_at    = now(),
    status         = $1,
    fetched        = $2,
    posts_created  = $3,
    voices_created = $4,
    skipped        = $5,
    error          = $6
WHERE id = $7
`

type FinishScanRunParams struct {
	Status        string    `json:"status"`
	Fetched       int32     `json:"fetched"`
	PostsCreated  int32     `json:"posts_created"`
	VoicesCreated int32     `json:"voices_created"`
	Skipped       int32     `json:"skipped"`
	Error         *string   `json:"error"`
	ID            uuid.UUID `json:"id"`
}

// Đóng vòng quét kèm kết quả. Ghi một lần ở cuối chứ không cộng dồn từng bài:
// vòng quét đã có sẵn bộ đếm trong bộ nhớ, và mỗi bài một UPDATE thì một kênh
// scan_limit=200 thành 200 lượt ghi cho một dòng.
func (q *Queries) FinishScanRun(ctx context.Context, arg FinishScanRunParams) error {
	_, err := q.db.Exec(ctx, finishScanRun,
		arg.Status,
		arg.Fetched,
		arg.PostsCreated,
		arg.VoicesCreated,
		arg.Skipped,
		arg.Error,
		arg.ID,
	)
	return err
}

const listScanRuns = `-- name: ListScanRuns :many
SELECT r.id, r.list_breaking_id, r.list_scheduled_id, r.started_at, r.finished_at, r.status, r.trigger_kind, r.triggered_by, r.fetched, r.posts_created, r.voices_created, r.skipped, r.error, u.email AS triggered_by_email
FROM scan_run r
LEFT JOIN app_user u ON u.id = r.triggered_by
WHERE ($1::uuid  IS NOT NULL AND r.list_breaking_id  = $1)
   OR ($2::uuid IS NOT NULL AND r.list_scheduled_id = $2)
ORDER BY r.started_at DESC
LIMIT $4 OFFSET $3
`

type ListScanRunsParams struct {
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	Off             int32      `json:"off"`
	Lim             int32      `json:"lim"`
}

type ListScanRunsRow struct {
	ID               uuid.UUID  `json:"id"`
	ListBreakingID   *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID  *uuid.UUID `json:"list_scheduled_id"`
	StartedAt        time.Time  `json:"started_at"`
	FinishedAt       *time.Time `json:"finished_at"`
	Status           string     `json:"status"`
	TriggerKind      string     `json:"trigger_kind"`
	TriggeredBy      *uuid.UUID `json:"triggered_by"`
	Fetched          int32      `json:"fetched"`
	PostsCreated     int32      `json:"posts_created"`
	VoicesCreated    int32      `json:"voices_created"`
	Skipped          int32      `json:"skipped"`
	Error            *string    `json:"error"`
	TriggeredByEmail *string    `json:"triggered_by_email"`
}

// Lịch sử của ĐÚNG MỘT kênh — service luôn truyền đúng một trong hai id.
func (q *Queries) ListScanRuns(ctx context.Context, arg ListScanRunsParams) ([]ListScanRunsRow, error) {
	rows, err := q.db.Query(ctx, listScanRuns,
		arg.ListBreakingID,
		arg.ListScheduledID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScanRunsRow{}
	for rows.Next() {
		var i ListScanRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ListBreakingID,
			&i.ListScheduledID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.TriggerKind,
			&i.TriggeredBy,
			&i.Fetched,
			&i.PostsCreated,
			&i.VoicesCreated,
			&i.Skipped,
			&i.Error,
			&i.TriggeredByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startScanRun = `-- name: StartScanRun :one
INSERT INTO scan_run (
  list_breaking_id, list_scheduled_id, trigger_kind, triggered_by
) VALUES (
  $1, $2,
  $3, $4
)
RETURNING id, list_breaking_id, list_scheduled_id, started_at, finished_at, status, trigger_kind, triggered_by, fetched, posts_created, voices_created, skipped, error
`

type StartScanRunParams struct {
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	TriggerKind     string     `json:"trigger_kind"`
	TriggeredBy     *uuid.UUID `json:"triggered_by"`
}

// Mở 1 vòng quét. Dòng này hiện lên bảng kênh là "Đang quét" cho tới khi
// FinishScanRun đóng nó lại.
func (q *Queries) StartScanRun(ctx context.Context, arg StartScanRunParams) (ScanRun, error) {
	row := q.db.QueryRow(ctx, startScanRun,
		arg.ListBreakingID,
		arg.ListScheduledID,
		arg.TriggerKind,
		arg.TriggeredBy,
	)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.ListBreakingID,
		&i.ListScheduledID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.TriggerKind,
		&i.TriggeredBy,
		&i.Fetched,
		&i.PostsCreated,
		&i.VoicesCreated,
		&i.Skipped,
		&i.Error,
	)
	return i, err
}

const sumScanRunsSince = `-- name: SumScanRunsSince :one
SELECT COUNT(*)::bigint                        AS runs,
       COALESCE(SUM(r.posts_created), 0)::bigint  AS posts_created,
       COALESCE(SUM(r.voices_created), 0)::bigint AS voices_created,
       COUNT(*) FILTER (WHERE r.status = 'error')::bigint AS failed
FROM scan_run r
WHERE (($1::uuid  IS NOT NULL AND r.list_breaking_id  = $1)
    OR ($2::uuid IS NOT NULL AND r.list_scheduled_id = $2))
  AND r.started_at >= $3
`

type SumScanRunsSinceParams struct {
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	Since           time.Time  `json:"since"`
}

type SumScanRunsSinceRow struct {
	Runs          int64 `json:"runs"`
	PostsCreated  int64 `json:"posts_created"`
	VoicesCreated int64 `json:"voices_created"`
	Failed        int64 `json:"failed"`
}

// Tổng kết cửa sổ gần đây, hiện ở đầu tab Lịch sử quét. Cần vì một trang 20
// dòng không trả lời được "kênh này mấy hôm nay có ra gì không" — mà đó mới là
// câu hỏi người ta mở tab này để hỏi.
func (q *Queries) SumScanRunsSince(ctx context.Context, arg SumScanRunsSinceParams) (SumScanRunsSinceRow, error) {
	row := q.db.QueryRow(ctx, sumScanRunsSince, arg.ListBreakingID, arg.ListScheduledID, arg.Since)
	var i SumScanRunsSinceRow
	err := row.Scan(
		&i.Runs,
		&i.PostsCreated,
		&i.VoicesCreated,
		&i.Failed,
	)
	return i, err
}
