// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrape_via.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimScrapeVia = `-- name: ClaimScrapeVia :one
UPDATE scrape_via
SET last_used_at = now()
WHERE id = (
  -- Bí danh ` + "`" + `c` + "`" + `: không có nó thì ` + "`" + `platform` + "`" + ` trong subquery vừa trỏ tới cột của
  -- bảng đang UPDATE vừa trỏ tới cột của chính subquery, và Postgres từ chối.
  SELECT c.id FROM scrape_via c
  WHERE c.platform = $1
    AND c.status = 'active'
    AND (c.daily_used_date < CURRENT_DATE OR c.daily_used < c.daily_quota)
  ORDER BY c.last_used_at ASC NULLS FIRST, c.id
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, platform, label, cookies_encrypted, status, consecutive_login_errors, cooldown_until, daily_quota, daily_used, daily_used_date, last_used_at, last_error_at, last_error, created_by, created_at, updated_at
`

// Nhận via cho MỘT lượt quét: nghỉ lâu nhất trước (round-robin theo thời gian
// nghỉ), trong nhóm còn khoẻ và còn hạn mức ngày.
//
// CHỌN VÀ ĐÁNH DẤU TRONG MỘT CÂU, không phải SELECT rồi UPDATE. Hai worker quét
// song song mà đọc rồi mới ghi thì cả hai cùng thấy một via "nghỉ lâu nhất" và
// cùng dùng nó — vòng xoay đứng im, một via gánh hết tải, đúng thứ cần tránh
// nhất khi tài sản quý là số via còn sống. Một câu UPDATE thì Postgres tự khoá
// dòng, worker thứ hai thấy last_used_at đã đổi và nhận via kế tiếp.
//
// SKIP LOCKED ở subquery: worker thứ hai nhảy sang via kế thay vì xếp hàng chờ
// — có vài trăm kênh cần quét thì chờ nhau là tự dồn burst về cuối hàng.
//
// Chỉ đặt last_used_at ở đây, KHÔNG trừ hạn mức: hạn mức trừ khi lượt quét
// thành công (xem MarkScrapeViaUsed). Một request bị proxy làm hỏng không phải
// lỗi của via và không đáng lấy mất một suất của nó.
//
// `daily_used_date < CURRENT_DATE` cũng được coi là CÒN hạn mức: bộ đếm của
// ngày hôm qua không phải hạn mức của hôm nay. Nhờ vậy việc reset tự liền ngay
// cả khi job cron lỡ nhịp.
func (q *Queries) ClaimScrapeVia(ctx context.Context, platform string) (ScrapeVia, error) {
	row := q.db.QueryRow(ctx, claimScrapeVia, platform)
	var i ScrapeVia
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Label,
		&i.CookiesEncrypted,
		&i.Status,
		&i.ConsecutiveLoginErrors,
		&i.CooldownUntil,
		&i.DailyQuota,
		&i.DailyUsed,
		&i.DailyUsedDate,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countScrapeViasByStatus = `-- name: CountScrapeViasByStatus :many
SELECT platform, status, COUNT(*)::bigint AS total
FROM scrape_via
GROUP BY platform, status
`

type CountScrapeViasByStatusRow struct {
	Platform string `json:"platform"`
	Status   string `json:"status"`
	Total    int64  `json:"total"`
}

// Bảng tổng quan trên màn Cài đặt: bao nhiêu via sống/chết theo từng nền tảng.
func (q *Queries) CountScrapeViasByStatus(ctx context.Context) ([]CountScrapeViasByStatusRow, error) {
	rows, err := q.db.Query(ctx, countScrapeViasByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountScrapeViasByStatusRow{}
	for rows.Next() {
		var i CountScrapeViasByStatusRow
		if err := rows.Scan(&i.Platform, &i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createScrapeVia = `-- name: CreateScrapeVia :one

INSERT INTO scrape_via (platform, label, cookies_encrypted, daily_quota, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, platform, label, cookies_encrypted, status, consecutive_login_errors, cooldown_until, daily_quota, daily_used, daily_used_date, last_used_at, last_error_at, last_error, created_by, created_at, updated_at
`

type CreateScrapeViaParams struct {
	Platform         string    `json:"platform"`
	Label            string    `json:"label"`
	CookiesEncrypted string    `json:"cookies_encrypted"`
	DailyQuota       int32     `json:"daily_quota"`
	CreatedBy        uuid.UUID `json:"created_by"`
}

// ---------------------------------------------------------------------------
// Via (phiên đăng nhập dùng để quét trang công khai)
// ---------------------------------------------------------------------------
func (q *Queries) CreateScrapeVia(ctx context.Context, arg CreateScrapeViaParams) (ScrapeVia, error) {
	row := q.db.QueryRow(ctx, createScrapeVia,
		arg.Platform,
		arg.Label,
		arg.CookiesEncrypted,
		arg.DailyQuota,
		arg.CreatedBy,
	)
	var i ScrapeVia
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Label,
		&i.CookiesEncrypted,
		&i.Status,
		&i.ConsecutiveLoginErrors,
		&i.CooldownUntil,
		&i.DailyQuota,
		&i.DailyUsed,
		&i.DailyUsedDate,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScrapeVia = `-- name: DeleteScrapeVia :execrows
DELETE FROM scrape_via WHERE id = $1
`

func (q *Queries) DeleteScrapeVia(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScrapeVia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScrapeVia = `-- name: GetScrapeVia :one
SELECT id, platform, label, cookies_encrypted, status, consecutive_login_errors, cooldown_until, daily_quota, daily_used, daily_used_date, last_used_at, last_error_at, last_error, created_by, created_at, updated_at FROM scrape_via WHERE id = $1
`

func (q *Queries) GetScrapeVia(ctx context.Context, id uuid.UUID) (ScrapeVia, error) {
	row := q.db.QueryRow(ctx, getScrapeVia, id)
	var i ScrapeVia
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Label,
		&i.CookiesEncrypted,
		&i.Status,
		&i.ConsecutiveLoginErrors,
		&i.CooldownUntil,
		&i.DailyQuota,
		&i.DailyUsed,
		&i.DailyUsedDate,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScrapeVias = `-- name: ListScrapeVias :many
SELECT id, platform, label, cookies_encrypted, status, consecutive_login_errors, cooldown_until, daily_quota, daily_used, daily_used_date, last_used_at, last_error_at, last_error, created_by, created_at, updated_at FROM scrape_via
WHERE $1::varchar IS NULL OR platform = $1
ORDER BY platform, label
`

// Bảng quản lý trên màn Cài đặt. Sắp theo nền tảng rồi nhãn để danh sách đứng
// yên giữa các lần tải — sắp theo trạng thái thì dòng nhảy chỗ mỗi lần một via
// vào cooldown, đúng lúc người ta đang nhìn nó.
func (q *Queries) ListScrapeVias(ctx context.Context, platform *string) ([]ScrapeVia, error) {
	rows, err := q.db.Query(ctx, listScrapeVias, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapeVia{}
	for rows.Next() {
		var i ScrapeVia
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Label,
			&i.CookiesEncrypted,
			&i.Status,
			&i.ConsecutiveLoginErrors,
			&i.CooldownUntil,
			&i.DailyQuota,
			&i.DailyUsed,
			&i.DailyUsedDate,
			&i.LastUsedAt,
			&i.LastErrorAt,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScrapeViaLoginError = `-- name: MarkScrapeViaLoginError :one
UPDATE scrape_via
SET consecutive_login_errors = consecutive_login_errors + 1,
    last_error_at            = now(),
    last_error               = $1,
    -- Nhánh ` + "`" + `cooldown_until IS NOT NULL` + "`" + ` đứng TRƯỚC nhánh ngưỡng, và thứ tự đó
    -- là toàn bộ ý nghĩa của bước "chết": via đã đi qua một vòng cooldown rồi
    -- mà vẫn bị đòi đăng nhập thì không cần đếm lại đủ N lần nữa — N lần đầu đã
    -- là bằng chứng, vòng nghỉ là cơ hội, và lần này là câu trả lời.
    --
    -- Đảo hai nhánh thì via hỏng sống thêm N lượt quét sau mỗi lần hồi sinh, và
    -- mỗi lượt đó là một lần đem một phiên đã chết ra trước mặt nền tảng.
    status = CASE
               WHEN cooldown_until IS NOT NULL THEN 'dead'
               WHEN consecutive_login_errors + 1 < $2::int THEN status
               ELSE 'cooldown'
             END,
    cooldown_until = CASE
               WHEN cooldown_until IS NOT NULL THEN cooldown_until
               WHEN consecutive_login_errors + 1 < $2::int THEN cooldown_until
               ELSE now() + $3::interval
             END,
    updated_at = now()
WHERE id = $4
RETURNING id, platform, label, cookies_encrypted, status, consecutive_login_errors, cooldown_until, daily_quota, daily_used, daily_used_date, last_used_at, last_error_at, last_error, created_by, created_at, updated_at
`

type MarkScrapeViaLoginErrorParams struct {
	LastError *string         `json:"last_error"`
	Threshold int32           `json:"threshold"`
	Cooldown  pgtype.Interval `json:"cooldown"`
	ID        uuid.UUID       `json:"id"`
}

// Nền tảng đòi đăng nhập — phiên của via này có vấn đề.
//
// Một câu UPDATE lo trọn máy trạng thái, thay vì đọc rồi tính rồi ghi: hai
// worker cùng gặp lỗi trên một via sẽ chạy hai lượt, và đọc-tính-ghi thì lượt
// sau ghi đè lượt trước, số đếm đứng yên và via không bao giờ chết.
//
//	chưa đủ ngưỡng          -> vẫn active, chỉ tăng số đếm
//	đủ ngưỡng, lần đầu      -> cooldown, hẹn giờ thử lại
//	lại hỏng sau cooldown   -> dead (đã cho một cơ hội rồi)
//
// Nhận ra "lại hỏng sau cooldown" bằng cooldown_until: cột này chỉ được đặt khi
// via đã từng đi qua cooldown, và MarkScrapeViaUsed xoá nó khi via sống lại
// thật. Còn giá trị nghĩa là lần cuối cùng ta cho nó cơ hội, nó vẫn hỏng.
func (q *Queries) MarkScrapeViaLoginError(ctx context.Context, arg MarkScrapeViaLoginErrorParams) (ScrapeVia, error) {
	row := q.db.QueryRow(ctx, markScrapeViaLoginError,
		arg.LastError,
		arg.Threshold,
		arg.Cooldown,
		arg.ID,
	)
	var i ScrapeVia
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Label,
		&i.CookiesEncrypted,
		&i.Status,
		&i.ConsecutiveLoginErrors,
		&i.CooldownUntil,
		&i.DailyQuota,
		&i.DailyUsed,
		&i.DailyUsedDate,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markScrapeViaUsed = `-- name: MarkScrapeViaUsed :exec
UPDATE scrape_via
SET last_used_at = now(),
    daily_used = CASE WHEN daily_used_date < CURRENT_DATE THEN 1 ELSE daily_used + 1 END,
    daily_used_date          = CURRENT_DATE,
    consecutive_login_errors = 0,
    last_error               = NULL,
    updated_at               = now()
WHERE id = $1
`

// Sau một lượt quét THÀNH CÔNG: trừ hạn mức, xoá sạch dấu vết hỏng hóc cũ.
//
// Bộ đếm ngày tự liền ngay tại đây: gặp ngày lệch thì đặt lại về 1 thay vì cộng
// tiếp vào con số của hôm qua.
func (q *Queries) MarkScrapeViaUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markScrapeViaUsed, id)
	return err
}

const noteScrapeViaError = `-- name: NoteScrapeViaError :exec
UPDATE scrape_via
SET last_error_at = now(), last_error = $1, updated_at = now()
WHERE id = $2
`

type NoteScrapeViaErrorParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

// Lỗi KHÔNG phải của via (bot_block, rate_limit, mạng đứt): ghi lại để đối
// chiếu, nhưng không đụng tới máy trạng thái.
//
// Vì sao tách khỏi câu trên: đánh via chết vì một IP bị chặn là thay nhầm thứ
// đang hỏng — via vẫn tốt, và ta vừa vứt đi một tài khoản còn dùng được.
func (q *Queries) NoteScrapeViaError(ctx context.Context, arg NoteScrapeViaErrorParams) error {
	_, err := q.db.Exec(ctx, noteScrapeViaError, arg.LastError, arg.ID)
	return err
}

const resetScrapeViaDailyUsed = `-- name: ResetScrapeViaDailyUsed :execrows
UPDATE scrape_via
SET daily_used = 0, daily_used_date = CURRENT_DATE, updated_at = now()
WHERE daily_used_date < CURRENT_DATE
`

// Job hằng ngày. Bộ đếm đã tự liền theo ngày ở MarkScrapeViaUsed, nên câu này
// chỉ để bảng nhìn đúng trên giao diện trước lượt dùng đầu tiên của ngày mới.
func (q *Queries) ResetScrapeViaDailyUsed(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetScrapeViaDailyUsed)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviveScrapeVias = `-- name: ReviveScrapeVias :execrows
UPDATE scrape_via
SET status = 'active', consecutive_login_errors = 0, updated_at = now()
WHERE status = 'cooldown' AND cooldown_until IS NOT NULL AND cooldown_until <= now()
`

// Job định kỳ: via hết cooldown thì cho thử lại.
//
// GIỮ NGUYÊN cooldown_until (không xoá về NULL) vì nó chính là thứ đánh dấu
// "via này đã được cho một cơ hội" — xem MarkScrapeViaLoginError. Xoá nó ở đây
// thì via hỏng lại sẽ vào cooldown lần nữa, và lặp mãi không bao giờ chết.
func (q *Queries) ReviveScrapeVias(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reviveScrapeVias)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScrapeVia = `-- name: UpdateScrapeVia :one
UPDATE scrape_via
SET label             = COALESCE($1, label),
    daily_quota       = COALESCE($2, daily_quota),
    cookies_encrypted = COALESCE($3, cookies_encrypted),
    status = CASE
               WHEN $3 IS NOT NULL THEN 'active'
               ELSE COALESCE($4, status)
             END,
    consecutive_login_errors =
      CASE WHEN $3 IS NULL THEN consecutive_login_errors ELSE 0 END,
    cooldown_until =
      CASE WHEN $3 IS NULL THEN cooldown_until ELSE NULL END,
    last_error =
      CASE WHEN $3 IS NULL THEN last_error ELSE NULL END,
    updated_at = now()
WHERE id = $5
RETURNING id, platform, label, cookies_encrypted, status, consecutive_login_errors, cooldown_until, daily_quota, daily_used, daily_used_date, last_used_at, last_error_at, last_error, created_by, created_at, updated_at
`

type UpdateScrapeViaParams struct {
	Label            *string   `json:"label"`
	DailyQuota       *int32    `json:"daily_quota"`
	CookiesEncrypted *string   `json:"cookies_encrypted"`
	Status           *string   `json:"status"`
	ID               uuid.UUID `json:"id"`
}

// Sửa via. Dán cookies mới cũng là RESET SỨC KHOẺ: người vào đây là vì via
// hỏng, dán cookies mới mà vẫn còn `dead` thì bộ chọn tiếp tục bỏ qua nó và họ
// không hiểu vì sao (đúng bài học của UpdateLLMAPIKey).
func (q *Queries) UpdateScrapeVia(ctx context.Context, arg UpdateScrapeViaParams) (ScrapeVia, error) {
	row := q.db.QueryRow(ctx, updateScrapeVia,
		arg.Label,
		arg.DailyQuota,
		arg.CookiesEncrypted,
		arg.Status,
		arg.ID,
	)
	var i ScrapeVia
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Label,
		&i.CookiesEncrypted,
		&i.Status,
		&i.ConsecutiveLoginErrors,
		&i.CooldownUntil,
		&i.DailyQuota,
		&i.DailyUsed,
		&i.DailyUsedDate,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
