// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrape_proxy.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimScrapeProxy = `-- name: ClaimScrapeProxy :one
UPDATE scrape_proxy
SET last_used_at = now()
WHERE id = (
  -- Bí danh ` + "`" + `c` + "`" + ` vì cùng lý do với ClaimScrapeVia.
  SELECT c.id FROM scrape_proxy c
  WHERE c.status = 'active'
    AND (c.platform IS NULL OR c.platform = $1)
  ORDER BY (c.platform IS NULL), c.last_used_at ASC NULLS FIRST, c.id
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, label, platform, endpoint_encrypted, endpoint_masked, kind, status, consecutive_blocks, errors_today, used_today, today, last_used_at, last_error_at, last_error, created_by, created_at, updated_at
`

// Nhận proxy cho MỘT request: nghỉ lâu nhất trước. Chọn-và-đánh-dấu trong một
// câu, cùng lý do với ClaimScrapeVia.
//
// `platform IS NULL` lọt vào kết quả: đó là gateway residential dùng chung cho
// mọi nền tảng. Proxy gán đích danh nền tảng được ưu tiên hơn (ORDER BY đẩy
// `platform IS NULL` xuống sau) vì gán đích danh là có chủ đích.
//
// Chỉ lấy `active`: `degraded` và `dead` đứng ngoài vòng chọn cho tới khi có
// người bật lại tay. Xem MarkScrapeProxyBlocked.
func (q *Queries) ClaimScrapeProxy(ctx context.Context, platform *string) (ScrapeProxy, error) {
	row := q.db.QueryRow(ctx, claimScrapeProxy, platform)
	var i ScrapeProxy
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Platform,
		&i.EndpointEncrypted,
		&i.EndpointMasked,
		&i.Kind,
		&i.Status,
		&i.ConsecutiveBlocks,
		&i.ErrorsToday,
		&i.UsedToday,
		&i.Today,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countViaUsageLogs = `-- name: CountViaUsageLogs :one
SELECT COUNT(*) FROM via_usage_log l
WHERE ($1::uuid IS NULL OR l.via_id = $1)
  AND ($2::varchar IS NULL OR l.platform = $2)
`

type CountViaUsageLogsParams struct {
	ViaID    *uuid.UUID `json:"via_id"`
	Platform *string    `json:"platform"`
}

func (q *Queries) CountViaUsageLogs(ctx context.Context, arg CountViaUsageLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countViaUsageLogs, arg.ViaID, arg.Platform)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScrapeProxy = `-- name: CreateScrapeProxy :one

INSERT INTO scrape_proxy (label, platform, endpoint_encrypted, endpoint_masked, kind, created_by)
VALUES ($1, $6, $2, $3, $4, $5)
RETURNING id, label, platform, endpoint_encrypted, endpoint_masked, kind, status, consecutive_blocks, errors_today, used_today, today, last_used_at, last_error_at, last_error, created_by, created_at, updated_at
`

type CreateScrapeProxyParams struct {
	Label             string    `json:"label"`
	EndpointEncrypted string    `json:"endpoint_encrypted"`
	EndpointMasked    string    `json:"endpoint_masked"`
	Kind              string    `json:"kind"`
	CreatedBy         uuid.UUID `json:"created_by"`
	Platform          *string   `json:"platform"`
}

// ---------------------------------------------------------------------------
// Proxy (lối ra mạng cho các request quét)
// ---------------------------------------------------------------------------
func (q *Queries) CreateScrapeProxy(ctx context.Context, arg CreateScrapeProxyParams) (ScrapeProxy, error) {
	row := q.db.QueryRow(ctx, createScrapeProxy,
		arg.Label,
		arg.EndpointEncrypted,
		arg.EndpointMasked,
		arg.Kind,
		arg.CreatedBy,
		arg.Platform,
	)
	var i ScrapeProxy
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Platform,
		&i.EndpointEncrypted,
		&i.EndpointMasked,
		&i.Kind,
		&i.Status,
		&i.ConsecutiveBlocks,
		&i.ErrorsToday,
		&i.UsedToday,
		&i.Today,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createViaUsageLog = `-- name: CreateViaUsageLog :exec

INSERT INTO via_usage_log (
  via_id, proxy_id, list_breaking_id, list_scheduled_id,
  platform, result, posts_found, detail
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
)
`

type CreateViaUsageLogParams struct {
	ViaID           uuid.UUID  `json:"via_id"`
	ProxyID         *uuid.UUID `json:"proxy_id"`
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	Platform        string     `json:"platform"`
	Result          string     `json:"result"`
	PostsFound      int32      `json:"posts_found"`
	Detail          *string    `json:"detail"`
}

// ---------------------------------------------------------------------------
// via_usage_log
// ---------------------------------------------------------------------------
func (q *Queries) CreateViaUsageLog(ctx context.Context, arg CreateViaUsageLogParams) error {
	_, err := q.db.Exec(ctx, createViaUsageLog,
		arg.ViaID,
		arg.ProxyID,
		arg.ListBreakingID,
		arg.ListScheduledID,
		arg.Platform,
		arg.Result,
		arg.PostsFound,
		arg.Detail,
	)
	return err
}

const deleteScrapeProxy = `-- name: DeleteScrapeProxy :execrows
DELETE FROM scrape_proxy WHERE id = $1
`

func (q *Queries) DeleteScrapeProxy(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScrapeProxy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteViaUsageLogsBefore = `-- name: DeleteViaUsageLogsBefore :execrows
DELETE FROM via_usage_log WHERE created_at < $1
`

func (q *Queries) DeleteViaUsageLogsBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteViaUsageLogsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScrapeProxy = `-- name: GetScrapeProxy :one
SELECT id, label, platform, endpoint_encrypted, endpoint_masked, kind, status, consecutive_blocks, errors_today, used_today, today, last_used_at, last_error_at, last_error, created_by, created_at, updated_at FROM scrape_proxy WHERE id = $1
`

func (q *Queries) GetScrapeProxy(ctx context.Context, id uuid.UUID) (ScrapeProxy, error) {
	row := q.db.QueryRow(ctx, getScrapeProxy, id)
	var i ScrapeProxy
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Platform,
		&i.EndpointEncrypted,
		&i.EndpointMasked,
		&i.Kind,
		&i.Status,
		&i.ConsecutiveBlocks,
		&i.ErrorsToday,
		&i.UsedToday,
		&i.Today,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScrapeProxies = `-- name: ListScrapeProxies :many
SELECT id, label, platform, endpoint_encrypted, endpoint_masked, kind, status, consecutive_blocks, errors_today, used_today, today, last_used_at, last_error_at, last_error, created_by, created_at, updated_at FROM scrape_proxy
WHERE $1::varchar IS NULL
   OR platform IS NULL
   OR platform = $1
ORDER BY label
`

func (q *Queries) ListScrapeProxies(ctx context.Context, platform *string) ([]ScrapeProxy, error) {
	rows, err := q.db.Query(ctx, listScrapeProxies, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapeProxy{}
	for rows.Next() {
		var i ScrapeProxy
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Platform,
			&i.EndpointEncrypted,
			&i.EndpointMasked,
			&i.Kind,
			&i.Status,
			&i.ConsecutiveBlocks,
			&i.ErrorsToday,
			&i.UsedToday,
			&i.Today,
			&i.LastUsedAt,
			&i.LastErrorAt,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViaUsageLogs = `-- name: ListViaUsageLogs :many
SELECT l.id, l.via_id, l.proxy_id, l.list_breaking_id, l.list_scheduled_id, l.platform, l.result, l.posts_found, l.detail, l.created_at, v.label AS via_label, p.label AS proxy_label
FROM via_usage_log l
JOIN scrape_via v ON v.id = l.via_id
LEFT JOIN scrape_proxy p ON p.id = l.proxy_id
WHERE ($1::uuid IS NULL OR l.via_id = $1)
  AND ($2::varchar IS NULL OR l.platform = $2)
ORDER BY l.created_at DESC
LIMIT $4 OFFSET $3
`

type ListViaUsageLogsParams struct {
	ViaID    *uuid.UUID `json:"via_id"`
	Platform *string    `json:"platform"`
	Off      int32      `json:"off"`
	Lim      int32      `json:"lim"`
}

type ListViaUsageLogsRow struct {
	ID              uuid.UUID  `json:"id"`
	ViaID           uuid.UUID  `json:"via_id"`
	ProxyID         *uuid.UUID `json:"proxy_id"`
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	Platform        string     `json:"platform"`
	Result          string     `json:"result"`
	PostsFound      int32      `json:"posts_found"`
	Detail          *string    `json:"detail"`
	CreatedAt       time.Time  `json:"created_at"`
	ViaLabel        string     `json:"via_label"`
	ProxyLabel      *string    `json:"proxy_label"`
}

func (q *Queries) ListViaUsageLogs(ctx context.Context, arg ListViaUsageLogsParams) ([]ListViaUsageLogsRow, error) {
	rows, err := q.db.Query(ctx, listViaUsageLogs,
		arg.ViaID,
		arg.Platform,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListViaUsageLogsRow{}
	for rows.Next() {
		var i ListViaUsageLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ViaID,
			&i.ProxyID,
			&i.ListBreakingID,
			&i.ListScheduledID,
			&i.Platform,
			&i.Result,
			&i.PostsFound,
			&i.Detail,
			&i.CreatedAt,
			&i.ViaLabel,
			&i.ProxyLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScrapeProxyBlocked = `-- name: MarkScrapeProxyBlocked :one
UPDATE scrape_proxy
SET consecutive_blocks = consecutive_blocks + 1,
    errors_today = CASE WHEN today < CURRENT_DATE THEN 1 ELSE errors_today + 1 END,
    used_today   = CASE WHEN today < CURRENT_DATE THEN 1 ELSE used_today END,
    today         = CURRENT_DATE,
    last_error_at = now(),
    last_error    = $1,
    status = CASE
               WHEN consecutive_blocks + 1 < $2::int THEN status
               WHEN status = 'degraded' THEN 'dead'
               ELSE 'degraded'
             END,
    updated_at = now()
WHERE id = $3
RETURNING id, label, platform, endpoint_encrypted, endpoint_masked, kind, status, consecutive_blocks, errors_today, used_today, today, last_used_at, last_error_at, last_error, created_by, created_at, updated_at
`

type MarkScrapeProxyBlockedParams struct {
	LastError *string   `json:"last_error"`
	Threshold int32     `json:"threshold"`
	ID        uuid.UUID `json:"id"`
}

// Nền tảng chặn IP (`bot_block`): đây là lỗi của lối ra mạng.
//
//	chưa đủ ngưỡng      -> vẫn active
//	đủ ngưỡng lần đầu   -> degraded (ra khỏi vòng chọn, còn cứu được bằng tay)
//	vẫn hỏng tiếp       -> dead
//
// KHÔNG có đường tự hồi sinh theo thời gian, khác hẳn via: một IP đã bị Meta/X
// liệt thì chờ bao lâu cũng vậy. Tự bật lại chỉ tạo ra một vòng lặp hỏng đều
// đặn và làm nhiễu số liệu của các proxy còn tốt.
func (q *Queries) MarkScrapeProxyBlocked(ctx context.Context, arg MarkScrapeProxyBlockedParams) (ScrapeProxy, error) {
	row := q.db.QueryRow(ctx, markScrapeProxyBlocked, arg.LastError, arg.Threshold, arg.ID)
	var i ScrapeProxy
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Platform,
		&i.EndpointEncrypted,
		&i.EndpointMasked,
		&i.Kind,
		&i.Status,
		&i.ConsecutiveBlocks,
		&i.ErrorsToday,
		&i.UsedToday,
		&i.Today,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markScrapeProxyUsed = `-- name: MarkScrapeProxyUsed :exec
UPDATE scrape_proxy
SET used_today = CASE WHEN today < CURRENT_DATE THEN 1 ELSE used_today + 1 END,
    errors_today = CASE WHEN today < CURRENT_DATE THEN 0 ELSE errors_today END,
    today              = CURRENT_DATE,
    consecutive_blocks = 0,
    updated_at         = now()
WHERE id = $1
`

// Request đi qua proxy này xong mà không bị chặn.
func (q *Queries) MarkScrapeProxyUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markScrapeProxyUsed, id)
	return err
}

const noteScrapeProxyError = `-- name: NoteScrapeProxyError :exec
UPDATE scrape_proxy
SET errors_today = CASE WHEN today < CURRENT_DATE THEN 1 ELSE errors_today + 1 END,
    used_today   = CASE WHEN today < CURRENT_DATE THEN 1 ELSE used_today END,
    today         = CURRENT_DATE,
    last_error_at = now(),
    last_error    = $1,
    updated_at    = now()
WHERE id = $2
`

type NoteScrapeProxyErrorParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

// Lỗi không quy được cho proxy: đếm vào tỉ lệ hỏng của ngày, không đụng trạng thái.
func (q *Queries) NoteScrapeProxyError(ctx context.Context, arg NoteScrapeProxyErrorParams) error {
	_, err := q.db.Exec(ctx, noteScrapeProxyError, arg.LastError, arg.ID)
	return err
}

const resetScrapeProxyDaily = `-- name: ResetScrapeProxyDaily :execrows
UPDATE scrape_proxy
SET errors_today = 0, used_today = 0, today = CURRENT_DATE, updated_at = now()
WHERE today < CURRENT_DATE
`

func (q *Queries) ResetScrapeProxyDaily(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resetScrapeProxyDaily)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrapeHourlyLoad = `-- name: ScrapeHourlyLoad :many
SELECT EXTRACT(HOUR FROM created_at)::int AS hour,
       platform,
       COUNT(*)::bigint AS total,
       COUNT(*) FILTER (WHERE result <> 'success')::bigint AS failed
FROM via_usage_log
WHERE created_at >= now() - ($1::int * interval '1 day')
GROUP BY 1, 2
ORDER BY 1, 2
`

type ScrapeHourlyLoadRow struct {
	Hour     int32  `json:"hour"`
	Platform string `json:"platform"`
	Total    int64  `json:"total"`
	Failed   int64  `json:"failed"`
}

// Số lượt quét theo GIỜ trong ngày, `days` ngày gần nhất.
//
// Biểu đồ này trả lời đúng một câu: lịch quét có bị dồn cục không. Vài trăm
// kênh quét 1 lần/ngày mà tất cả rơi vào cùng một khung giờ thì nền tảng nhìn
// thấy một đợt tấn công, còn bảng thống kê lỗi thì chỉ nói "bị chặn" mà không
// nói vì sao — cột giờ này mới nói ra.
func (q *Queries) ScrapeHourlyLoad(ctx context.Context, days int32) ([]ScrapeHourlyLoadRow, error) {
	rows, err := q.db.Query(ctx, scrapeHourlyLoad, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScrapeHourlyLoadRow{}
	for rows.Next() {
		var i ScrapeHourlyLoadRow
		if err := rows.Scan(
			&i.Hour,
			&i.Platform,
			&i.Total,
			&i.Failed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScrapeProxy = `-- name: UpdateScrapeProxy :one
UPDATE scrape_proxy
SET label              = COALESCE($1, label),
    kind               = COALESCE($2, kind),
    endpoint_encrypted = COALESCE($3, endpoint_encrypted),
    endpoint_masked    = COALESCE($4, endpoint_masked),
    status = CASE
               WHEN $3 IS NOT NULL THEN 'active'
               ELSE COALESCE($5, status)
             END,
    consecutive_blocks =
      CASE WHEN $3 IS NULL THEN consecutive_blocks ELSE 0 END,
    last_error =
      CASE WHEN $3 IS NULL THEN last_error ELSE NULL END,
    updated_at = now()
WHERE id = $6
RETURNING id, label, platform, endpoint_encrypted, endpoint_masked, kind, status, consecutive_blocks, errors_today, used_today, today, last_used_at, last_error_at, last_error, created_by, created_at, updated_at
`

type UpdateScrapeProxyParams struct {
	Label             *string   `json:"label"`
	Kind              *string   `json:"kind"`
	EndpointEncrypted *string   `json:"endpoint_encrypted"`
	EndpointMasked    *string   `json:"endpoint_masked"`
	Status            *string   `json:"status"`
	ID                uuid.UUID `json:"id"`
}

// Dán endpoint mới cũng là reset sức khoẻ — cùng lý do với UpdateScrapeVia.
func (q *Queries) UpdateScrapeProxy(ctx context.Context, arg UpdateScrapeProxyParams) (ScrapeProxy, error) {
	row := q.db.QueryRow(ctx, updateScrapeProxy,
		arg.Label,
		arg.Kind,
		arg.EndpointEncrypted,
		arg.EndpointMasked,
		arg.Status,
		arg.ID,
	)
	var i ScrapeProxy
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Platform,
		&i.EndpointEncrypted,
		&i.EndpointMasked,
		&i.Kind,
		&i.Status,
		&i.ConsecutiveBlocks,
		&i.ErrorsToday,
		&i.UsedToday,
		&i.Today,
		&i.LastUsedAt,
		&i.LastErrorAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
