// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skipped_log.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSkippedLogs = `-- name: CountSkippedLogs :one
SELECT COUNT(*) FROM skipped_log WHERE list_breaking_id = $1
`

func (q *Queries) CountSkippedLogs(ctx context.Context, listBreakingID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSkippedLogs, listBreakingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSkippedLogsSince = `-- name: CountSkippedLogsSince :one
SELECT COUNT(*) FROM skipped_log
WHERE list_breaking_id = $1 AND checked_at >= $2
`

type CountSkippedLogsSinceParams struct {
	ListBreakingID uuid.UUID `json:"list_breaking_id"`
	Since          time.Time `json:"since"`
}

// Tỉ lệ bỏ qua giúp đánh giá regex có quá chặt/quá lỏng hay không.
func (q *Queries) CountSkippedLogsSince(ctx context.Context, arg CountSkippedLogsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSkippedLogsSince, arg.ListBreakingID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSkippedLog = `-- name: CreateSkippedLog :exec
INSERT INTO skipped_log (list_breaking_id, post_id_external, reason, post_url, text_excerpt)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSkippedLogParams struct {
	ListBreakingID uuid.UUID `json:"list_breaking_id"`
	PostIDExternal string    `json:"post_id_external"`
	Reason         string    `json:"reason"`
	PostUrl        *string   `json:"post_url"`
	TextExcerpt    *string   `json:"text_excerpt"`
}

func (q *Queries) CreateSkippedLog(ctx context.Context, arg CreateSkippedLogParams) error {
	_, err := q.db.Exec(ctx, createSkippedLog,
		arg.ListBreakingID,
		arg.PostIDExternal,
		arg.Reason,
		arg.PostUrl,
		arg.TextExcerpt,
	)
	return err
}

const deleteSkippedLogsBefore = `-- name: DeleteSkippedLogsBefore :execrows
DELETE FROM skipped_log WHERE checked_at < $1
`

func (q *Queries) DeleteSkippedLogsBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkippedLogsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSkippedLogs = `-- name: ListSkippedLogs :many
SELECT id, list_breaking_id, post_id_external, reason, checked_at, post_url, text_excerpt FROM skipped_log
WHERE list_breaking_id = $1
ORDER BY checked_at DESC
LIMIT $3 OFFSET $2
`

type ListSkippedLogsParams struct {
	ListBreakingID uuid.UUID `json:"list_breaking_id"`
	Off            int32     `json:"off"`
	Lim            int32     `json:"lim"`
}

func (q *Queries) ListSkippedLogs(ctx context.Context, arg ListSkippedLogsParams) ([]SkippedLog, error) {
	rows, err := q.db.Query(ctx, listSkippedLogs, arg.ListBreakingID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkippedLog{}
	for rows.Next() {
		var i SkippedLog
		if err := rows.Scan(
			&i.ID,
			&i.ListBreakingID,
			&i.PostIDExternal,
			&i.Reason,
			&i.CheckedAt,
			&i.PostUrl,
			&i.TextExcerpt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
