// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source_post.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cascadeVoiceLanguageFromPost = `-- name: CascadeVoiceLanguageFromPost :execrows
UPDATE voice SET language = $1
WHERE source_post_id = $2
  AND voice_file_url IS NULL
  AND language <> $1
`

type CascadeVoiceLanguageFromPostParams struct {
	Language string     `json:"language"`
	PostID   *uuid.UUID `json:"post_id"`
}

// Đổi ngôn ngữ của Bài Post thì các Voice CHƯA có file của bài đó đi theo.
//
// Cùng ranh giới với cascade từ kênh: voice đã ghi xong file là mô tả của một
// file audio có thật, đổi nhãn không đổi được tiếng đã đọc trong file.
func (q *Queries) CascadeVoiceLanguageFromPost(ctx context.Context, arg CascadeVoiceLanguageFromPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, cascadeVoiceLanguageFromPost, arg.Language, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimSourcePostForProcessing = `-- name: ClaimSourcePostForProcessing :one
UPDATE source_post
SET status = 'processing', last_error = NULL
WHERE id = $1 AND status IN ('new', 'failed')
RETURNING id, source_type, list_breaking_id, list_scheduled_id, source_url, platform, content_type, post_id_extracted, extracted_text, collect_mode, prompt_id, language, status, last_error, created_by, created_at, title, hashtags, thumbnail_url, author_name, posted_at
`

// Chỉ 1 worker được xử lý 1 bài tại 1 thời điểm (idempotent khi Asynq retry).
func (q *Queries) ClaimSourcePostForProcessing(ctx context.Context, id uuid.UUID) (SourcePost, error) {
	row := q.db.QueryRow(ctx, claimSourcePostForProcessing, id)
	var i SourcePost
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.ListBreakingID,
		&i.ListScheduledID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.PostIDExtracted,
		&i.ExtractedText,
		&i.CollectMode,
		&i.PromptID,
		&i.Language,
		&i.Status,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Title,
		&i.Hashtags,
		&i.ThumbnailUrl,
		&i.AuthorName,
		&i.PostedAt,
	)
	return i, err
}

const countSourcePosts = `-- name: CountSourcePosts :one
SELECT COUNT(*) FROM source_post sp
WHERE ($1::varchar IS NULL OR sp.source_type = $1)
  AND ($2::varchar       IS NULL OR sp.status       = $2)
  AND ($3::varchar     IS NULL OR sp.platform     = $3)
  AND ($4::varchar IS NULL OR sp.collect_mode = $4)
  AND ($5::varchar     IS NULL OR sp.language     = $5)
  AND ($6::uuid        IS NULL OR sp.created_by        = $6)
  AND ($7::uuid  IS NULL OR sp.list_breaking_id  = $7)
  AND ($8::uuid IS NULL OR sp.list_scheduled_id = $8)
  AND ($9::timestamptz IS NULL OR sp.created_at >= $9)
  AND ($10::timestamptz   IS NULL OR sp.created_at <= $10)
`

type CountSourcePostsParams struct {
	SourceType      *string    `json:"source_type"`
	Status          *string    `json:"status"`
	Platform        *string    `json:"platform"`
	CollectMode     *string    `json:"collect_mode"`
	Language        *string    `json:"language"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	CreatedFrom     *time.Time `json:"created_from"`
	CreatedTo       *time.Time `json:"created_to"`
}

func (q *Queries) CountSourcePosts(ctx context.Context, arg CountSourcePostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSourcePosts,
		arg.SourceType,
		arg.Status,
		arg.Platform,
		arg.CollectMode,
		arg.Language,
		arg.CreatedBy,
		arg.ListBreakingID,
		arg.ListScheduledID,
		arg.CreatedFrom,
		arg.CreatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSourcePost = `-- name: CreateSourcePost :one
INSERT INTO source_post (
  source_type, list_breaking_id, list_scheduled_id, source_url, platform,
  content_type, post_id_extracted, extracted_text, collect_mode, prompt_id,
  language, status, created_by, title, hashtags, thumbnail_url,
  author_name, posted_at
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10, $11, $12,
  $13, $14,
  COALESCE($15::text[], '{}'),
  $16, $17, $18
)
RETURNING id, source_type, list_breaking_id, list_scheduled_id, source_url, platform, content_type, post_id_extracted, extracted_text, collect_mode, prompt_id, language, status, last_error, created_by, created_at, title, hashtags, thumbnail_url, author_name, posted_at
`

type CreateSourcePostParams struct {
	SourceType      string     `json:"source_type"`
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	SourceUrl       string     `json:"source_url"`
	Platform        string     `json:"platform"`
	ContentType     *string    `json:"content_type"`
	PostIDExtracted *string    `json:"post_id_extracted"`
	ExtractedText   *string    `json:"extracted_text"`
	CollectMode     string     `json:"collect_mode"`
	PromptID        *uuid.UUID `json:"prompt_id"`
	Language        string     `json:"language"`
	Status          string     `json:"status"`
	CreatedBy       uuid.UUID  `json:"created_by"`
	Title           *string    `json:"title"`
	Hashtags        []string   `json:"hashtags"`
	ThumbnailUrl    *string    `json:"thumbnail_url"`
	AuthorName      *string    `json:"author_name"`
	PostedAt        *time.Time `json:"posted_at"`
}

func (q *Queries) CreateSourcePost(ctx context.Context, arg CreateSourcePostParams) (SourcePost, error) {
	row := q.db.QueryRow(ctx, createSourcePost,
		arg.SourceType,
		arg.ListBreakingID,
		arg.ListScheduledID,
		arg.SourceUrl,
		arg.Platform,
		arg.ContentType,
		arg.PostIDExtracted,
		arg.ExtractedText,
		arg.CollectMode,
		arg.PromptID,
		arg.Language,
		arg.Status,
		arg.CreatedBy,
		arg.Title,
		arg.Hashtags,
		arg.ThumbnailUrl,
		arg.AuthorName,
		arg.PostedAt,
	)
	var i SourcePost
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.ListBreakingID,
		&i.ListScheduledID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.PostIDExtracted,
		&i.ExtractedText,
		&i.CollectMode,
		&i.PromptID,
		&i.Language,
		&i.Status,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Title,
		&i.Hashtags,
		&i.ThumbnailUrl,
		&i.AuthorName,
		&i.PostedAt,
	)
	return i, err
}

const deleteSourcePost = `-- name: DeleteSourcePost :execrows
DELETE FROM source_post WHERE id = $1
`

func (q *Queries) DeleteSourcePost(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSourcePost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findSourcePostByPostID = `-- name: FindSourcePostByPostID :one
SELECT id, source_type, list_breaking_id, list_scheduled_id, source_url, platform, content_type, post_id_extracted, extracted_text, collect_mode, prompt_id, language, status, last_error, created_by, created_at, title, hashtags, thumbnail_url, author_name, posted_at FROM source_post
WHERE platform = $1 AND post_id_extracted = $2
ORDER BY created_at ASC
LIMIT 1
`

type FindSourcePostByPostIDParams struct {
	Platform        string  `json:"platform"`
	PostIDExtracted *string `json:"post_id_extracted"`
}

// Tra cứu bài trùng theo ID bài đăng trên nền tảng (KHÔNG theo URL): cùng 1
// bài có nhiều dạng URL khác nhau nhưng chỉ 1 id.
// Trả bản CŨ NHẤT để thông báo trùng luôn trỏ về bài gốc.
func (q *Queries) FindSourcePostByPostID(ctx context.Context, arg FindSourcePostByPostIDParams) (SourcePost, error) {
	row := q.db.QueryRow(ctx, findSourcePostByPostID, arg.Platform, arg.PostIDExtracted)
	var i SourcePost
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.ListBreakingID,
		&i.ListScheduledID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.PostIDExtracted,
		&i.ExtractedText,
		&i.CollectMode,
		&i.PromptID,
		&i.Language,
		&i.Status,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Title,
		&i.Hashtags,
		&i.ThumbnailUrl,
		&i.AuthorName,
		&i.PostedAt,
	)
	return i, err
}

const getSourcePost = `-- name: GetSourcePost :one
SELECT id, source_type, list_breaking_id, list_scheduled_id, source_url, platform, content_type, post_id_extracted, extracted_text, collect_mode, prompt_id, language, status, last_error, created_by, created_at, title, hashtags, thumbnail_url, author_name, posted_at FROM source_post WHERE id = $1
`

func (q *Queries) GetSourcePost(ctx context.Context, id uuid.UUID) (SourcePost, error) {
	row := q.db.QueryRow(ctx, getSourcePost, id)
	var i SourcePost
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.ListBreakingID,
		&i.ListScheduledID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.PostIDExtracted,
		&i.ExtractedText,
		&i.CollectMode,
		&i.PromptID,
		&i.Language,
		&i.Status,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Title,
		&i.Hashtags,
		&i.ThumbnailUrl,
		&i.AuthorName,
		&i.PostedAt,
	)
	return i, err
}

const listSourcePosts = `-- name: ListSourcePosts :many
SELECT sp.id, sp.source_type, sp.list_breaking_id, sp.list_scheduled_id, sp.source_url, sp.platform, sp.content_type, sp.post_id_extracted, sp.extracted_text, sp.collect_mode, sp.prompt_id, sp.language, sp.status, sp.last_error, sp.created_by, sp.created_at, sp.title, sp.hashtags, sp.thumbnail_url, sp.author_name, sp.posted_at, u.email AS created_by_email,
       COALESCE(lb.source_url, ls.source_url, '') AS list_source_url
FROM source_post sp
JOIN app_user u ON u.id = sp.created_by
LEFT JOIN list_breaking  lb ON lb.id = sp.list_breaking_id
LEFT JOIN list_scheduled ls ON ls.id = sp.list_scheduled_id
WHERE ($1::varchar IS NULL OR sp.source_type = $1)
  AND ($2::varchar       IS NULL OR sp.status       = $2)
  AND ($3::varchar     IS NULL OR sp.platform     = $3)
  AND ($4::varchar IS NULL OR sp.collect_mode = $4)
  AND ($5::varchar     IS NULL OR sp.language     = $5)
  AND ($6::uuid        IS NULL OR sp.created_by        = $6)
  AND ($7::uuid  IS NULL OR sp.list_breaking_id  = $7)
  AND ($8::uuid IS NULL OR sp.list_scheduled_id = $8)
  AND ($9::timestamptz IS NULL OR sp.created_at >= $9)
  AND ($10::timestamptz   IS NULL OR sp.created_at <= $10)
ORDER BY
  CASE WHEN $11::text = 'asc' THEN sp.created_at END ASC,
  sp.created_at DESC
LIMIT $13 OFFSET $12
`

type ListSourcePostsParams struct {
	SourceType      *string    `json:"source_type"`
	Status          *string    `json:"status"`
	Platform        *string    `json:"platform"`
	CollectMode     *string    `json:"collect_mode"`
	Language        *string    `json:"language"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	CreatedFrom     *time.Time `json:"created_from"`
	CreatedTo       *time.Time `json:"created_to"`
	Dir             string     `json:"dir"`
	Off             int32      `json:"off"`
	Lim             int32      `json:"lim"`
}

type ListSourcePostsRow struct {
	ID              uuid.UUID  `json:"id"`
	SourceType      string     `json:"source_type"`
	ListBreakingID  *uuid.UUID `json:"list_breaking_id"`
	ListScheduledID *uuid.UUID `json:"list_scheduled_id"`
	SourceUrl       string     `json:"source_url"`
	Platform        string     `json:"platform"`
	ContentType     *string    `json:"content_type"`
	PostIDExtracted *string    `json:"post_id_extracted"`
	ExtractedText   *string    `json:"extracted_text"`
	CollectMode     string     `json:"collect_mode"`
	PromptID        *uuid.UUID `json:"prompt_id"`
	Language        string     `json:"language"`
	Status          string     `json:"status"`
	LastError       *string    `json:"last_error"`
	CreatedBy       uuid.UUID  `json:"created_by"`
	CreatedAt       time.Time  `json:"created_at"`
	Title           *string    `json:"title"`
	Hashtags        []string   `json:"hashtags"`
	ThumbnailUrl    *string    `json:"thumbnail_url"`
	AuthorName      *string    `json:"author_name"`
	PostedAt        *time.Time `json:"posted_at"`
	CreatedByEmail  string     `json:"created_by_email"`
	ListSourceUrl   string     `json:"list_source_url"`
}

// Bài Post đi kèm URL của kênh đã đẻ ra nó. Kênh không có cột tên, nên thứ
// nhận diện được một kênh trên giao diện vẫn là source_url của nó.
//
// LEFT JOIN cả hai bảng kênh chứ không JOIN theo source_type: một bài chỉ
// gắn được vào ĐÚNG MỘT loại kênh (ck_source_post_origin ở migration 000001
// ép như vậy), nên COALESCE hai nhánh luôn ra nhiều nhất một giá trị, và bài
// F1 nhập tay thì cả hai nhánh đều NULL.
//
// Nhánh ” cuối cùng là để cột này KHÔNG BAO GIỜ NULL: sqlc suy ra COALESCE là
// NOT NULL nên sinh ra `string`, quét NULL vào đó là lỗi runtime ngay ở bài F1
// đầu tiên. Rỗng = không đến từ kênh nào.
// Sắp xếp động: chỉ có 1 cột thời gian nên chỉ cần chiều. Nhánh CASE toàn
// NULL khi dir='desc' -> rơi về mặc định mới nhất trước.
func (q *Queries) ListSourcePosts(ctx context.Context, arg ListSourcePostsParams) ([]ListSourcePostsRow, error) {
	rows, err := q.db.Query(ctx, listSourcePosts,
		arg.SourceType,
		arg.Status,
		arg.Platform,
		arg.CollectMode,
		arg.Language,
		arg.CreatedBy,
		arg.ListBreakingID,
		arg.ListScheduledID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Dir,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourcePostsRow{}
	for rows.Next() {
		var i ListSourcePostsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.ListBreakingID,
			&i.ListScheduledID,
			&i.SourceUrl,
			&i.Platform,
			&i.ContentType,
			&i.PostIDExtracted,
			&i.ExtractedText,
			&i.CollectMode,
			&i.PromptID,
			&i.Language,
			&i.Status,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Title,
			&i.Hashtags,
			&i.ThumbnailUrl,
			&i.AuthorName,
			&i.PostedAt,
			&i.CreatedByEmail,
			&i.ListSourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSourcePostStatus = `-- name: SetSourcePostStatus :one
UPDATE source_post
SET status = $1, last_error = $2
WHERE id = $3
RETURNING id, source_type, list_breaking_id, list_scheduled_id, source_url, platform, content_type, post_id_extracted, extracted_text, collect_mode, prompt_id, language, status, last_error, created_by, created_at, title, hashtags, thumbnail_url, author_name, posted_at
`

type SetSourcePostStatusParams struct {
	Status    string    `json:"status"`
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetSourcePostStatus(ctx context.Context, arg SetSourcePostStatusParams) (SourcePost, error) {
	row := q.db.QueryRow(ctx, setSourcePostStatus, arg.Status, arg.LastError, arg.ID)
	var i SourcePost
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.ListBreakingID,
		&i.ListScheduledID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.PostIDExtracted,
		&i.ExtractedText,
		&i.CollectMode,
		&i.PromptID,
		&i.Language,
		&i.Status,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Title,
		&i.Hashtags,
		&i.ThumbnailUrl,
		&i.AuthorName,
		&i.PostedAt,
	)
	return i, err
}

const updateSourcePost = `-- name: UpdateSourcePost :one
UPDATE source_post
SET collect_mode   = COALESCE($1, collect_mode),
    prompt_id      = COALESCE($2, prompt_id),
    language       = COALESCE($3, language),
    extracted_text = COALESCE($4, extracted_text)
WHERE id = $5
RETURNING id, source_type, list_breaking_id, list_scheduled_id, source_url, platform, content_type, post_id_extracted, extracted_text, collect_mode, prompt_id, language, status, last_error, created_by, created_at, title, hashtags, thumbnail_url, author_name, posted_at
`

type UpdateSourcePostParams struct {
	CollectMode   *string    `json:"collect_mode"`
	PromptID      *uuid.UUID `json:"prompt_id"`
	Language      *string    `json:"language"`
	ExtractedText *string    `json:"extracted_text"`
	ID            uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateSourcePost(ctx context.Context, arg UpdateSourcePostParams) (SourcePost, error) {
	row := q.db.QueryRow(ctx, updateSourcePost,
		arg.CollectMode,
		arg.PromptID,
		arg.Language,
		arg.ExtractedText,
		arg.ID,
	)
	var i SourcePost
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.ListBreakingID,
		&i.ListScheduledID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.PostIDExtracted,
		&i.ExtractedText,
		&i.CollectMode,
		&i.PromptID,
		&i.Language,
		&i.Status,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Title,
		&i.Hashtags,
		&i.ThumbnailUrl,
		&i.AuthorName,
		&i.PostedAt,
	)
	return i, err
}

const updateSourcePostMetadata = `-- name: UpdateSourcePostMetadata :one
UPDATE source_post
SET title         = COALESCE($1, title),
    hashtags      = COALESCE($2::text[], hashtags),
    thumbnail_url = COALESCE($3, thumbnail_url),
    author_name   = COALESCE($4, author_name),
    posted_at     = COALESCE($5, posted_at),
    content_type  = COALESCE($6, content_type)
WHERE id = $7
RETURNING id, source_type, list_breaking_id, list_scheduled_id, source_url, platform, content_type, post_id_extracted, extracted_text, collect_mode, prompt_id, language, status, last_error, created_by, created_at, title, hashtags, thumbnail_url, author_name, posted_at
`

type UpdateSourcePostMetadataParams struct {
	Title        *string    `json:"title"`
	Hashtags     []string   `json:"hashtags"`
	ThumbnailUrl *string    `json:"thumbnail_url"`
	AuthorName   *string    `json:"author_name"`
	PostedAt     *time.Time `json:"posted_at"`
	ContentType  *string    `json:"content_type"`
	ID           uuid.UUID  `json:"id"`
}

// Worker ghi lại metadata gốc lấy được từ nền tảng để Voice và form đăng bài
// auto-fill từ đây.
//
// `title` là TOÀN BỘ nội dung bài (trừ hashtag) — hệ thống không còn trường mô
// tả riêng. COALESCE để lần fetch không ra thì giữ nguyên phần đã có.
func (q *Queries) UpdateSourcePostMetadata(ctx context.Context, arg UpdateSourcePostMetadataParams) (SourcePost, error) {
	row := q.db.QueryRow(ctx, updateSourcePostMetadata,
		arg.Title,
		arg.Hashtags,
		arg.ThumbnailUrl,
		arg.AuthorName,
		arg.PostedAt,
		arg.ContentType,
		arg.ID,
	)
	var i SourcePost
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.ListBreakingID,
		&i.ListScheduledID,
		&i.SourceUrl,
		&i.Platform,
		&i.ContentType,
		&i.PostIDExtracted,
		&i.ExtractedText,
		&i.CollectMode,
		&i.PromptID,
		&i.Language,
		&i.Status,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Title,
		&i.Hashtags,
		&i.ThumbnailUrl,
		&i.AuthorName,
		&i.PostedAt,
	)
	return i, err
}
