// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countVoices = `-- name: CountVoices :one
SELECT COUNT(*)
FROM voice v
JOIN source_post sp ON sp.id = v.source_post_id
WHERE ($1::varchar IS NULL OR v.publish_status = $1)
  AND ($2::uuid    IS NULL OR v.source_post_id = $2)
  AND ($3::varchar       IS NULL OR sp.platform      = $3)
  AND ($4::varchar       IS NULL OR v.language       = $4)
  AND ($5::uuid        IS NULL OR v.created_by     = $5)
  AND ($6::timestamptz   IS NULL OR v.created_at   >= $6)
  AND ($7::timestamptz     IS NULL OR v.created_at   <= $7)
  AND ($8::timestamptz IS NULL OR v.published_at >= $8)
  AND ($9::timestamptz   IS NULL OR v.published_at <= $9)
`

type CountVoicesParams struct {
	PublishStatus *string    `json:"publish_status"`
	SourcePostID  *uuid.UUID `json:"source_post_id"`
	Platform      *string    `json:"platform"`
	Language      *string    `json:"language"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedFrom   *time.Time `json:"created_from"`
	CreatedTo     *time.Time `json:"created_to"`
	PublishedFrom *time.Time `json:"published_from"`
	PublishedTo   *time.Time `json:"published_to"`
}

func (q *Queries) CountVoices(ctx context.Context, arg CountVoicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVoices,
		arg.PublishStatus,
		arg.SourcePostID,
		arg.Platform,
		arg.Language,
		arg.CreatedBy,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.PublishedFrom,
		arg.PublishedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVoice = `-- name: CreateVoice :one
INSERT INTO voice (
  source_post_id, ai_engine_id, voice_file_url, duration_seconds, description,
  hashtag, language, image_url, publish_status, title, mime_type, size_bytes,
  sample_rate, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, description, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate
`

type CreateVoiceParams struct {
	SourcePostID    uuid.UUID  `json:"source_post_id"`
	AiEngineID      *uuid.UUID `json:"ai_engine_id"`
	VoiceFileUrl    *string    `json:"voice_file_url"`
	DurationSeconds *int32     `json:"duration_seconds"`
	Description     *string    `json:"description"`
	Hashtag         *string    `json:"hashtag"`
	Language        string     `json:"language"`
	ImageUrl        *string    `json:"image_url"`
	PublishStatus   string     `json:"publish_status"`
	Title           *string    `json:"title"`
	MimeType        *string    `json:"mime_type"`
	SizeBytes       *int64     `json:"size_bytes"`
	SampleRate      *int32     `json:"sample_rate"`
	CreatedBy       uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateVoice(ctx context.Context, arg CreateVoiceParams) (Voice, error) {
	row := q.db.QueryRow(ctx, createVoice,
		arg.SourcePostID,
		arg.AiEngineID,
		arg.VoiceFileUrl,
		arg.DurationSeconds,
		arg.Description,
		arg.Hashtag,
		arg.Language,
		arg.ImageUrl,
		arg.PublishStatus,
		arg.Title,
		arg.MimeType,
		arg.SizeBytes,
		arg.SampleRate,
		arg.CreatedBy,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Description,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
	)
	return i, err
}

const deleteVoice = `-- name: DeleteVoice :execrows
DELETE FROM voice WHERE id = $1
`

func (q *Queries) DeleteVoice(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVoice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVoice = `-- name: GetVoice :one
SELECT id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, description, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate FROM voice WHERE id = $1
`

func (q *Queries) GetVoice(ctx context.Context, id uuid.UUID) (Voice, error) {
	row := q.db.QueryRow(ctx, getVoice, id)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Description,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
	)
	return i, err
}

const listVoices = `-- name: ListVoices :many
SELECT v.id, v.source_post_id, v.ai_engine_id, v.voice_file_url, v.duration_seconds, v.description, v.hashtag, v.language, v.image_url, v.publish_status, v.multime_post_url, v.last_error, v.created_by, v.created_at, v.published_at, v.title, v.mime_type, v.size_bytes, v.sample_rate,
       sp.platform    AS platform,
       sp.source_url  AS source_url,
       sp.title       AS source_title,
       u.email        AS created_by_email
FROM voice v
JOIN source_post sp ON sp.id = v.source_post_id
JOIN app_user u     ON u.id = v.created_by
WHERE ($1::varchar IS NULL OR v.publish_status = $1)
  AND ($2::uuid    IS NULL OR v.source_post_id = $2)
  AND ($3::varchar       IS NULL OR sp.platform      = $3)
  AND ($4::varchar       IS NULL OR v.language       = $4)
  AND ($5::uuid        IS NULL OR v.created_by     = $5)
  AND ($6::timestamptz   IS NULL OR v.created_at   >= $6)
  AND ($7::timestamptz     IS NULL OR v.created_at   <= $7)
  AND ($8::timestamptz IS NULL OR v.published_at >= $8)
  AND ($9::timestamptz   IS NULL OR v.published_at <= $9)
ORDER BY v.created_at DESC
LIMIT $11 OFFSET $10
`

type ListVoicesParams struct {
	PublishStatus *string    `json:"publish_status"`
	SourcePostID  *uuid.UUID `json:"source_post_id"`
	Platform      *string    `json:"platform"`
	Language      *string    `json:"language"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedFrom   *time.Time `json:"created_from"`
	CreatedTo     *time.Time `json:"created_to"`
	PublishedFrom *time.Time `json:"published_from"`
	PublishedTo   *time.Time `json:"published_to"`
	Off           int32      `json:"off"`
	Lim           int32      `json:"lim"`
}

type ListVoicesRow struct {
	ID              uuid.UUID  `json:"id"`
	SourcePostID    uuid.UUID  `json:"source_post_id"`
	AiEngineID      *uuid.UUID `json:"ai_engine_id"`
	VoiceFileUrl    *string    `json:"voice_file_url"`
	DurationSeconds *int32     `json:"duration_seconds"`
	Description     *string    `json:"description"`
	Hashtag         *string    `json:"hashtag"`
	Language        string     `json:"language"`
	ImageUrl        *string    `json:"image_url"`
	PublishStatus   string     `json:"publish_status"`
	MultimePostUrl  *string    `json:"multime_post_url"`
	LastError       *string    `json:"last_error"`
	CreatedBy       uuid.UUID  `json:"created_by"`
	CreatedAt       time.Time  `json:"created_at"`
	PublishedAt     *time.Time `json:"published_at"`
	Title           *string    `json:"title"`
	MimeType        *string    `json:"mime_type"`
	SizeBytes       *int64     `json:"size_bytes"`
	SampleRate      *int32     `json:"sample_rate"`
	Platform        string     `json:"platform"`
	SourceUrl       string     `json:"source_url"`
	SourceTitle     *string    `json:"source_title"`
	CreatedByEmail  string     `json:"created_by_email"`
}

// Trả kèm nền tảng nguồn + email người tạo để bảng Voice hiển thị và lọc được
// mà không phải gọi thêm API (prompt.md mục 3, 4, 8).
func (q *Queries) ListVoices(ctx context.Context, arg ListVoicesParams) ([]ListVoicesRow, error) {
	rows, err := q.db.Query(ctx, listVoices,
		arg.PublishStatus,
		arg.SourcePostID,
		arg.Platform,
		arg.Language,
		arg.CreatedBy,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.PublishedFrom,
		arg.PublishedTo,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVoicesRow{}
	for rows.Next() {
		var i ListVoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourcePostID,
			&i.AiEngineID,
			&i.VoiceFileUrl,
			&i.DurationSeconds,
			&i.Description,
			&i.Hashtag,
			&i.Language,
			&i.ImageUrl,
			&i.PublishStatus,
			&i.MultimePostUrl,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Title,
			&i.MimeType,
			&i.SizeBytes,
			&i.SampleRate,
			&i.Platform,
			&i.SourceUrl,
			&i.SourceTitle,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoicesBySourcePost = `-- name: ListVoicesBySourcePost :many
SELECT id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, description, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate FROM voice WHERE source_post_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVoicesBySourcePost(ctx context.Context, sourcePostID uuid.UUID) ([]Voice, error) {
	rows, err := q.db.Query(ctx, listVoicesBySourcePost, sourcePostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voice{}
	for rows.Next() {
		var i Voice
		if err := rows.Scan(
			&i.ID,
			&i.SourcePostID,
			&i.AiEngineID,
			&i.VoiceFileUrl,
			&i.DurationSeconds,
			&i.Description,
			&i.Hashtag,
			&i.Language,
			&i.ImageUrl,
			&i.PublishStatus,
			&i.MultimePostUrl,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Title,
			&i.MimeType,
			&i.SizeBytes,
			&i.SampleRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVoicePublished = `-- name: MarkVoicePublished :one
UPDATE voice
SET publish_status   = 'published',
    multime_post_url = $1,
    voice_file_url   = NULL,
    last_error       = NULL,
    published_at     = now()
WHERE id = $2
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, description, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate
`

type MarkVoicePublishedParams struct {
	MultimePostUrl *string   `json:"multime_post_url"`
	ID             uuid.UUID `json:"id"`
}

// Business rule #2: publish thành công -> xoá file S3 và set voice_file_url = NULL,
// chỉ giữ multime_post_url làm nguồn tham chiếu duy nhất.
func (q *Queries) MarkVoicePublished(ctx context.Context, arg MarkVoicePublishedParams) (Voice, error) {
	row := q.db.QueryRow(ctx, markVoicePublished, arg.MultimePostUrl, arg.ID)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Description,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
	)
	return i, err
}

const setVoicePublishStatus = `-- name: SetVoicePublishStatus :one
UPDATE voice
SET publish_status = $1, last_error = $2
WHERE id = $3
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, description, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate
`

type SetVoicePublishStatusParams struct {
	PublishStatus string    `json:"publish_status"`
	LastError     *string   `json:"last_error"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) SetVoicePublishStatus(ctx context.Context, arg SetVoicePublishStatusParams) (Voice, error) {
	row := q.db.QueryRow(ctx, setVoicePublishStatus, arg.PublishStatus, arg.LastError, arg.ID)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Description,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
	)
	return i, err
}

const updateVoiceMetadata = `-- name: UpdateVoiceMetadata :one
UPDATE voice
SET description = COALESCE($1, description),
    hashtag     = COALESCE($2, hashtag),
    language    = COALESCE($3, language),
    image_url   = COALESCE($4, image_url),
    title       = COALESCE($5, title)
WHERE id = $6
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, description, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate
`

type UpdateVoiceMetadataParams struct {
	Description *string   `json:"description"`
	Hashtag     *string   `json:"hashtag"`
	Language    *string   `json:"language"`
	ImageUrl    *string   `json:"image_url"`
	Title       *string   `json:"title"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateVoiceMetadata(ctx context.Context, arg UpdateVoiceMetadataParams) (Voice, error) {
	row := q.db.QueryRow(ctx, updateVoiceMetadata,
		arg.Description,
		arg.Hashtag,
		arg.Language,
		arg.ImageUrl,
		arg.Title,
		arg.ID,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Description,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
	)
	return i, err
}
