// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimVoiceForProcessing = `-- name: ClaimVoiceForProcessing :one
UPDATE voice
SET publish_status = 'processing', last_error = NULL
WHERE id = $1 AND publish_status IN ('processing', 'failed')
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config
`

// Nhận Voice về để đọc. Chỉ nhận khi voice đang `processing` hoặc đã `failed`:
// Asynq retry lần sau vẫn nhặt lại được, còn voice đã ra file (draft/ready) thì
// không đọc đè lên — muốn đọc lại phải đi qua SetVoiceContent, nơi người dùng
// chốt lại lời đọc. Voice đã publish thì không bao giờ đụng vào.
func (q *Queries) ClaimVoiceForProcessing(ctx context.Context, id uuid.UUID) (Voice, error) {
	row := q.db.QueryRow(ctx, claimVoiceForProcessing, id)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}

const countVoices = `-- name: CountVoices :one
SELECT COUNT(*)
FROM voice v
LEFT JOIN source_post sp ON sp.id = v.source_post_id
WHERE ($1::varchar IS NULL
       OR CASE
            WHEN v.publish_status IN ('draft', 'ready')
             AND (v.author_id IS NULL OR v.author_id <= 0
                  OR COALESCE(btrim(v.hashtag), '') = ''
                  OR COALESCE(btrim(v.title), '') = ''
                  OR (v.duration_seconds IS NOT NULL
                      AND v.duration_seconds < $2::int))
            THEN 'incomplete'
            ELSE v.publish_status
          END = $1)
  AND ($3::uuid    IS NULL OR v.source_post_id = $3)
  AND ($4::varchar       IS NULL OR sp.platform      = $4)
  AND ($5::varchar       IS NULL OR v.language       = $5)
  AND ($6::uuid        IS NULL OR v.created_by     = $6)
  AND ($7::timestamptz   IS NULL OR v.created_at   >= $7)
  AND ($8::timestamptz     IS NULL OR v.created_at   <= $8)
  AND ($9::timestamptz IS NULL OR v.published_at >= $9)
  AND ($10::timestamptz   IS NULL OR v.published_at <= $10)
`

type CountVoicesParams struct {
	PublishStatus *string    `json:"publish_status"`
	MinDuration   int32      `json:"min_duration"`
	SourcePostID  *uuid.UUID `json:"source_post_id"`
	Platform      *string    `json:"platform"`
	Language      *string    `json:"language"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedFrom   *time.Time `json:"created_from"`
	CreatedTo     *time.Time `json:"created_to"`
	PublishedFrom *time.Time `json:"published_from"`
	PublishedTo   *time.Time `json:"published_to"`
}

// Lọc theo trạng thái NGƯỜI DÙNG THẤY, không phải cột thô: voice còn thiếu điều
// kiện đăng (chưa chọn author, chưa có hashtag/tiêu đề, audio ngắn hơn mức
// multime nhận) hiện badge "Chưa đủ điều kiện", nên chọn trạng thái đó phải ra
// đúng những dòng ấy — và "Nháp"/"Chờ đăng" thì không được lẫn chúng.
//
// 'incomplete' KHÔNG phải giá trị có trong cột publish_status: nó là trạng thái
// suy ra lúc đọc. Thiếu hashtag là việc người dùng chưa điền xong, khác hẳn
// 'failed' (đã gửi lên multime và bị từ chối), nên không gộp chung.
func (q *Queries) CountVoices(ctx context.Context, arg CountVoicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVoices,
		arg.PublishStatus,
		arg.MinDuration,
		arg.SourcePostID,
		arg.Platform,
		arg.Language,
		arg.CreatedBy,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.PublishedFrom,
		arg.PublishedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTextVoice = `-- name: CreateTextVoice :one
INSERT INTO voice (
  input_text, collect_mode, prompt_id, language, publish_status, title, created_by,
  llm_api_set_id,
  -- Metadata điền sẵn ở form, giống hệt voice tạo từ URL: form tạo voice giờ là
  -- MỘT form cho cả ba hình thức, nên hai đường không được nhận hai bộ trường
  -- khác nhau — lệch một trường là một thứ người dùng điền rồi mà biến mất.
  hashtag, image_url, image_uploaded, no_image,
  author_gender, author_country_id, publish_when_ready, tts_config
) VALUES (
  $1, $2, $3,
  $4, 'processing', $5, $6,
  $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15
)
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config
`

type CreateTextVoiceParams struct {
	InputText        *string    `json:"input_text"`
	CollectMode      *string    `json:"collect_mode"`
	PromptID         *uuid.UUID `json:"prompt_id"`
	Language         string     `json:"language"`
	Title            *string    `json:"title"`
	CreatedBy        uuid.UUID  `json:"created_by"`
	LlmApiSetID      *uuid.UUID `json:"llm_api_set_id"`
	Hashtag          *string    `json:"hashtag"`
	ImageUrl         *string    `json:"image_url"`
	ImageUploaded    bool       `json:"image_uploaded"`
	NoImage          bool       `json:"no_image"`
	AuthorGender     *string    `json:"author_gender"`
	AuthorCountryID  *int64     `json:"author_country_id"`
	PublishWhenReady bool       `json:"publish_when_ready"`
	TtsConfig        []byte     `json:"tts_config"`
}

// Voice gõ tay: không có Bài Post nào đứng sau, nội dung nằm thẳng trên Voice.
// Tạo ở trạng thái `processing` để người dùng thấy ngay dòng voice đang chạy,
// worker điền file + metadata vào đúng dòng đó (FinishVoice).
func (q *Queries) CreateTextVoice(ctx context.Context, arg CreateTextVoiceParams) (Voice, error) {
	row := q.db.QueryRow(ctx, createTextVoice,
		arg.InputText,
		arg.CollectMode,
		arg.PromptID,
		arg.Language,
		arg.Title,
		arg.CreatedBy,
		arg.LlmApiSetID,
		arg.Hashtag,
		arg.ImageUrl,
		arg.ImageUploaded,
		arg.NoImage,
		arg.AuthorGender,
		arg.AuthorCountryID,
		arg.PublishWhenReady,
		arg.TtsConfig,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}

const createVoice = `-- name: CreateVoice :one
INSERT INTO voice (
  source_post_id, ai_engine_id, voice_file_url, duration_seconds,
  hashtag, language, image_url, publish_status, title, mime_type, size_bytes,
  sample_rate, created_by,
  author_id, author_email, author_gender,
  image_uploaded, no_image, publish_when_ready, llm_api_set_id, author_country_id,
  spoken_text, tts_config
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
  $14, $15, $16,
  $17, $18, $19,
  $20, $21,
  $22, $23
)
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config
`

type CreateVoiceParams struct {
	SourcePostID     *uuid.UUID `json:"source_post_id"`
	AiEngineID       *uuid.UUID `json:"ai_engine_id"`
	VoiceFileUrl     *string    `json:"voice_file_url"`
	DurationSeconds  *int32     `json:"duration_seconds"`
	Hashtag          *string    `json:"hashtag"`
	Language         string     `json:"language"`
	ImageUrl         *string    `json:"image_url"`
	PublishStatus    string     `json:"publish_status"`
	Title            *string    `json:"title"`
	MimeType         *string    `json:"mime_type"`
	SizeBytes        *int64     `json:"size_bytes"`
	SampleRate       *int32     `json:"sample_rate"`
	CreatedBy        uuid.UUID  `json:"created_by"`
	AuthorID         *int64     `json:"author_id"`
	AuthorEmail      *string    `json:"author_email"`
	AuthorGender     *string    `json:"author_gender"`
	ImageUploaded    bool       `json:"image_uploaded"`
	NoImage          bool       `json:"no_image"`
	PublishWhenReady bool       `json:"publish_when_ready"`
	LlmApiSetID      *uuid.UUID `json:"llm_api_set_id"`
	AuthorCountryID  *int64     `json:"author_country_id"`
	SpokenText       *string    `json:"spoken_text"`
	TtsConfig        []byte     `json:"tts_config"`
}

// Metadata người dùng điền sẵn ở màn tạo Voice đi vào ngay từ đây (title,
// hashtag, author, ảnh): worker sau đó chỉ ĐIỀN VÀO CHỖ TRỐNG chứ không ghi đè,
// nên giá trị người dùng gõ luôn thắng giá trị lấy từ bài gốc.
func (q *Queries) CreateVoice(ctx context.Context, arg CreateVoiceParams) (Voice, error) {
	row := q.db.QueryRow(ctx, createVoice,
		arg.SourcePostID,
		arg.AiEngineID,
		arg.VoiceFileUrl,
		arg.DurationSeconds,
		arg.Hashtag,
		arg.Language,
		arg.ImageUrl,
		arg.PublishStatus,
		arg.Title,
		arg.MimeType,
		arg.SizeBytes,
		arg.SampleRate,
		arg.CreatedBy,
		arg.AuthorID,
		arg.AuthorEmail,
		arg.AuthorGender,
		arg.ImageUploaded,
		arg.NoImage,
		arg.PublishWhenReady,
		arg.LlmApiSetID,
		arg.AuthorCountryID,
		arg.SpokenText,
		arg.TtsConfig,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}

const deleteVoice = `-- name: DeleteVoice :execrows
DELETE FROM voice WHERE id = $1
`

func (q *Queries) DeleteVoice(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVoice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishVoice = `-- name: FinishVoice :one
UPDATE voice
SET ai_engine_id     = $1,
    voice_file_url   = $2,
    duration_seconds = $3,
    title            = COALESCE($4, title),
    hashtag          = COALESCE($5, hashtag),
    image_url        = COALESCE($6, image_url),
    language         = $7,
    mime_type        = $8,
    size_bytes       = $9,
    sample_rate      = $10,
    -- Model THẬT đã viết lại nội dung. COALESCE vì mode B không qua LLM: ghi
    -- thẳng NULL sẽ xoá mất model của lần chạy trước trên chính voice đó.
    llm_model_used   = COALESCE($11, llm_model_used),
    -- Đoạn chữ TTS vừa đọc. KHÔNG dùng COALESCE: đây là kết quả của đúng lần
    -- chạy này, giữ lại giá trị cũ nghĩa là mô tả sai file audio vừa ghi đè.
    spoken_text      = $12,
    publish_status   = 'draft',
    last_error       = NULL
WHERE id = $13
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config
`

type FinishVoiceParams struct {
	AiEngineID      *uuid.UUID `json:"ai_engine_id"`
	VoiceFileUrl    *string    `json:"voice_file_url"`
	DurationSeconds *int32     `json:"duration_seconds"`
	Title           *string    `json:"title"`
	Hashtag         *string    `json:"hashtag"`
	ImageUrl        *string    `json:"image_url"`
	Language        string     `json:"language"`
	MimeType        *string    `json:"mime_type"`
	SizeBytes       *int64     `json:"size_bytes"`
	SampleRate      *int32     `json:"sample_rate"`
	LlmModelUsed    *string    `json:"llm_model_used"`
	SpokenText      *string    `json:"spoken_text"`
	ID              uuid.UUID  `json:"id"`
}

// Worker điền kết quả vào record `processing` đã tạo sẵn lúc enqueue.
// Metadata dùng COALESCE: fetch không ra tiêu đề thì giữ nguyên phần đã điền
// sẵn từ Bài Post, không xoá trắng.
func (q *Queries) FinishVoice(ctx context.Context, arg FinishVoiceParams) (Voice, error) {
	row := q.db.QueryRow(ctx, finishVoice,
		arg.AiEngineID,
		arg.VoiceFileUrl,
		arg.DurationSeconds,
		arg.Title,
		arg.Hashtag,
		arg.ImageUrl,
		arg.Language,
		arg.MimeType,
		arg.SizeBytes,
		arg.SampleRate,
		arg.LlmModelUsed,
		arg.SpokenText,
		arg.ID,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}

const getVoice = `-- name: GetVoice :one
SELECT id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config FROM voice WHERE id = $1
`

func (q *Queries) GetVoice(ctx context.Context, id uuid.UUID) (Voice, error) {
	row := q.db.QueryRow(ctx, getVoice, id)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}

const lastUsedPromptAndSet = `-- name: LastUsedPromptAndSet :one
SELECT
  (SELECT p.prompt_id FROM voice p
    WHERE p.created_by = $1::uuid AND p.prompt_id IS NOT NULL
    ORDER BY p.created_at DESC LIMIT 1) AS prompt_id,
  (SELECT k.llm_api_set_id FROM voice k
    WHERE k.created_by = $1::uuid AND k.llm_api_set_id IS NOT NULL
    ORDER BY k.created_at DESC LIMIT 1) AS llm_api_set_id
`

type LastUsedPromptAndSetRow struct {
	PromptID    *uuid.UUID `json:"prompt_id"`
	LlmApiSetID *uuid.UUID `json:"llm_api_set_id"`
}

// Prompt mẫu + Bộ API mà CHÍNH người này dùng gần đây nhất ở hình thức C.
//
// Để form tạo voice chọn sẵn thay vì bắt chọn lại mỗi lần: gần như ai cũng chạy
// đi chạy lại cùng một prompt, và hai ô bắt buộc phải tự tay chọn ở mỗi lần tạo
// là hai lần bấm thừa cộng một lần quên.
//
// Hai cột lấy ĐỘC LẬP, mỗi cột từ voice gần nhất có giá trị: chúng được chọn
// riêng, nên voice gần nhất có prompt chưa chắc là voice gần nhất có bộ API.
func (q *Queries) LastUsedPromptAndSet(ctx context.Context, userID uuid.UUID) (LastUsedPromptAndSetRow, error) {
	row := q.db.QueryRow(ctx, lastUsedPromptAndSet, userID)
	var i LastUsedPromptAndSetRow
	err := row.Scan(&i.PromptID, &i.LlmApiSetID)
	return i, err
}

const listVoices = `-- name: ListVoices :many
SELECT v.id, v.source_post_id, v.ai_engine_id, v.voice_file_url, v.duration_seconds, v.hashtag, v.language, v.image_url, v.publish_status, v.multime_post_url, v.last_error, v.created_by, v.created_at, v.published_at, v.title, v.mime_type, v.size_bytes, v.sample_rate, v.input_text, v.collect_mode, v.prompt_id, v.author_id, v.author_email, v.image_uploaded, v.author_gender, v.publish_when_ready, v.no_image, v.llm_api_set_id, v.llm_model_used, v.author_country_id, v.spoken_text, v.tts_config,
       sp.platform     AS platform,
       sp.source_url   AS source_url,
       sp.title        AS source_title,
       sp.collect_mode AS source_collect_mode,
       sp.prompt_id    AS source_prompt_id,
       sp.extracted_text AS source_extracted_text,
       u.email         AS created_by_email
FROM voice v
LEFT JOIN source_post sp ON sp.id = v.source_post_id
JOIN app_user u     ON u.id = v.created_by
WHERE ($1::varchar IS NULL
       OR CASE
            WHEN v.publish_status IN ('draft', 'ready')
             AND (v.author_id IS NULL OR v.author_id <= 0
                  OR COALESCE(btrim(v.hashtag), '') = ''
                  OR COALESCE(btrim(v.title), '') = ''
                  OR (v.duration_seconds IS NOT NULL
                      AND v.duration_seconds < $2::int))
            THEN 'incomplete'
            ELSE v.publish_status
          END = $1)
  AND ($3::uuid    IS NULL OR v.source_post_id = $3)
  AND ($4::varchar       IS NULL OR sp.platform      = $4)
  AND ($5::varchar       IS NULL OR v.language       = $5)
  AND ($6::uuid        IS NULL OR v.created_by     = $6)
  AND ($7::timestamptz   IS NULL OR v.created_at   >= $7)
  AND ($8::timestamptz     IS NULL OR v.created_at   <= $8)
  AND ($9::timestamptz IS NULL OR v.published_at >= $9)
  AND ($10::timestamptz   IS NULL OR v.published_at <= $10)
ORDER BY
  CASE WHEN $11::text = 'published_at' AND $12::text = 'asc'
       THEN v.published_at END ASC NULLS LAST,
  CASE WHEN $11::text = 'published_at' AND $12::text = 'desc'
       THEN v.published_at END DESC NULLS LAST,
  CASE WHEN $12::text = 'asc' AND $11::text <> 'published_at'
       THEN v.created_at END ASC,
  v.created_at DESC
LIMIT $14 OFFSET $13
`

type ListVoicesParams struct {
	PublishStatus *string    `json:"publish_status"`
	MinDuration   int32      `json:"min_duration"`
	SourcePostID  *uuid.UUID `json:"source_post_id"`
	Platform      *string    `json:"platform"`
	Language      *string    `json:"language"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedFrom   *time.Time `json:"created_from"`
	CreatedTo     *time.Time `json:"created_to"`
	PublishedFrom *time.Time `json:"published_from"`
	PublishedTo   *time.Time `json:"published_to"`
	Sort          string     `json:"sort"`
	Dir           string     `json:"dir"`
	Off           int32      `json:"off"`
	Lim           int32      `json:"lim"`
}

type ListVoicesRow struct {
	ID                  uuid.UUID  `json:"id"`
	SourcePostID        *uuid.UUID `json:"source_post_id"`
	AiEngineID          *uuid.UUID `json:"ai_engine_id"`
	VoiceFileUrl        *string    `json:"voice_file_url"`
	DurationSeconds     *int32     `json:"duration_seconds"`
	Hashtag             *string    `json:"hashtag"`
	Language            string     `json:"language"`
	ImageUrl            *string    `json:"image_url"`
	PublishStatus       string     `json:"publish_status"`
	MultimePostUrl      *string    `json:"multime_post_url"`
	LastError           *string    `json:"last_error"`
	CreatedBy           uuid.UUID  `json:"created_by"`
	CreatedAt           time.Time  `json:"created_at"`
	PublishedAt         *time.Time `json:"published_at"`
	Title               *string    `json:"title"`
	MimeType            *string    `json:"mime_type"`
	SizeBytes           *int64     `json:"size_bytes"`
	SampleRate          *int32     `json:"sample_rate"`
	InputText           *string    `json:"input_text"`
	CollectMode         *string    `json:"collect_mode"`
	PromptID            *uuid.UUID `json:"prompt_id"`
	AuthorID            *int64     `json:"author_id"`
	AuthorEmail         *string    `json:"author_email"`
	ImageUploaded       bool       `json:"image_uploaded"`
	AuthorGender        *string    `json:"author_gender"`
	PublishWhenReady    bool       `json:"publish_when_ready"`
	NoImage             bool       `json:"no_image"`
	LlmApiSetID         *uuid.UUID `json:"llm_api_set_id"`
	LlmModelUsed        *string    `json:"llm_model_used"`
	AuthorCountryID     *int64     `json:"author_country_id"`
	SpokenText          *string    `json:"spoken_text"`
	TtsConfig           []byte     `json:"tts_config"`
	Platform            *string    `json:"platform"`
	SourceUrl           *string    `json:"source_url"`
	SourceTitle         *string    `json:"source_title"`
	SourceCollectMode   *string    `json:"source_collect_mode"`
	SourcePromptID      *uuid.UUID `json:"source_prompt_id"`
	SourceExtractedText *string    `json:"source_extracted_text"`
	CreatedByEmail      string     `json:"created_by_email"`
}

// Trả kèm nền tảng nguồn + email người tạo để bảng Voice hiển thị và lọc được
// mà không phải gọi thêm API (prompt.md mục 3, 4, 8).
// Lọc theo trạng thái NGƯỜI DÙNG THẤY, không phải cột thô: voice còn thiếu điều
// kiện đăng (chưa chọn author, chưa có hashtag/tiêu đề, audio ngắn hơn mức
// multime nhận) hiện badge "Chưa đủ điều kiện", nên chọn trạng thái đó phải ra
// đúng những dòng ấy — và "Nháp"/"Chờ đăng" thì không được lẫn chúng.
//
// 'incomplete' KHÔNG phải giá trị có trong cột publish_status: nó là trạng thái
// suy ra lúc đọc. Thiếu hashtag là việc người dùng chưa điền xong, khác hẳn
// 'failed' (đã gửi lên multime và bị từ chối), nên không gộp chung.
// Sắp xếp động: mỗi nhánh CASE chỉ có giá trị khi đúng cột + đúng chiều đang
// chọn, các nhánh còn lại toàn NULL nên không ảnh hưởng thứ tự. Dòng cuối là
// mặc định (mới nhất trước) và cũng là nhánh sort=created_at + dir=desc.
func (q *Queries) ListVoices(ctx context.Context, arg ListVoicesParams) ([]ListVoicesRow, error) {
	rows, err := q.db.Query(ctx, listVoices,
		arg.PublishStatus,
		arg.MinDuration,
		arg.SourcePostID,
		arg.Platform,
		arg.Language,
		arg.CreatedBy,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.PublishedFrom,
		arg.PublishedTo,
		arg.Sort,
		arg.Dir,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVoicesRow{}
	for rows.Next() {
		var i ListVoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourcePostID,
			&i.AiEngineID,
			&i.VoiceFileUrl,
			&i.DurationSeconds,
			&i.Hashtag,
			&i.Language,
			&i.ImageUrl,
			&i.PublishStatus,
			&i.MultimePostUrl,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Title,
			&i.MimeType,
			&i.SizeBytes,
			&i.SampleRate,
			&i.InputText,
			&i.CollectMode,
			&i.PromptID,
			&i.AuthorID,
			&i.AuthorEmail,
			&i.ImageUploaded,
			&i.AuthorGender,
			&i.PublishWhenReady,
			&i.NoImage,
			&i.LlmApiSetID,
			&i.LlmModelUsed,
			&i.AuthorCountryID,
			&i.SpokenText,
			&i.TtsConfig,
			&i.Platform,
			&i.SourceUrl,
			&i.SourceTitle,
			&i.SourceCollectMode,
			&i.SourcePromptID,
			&i.SourceExtractedText,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoicesBySourcePost = `-- name: ListVoicesBySourcePost :many
SELECT id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config FROM voice WHERE source_post_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVoicesBySourcePost(ctx context.Context, sourcePostID *uuid.UUID) ([]Voice, error) {
	rows, err := q.db.Query(ctx, listVoicesBySourcePost, sourcePostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voice{}
	for rows.Next() {
		var i Voice
		if err := rows.Scan(
			&i.ID,
			&i.SourcePostID,
			&i.AiEngineID,
			&i.VoiceFileUrl,
			&i.DurationSeconds,
			&i.Hashtag,
			&i.Language,
			&i.ImageUrl,
			&i.PublishStatus,
			&i.MultimePostUrl,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Title,
			&i.MimeType,
			&i.SizeBytes,
			&i.SampleRate,
			&i.InputText,
			&i.CollectMode,
			&i.PromptID,
			&i.AuthorID,
			&i.AuthorEmail,
			&i.ImageUploaded,
			&i.AuthorGender,
			&i.PublishWhenReady,
			&i.NoImage,
			&i.LlmApiSetID,
			&i.LlmModelUsed,
			&i.AuthorCountryID,
			&i.SpokenText,
			&i.TtsConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVoicePublished = `-- name: MarkVoicePublished :one
UPDATE voice
SET publish_status   = 'published',
    multime_post_url = $1,
    voice_file_url   = NULL,
    image_url        = CASE WHEN image_uploaded THEN NULL ELSE image_url END,
    image_uploaded   = FALSE,
    last_error       = NULL,
    published_at     = now()
WHERE id = $2
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config
`

type MarkVoicePublishedParams struct {
	MultimePostUrl *string   `json:"multime_post_url"`
	ID             uuid.UUID `json:"id"`
}

// Business rule #2: publish thành công -> xoá file S3 và set voice_file_url = NULL,
// chỉ giữ multime_post_url làm nguồn tham chiếu duy nhất.
// Ảnh bìa tải từ máy cũng bị xoá theo cùng lý do: multime đã giữ bản của nó,
// bản trong bucket của mình không còn ai đọc nữa. Ảnh lấy từ URL bài gốc không
// nằm trong bucket nên giữ nguyên link.
func (q *Queries) MarkVoicePublished(ctx context.Context, arg MarkVoicePublishedParams) (Voice, error) {
	row := q.db.QueryRow(ctx, markVoicePublished, arg.MultimePostUrl, arg.ID)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}

const setVoiceContent = `-- name: SetVoiceContent :one
UPDATE voice
SET input_text     = $1,
    collect_mode   = $2,
    prompt_id      = $3,
    language       = COALESCE($4, language),
    llm_api_set_id = COALESCE($5, llm_api_set_id),
    -- Lời đọc người dùng tự chốt ở tab Nội dung. Chỉ có giá trị khi họ sửa
    -- thẳng vào ô lời đọc; NULL = để LLM (hoặc chính input_text) quyết định như
    -- thường, nên COALESCE giữ nguyên bản cũ cho tới khi FinishVoice ghi đè.
    spoken_text    = COALESCE($6, spoken_text),
    -- Cấu hình giọng đọc: cờ set_tts_config phân biệt "không đụng tới" với
    -- "trả về mặc định". COALESCE không làm được việc đó — gửi NULL để xoá
    -- cấu hình sẽ bị hiểu thành giữ nguyên, và người dùng bấm tạo lại sau khi
    -- thu mục cấu hình về mặc định vẫn nghe đúng giọng cũ.
    tts_config     = CASE WHEN $7::bool
                          THEN $8
                          ELSE tts_config END,
    publish_status = 'processing',
    last_error     = NULL
WHERE id = $9 AND publish_status <> 'published'
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config
`

type SetVoiceContentParams struct {
	InputText    *string    `json:"input_text"`
	CollectMode  *string    `json:"collect_mode"`
	PromptID     *uuid.UUID `json:"prompt_id"`
	Language     *string    `json:"language"`
	LlmApiSetID  *uuid.UUID `json:"llm_api_set_id"`
	SpokenText   *string    `json:"spoken_text"`
	SetTtsConfig bool       `json:"set_tts_config"`
	TtsConfig    []byte     `json:"tts_config"`
	ID           uuid.UUID  `json:"id"`
}

// Chốt lời đọc mới cho 1 Voice rồi đưa lại vào hàng đợi.
//
// Đặt luôn publish_status='processing' trong cùng câu lệnh: người dùng bấm
// "Tạo lại" là thấy dòng voice chuyển sang đang xử lý ngay, không có khoảng
// giữa mà bảng vẫn hiện voice cũ như chưa có gì xảy ra.
func (q *Queries) SetVoiceContent(ctx context.Context, arg SetVoiceContentParams) (Voice, error) {
	row := q.db.QueryRow(ctx, setVoiceContent,
		arg.InputText,
		arg.CollectMode,
		arg.PromptID,
		arg.Language,
		arg.LlmApiSetID,
		arg.SpokenText,
		arg.SetTtsConfig,
		arg.TtsConfig,
		arg.ID,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}

const setVoiceImage = `-- name: SetVoiceImage :one
UPDATE voice
SET image_url      = $1,
    image_uploaded = $2
WHERE id = $3
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config
`

type SetVoiceImageParams struct {
	ImageUrl      *string   `json:"image_url"`
	ImageUploaded bool      `json:"image_uploaded"`
	ID            uuid.UUID `json:"id"`
}

// Ảnh bìa tải từ máy: image_uploaded = TRUE đánh dấu file nằm trong storage của
// mình, để sau khi đăng lên multime thì xoá đi cho đỡ tốn dung lượng.
func (q *Queries) SetVoiceImage(ctx context.Context, arg SetVoiceImageParams) (Voice, error) {
	row := q.db.QueryRow(ctx, setVoiceImage, arg.ImageUrl, arg.ImageUploaded, arg.ID)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}

const setVoicePublishStatus = `-- name: SetVoicePublishStatus :one
UPDATE voice
SET publish_status = $1, last_error = $2
WHERE id = $3
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config
`

type SetVoicePublishStatusParams struct {
	PublishStatus string    `json:"publish_status"`
	LastError     *string   `json:"last_error"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) SetVoicePublishStatus(ctx context.Context, arg SetVoicePublishStatusParams) (Voice, error) {
	row := q.db.QueryRow(ctx, setVoicePublishStatus, arg.PublishStatus, arg.LastError, arg.ID)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}

const updateVoiceMetadata = `-- name: UpdateVoiceMetadata :one
UPDATE voice
SET hashtag           = COALESCE($1, hashtag),
    language          = COALESCE($2, language),
    image_url         = COALESCE($3, image_url),
    title             = COALESCE($4, title),
    author_gender     = COALESCE($5, author_gender),
    author_country_id = CASE WHEN $6::bool
                             THEN $7
                             ELSE author_country_id END,
    author_id         = CASE WHEN $8::bool THEN NULL
                             ELSE COALESCE($9, author_id) END,
    author_email      = CASE WHEN $8::bool THEN NULL
                             WHEN $9::bigint IS NULL THEN author_email
                             ELSE $10 END
WHERE id = $11
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id, author_id, author_email, image_uploaded, author_gender, publish_when_ready, no_image, llm_api_set_id, llm_model_used, author_country_id, spoken_text, tts_config
`

type UpdateVoiceMetadataParams struct {
	Hashtag         *string   `json:"hashtag"`
	Language        *string   `json:"language"`
	ImageUrl        *string   `json:"image_url"`
	Title           *string   `json:"title"`
	AuthorGender    *string   `json:"author_gender"`
	SetCountry      bool      `json:"set_country"`
	AuthorCountryID *int64    `json:"author_country_id"`
	ResetAuthor     bool      `json:"reset_author"`
	AuthorID        *int64    `json:"author_id"`
	AuthorEmail     *string   `json:"author_email"`
	ID              uuid.UUID `json:"id"`
}

// Chọn giới tính KHÔNG còn kéo theo việc bốc tài khoản — việc đó lùi xuống bước
// đăng. Vì thế author_gender giờ sửa được độc lập với author_id.
//
// `reset_author` là hệ quả bắt buộc của điều đó: đổi giới tính hoặc quốc gia mà
// vẫn giữ tài khoản đã bốc trước đó nghĩa là bài lên multime dưới tên một người
// không khớp thứ người dùng vừa chọn.
func (q *Queries) UpdateVoiceMetadata(ctx context.Context, arg UpdateVoiceMetadataParams) (Voice, error) {
	row := q.db.QueryRow(ctx, updateVoiceMetadata,
		arg.Hashtag,
		arg.Language,
		arg.ImageUrl,
		arg.Title,
		arg.AuthorGender,
		arg.SetCountry,
		arg.AuthorCountryID,
		arg.ResetAuthor,
		arg.AuthorID,
		arg.AuthorEmail,
		arg.ID,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
		&i.AuthorID,
		&i.AuthorEmail,
		&i.ImageUploaded,
		&i.AuthorGender,
		&i.PublishWhenReady,
		&i.NoImage,
		&i.LlmApiSetID,
		&i.LlmModelUsed,
		&i.AuthorCountryID,
		&i.SpokenText,
		&i.TtsConfig,
	)
	return i, err
}
