// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimVoiceForProcessing = `-- name: ClaimVoiceForProcessing :one
UPDATE voice
SET publish_status = 'processing', last_error = NULL
WHERE id = $1 AND publish_status IN ('processing', 'failed')
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id
`

// Nhận Voice về để đọc. Chỉ nhận khi voice đang `processing` hoặc đã `failed`:
// Asynq retry lần sau vẫn nhặt lại được, còn voice đã ra file (draft/ready) thì
// không đọc đè lên — muốn đọc lại phải đi qua SetVoiceContent, nơi người dùng
// chốt lại lời đọc. Voice đã publish thì không bao giờ đụng vào.
func (q *Queries) ClaimVoiceForProcessing(ctx context.Context, id uuid.UUID) (Voice, error) {
	row := q.db.QueryRow(ctx, claimVoiceForProcessing, id)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
	)
	return i, err
}

const countVoices = `-- name: CountVoices :one
SELECT COUNT(*)
FROM voice v
LEFT JOIN source_post sp ON sp.id = v.source_post_id
WHERE ($1::varchar IS NULL OR v.publish_status = $1)
  AND ($2::uuid    IS NULL OR v.source_post_id = $2)
  AND ($3::varchar       IS NULL OR sp.platform      = $3)
  AND ($4::varchar       IS NULL OR v.language       = $4)
  AND ($5::uuid        IS NULL OR v.created_by     = $5)
  AND ($6::timestamptz   IS NULL OR v.created_at   >= $6)
  AND ($7::timestamptz     IS NULL OR v.created_at   <= $7)
  AND ($8::timestamptz IS NULL OR v.published_at >= $8)
  AND ($9::timestamptz   IS NULL OR v.published_at <= $9)
`

type CountVoicesParams struct {
	PublishStatus *string    `json:"publish_status"`
	SourcePostID  *uuid.UUID `json:"source_post_id"`
	Platform      *string    `json:"platform"`
	Language      *string    `json:"language"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedFrom   *time.Time `json:"created_from"`
	CreatedTo     *time.Time `json:"created_to"`
	PublishedFrom *time.Time `json:"published_from"`
	PublishedTo   *time.Time `json:"published_to"`
}

func (q *Queries) CountVoices(ctx context.Context, arg CountVoicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVoices,
		arg.PublishStatus,
		arg.SourcePostID,
		arg.Platform,
		arg.Language,
		arg.CreatedBy,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.PublishedFrom,
		arg.PublishedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTextVoice = `-- name: CreateTextVoice :one
INSERT INTO voice (
  input_text, collect_mode, prompt_id, language, publish_status, title, created_by
) VALUES (
  $1, $2, $3,
  $4, 'processing', $5, $6
)
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id
`

type CreateTextVoiceParams struct {
	InputText   *string    `json:"input_text"`
	CollectMode *string    `json:"collect_mode"`
	PromptID    *uuid.UUID `json:"prompt_id"`
	Language    string     `json:"language"`
	Title       *string    `json:"title"`
	CreatedBy   uuid.UUID  `json:"created_by"`
}

// Voice gõ tay: không có Bài Post nào đứng sau, nội dung nằm thẳng trên Voice.
// Tạo ở trạng thái `processing` để người dùng thấy ngay dòng voice đang chạy,
// worker điền file + metadata vào đúng dòng đó (FinishVoice).
func (q *Queries) CreateTextVoice(ctx context.Context, arg CreateTextVoiceParams) (Voice, error) {
	row := q.db.QueryRow(ctx, createTextVoice,
		arg.InputText,
		arg.CollectMode,
		arg.PromptID,
		arg.Language,
		arg.Title,
		arg.CreatedBy,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
	)
	return i, err
}

const createVoice = `-- name: CreateVoice :one
INSERT INTO voice (
  source_post_id, ai_engine_id, voice_file_url, duration_seconds,
  hashtag, language, image_url, publish_status, title, mime_type, size_bytes,
  sample_rate, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id
`

type CreateVoiceParams struct {
	SourcePostID    *uuid.UUID `json:"source_post_id"`
	AiEngineID      *uuid.UUID `json:"ai_engine_id"`
	VoiceFileUrl    *string    `json:"voice_file_url"`
	DurationSeconds *int32     `json:"duration_seconds"`
	Hashtag         *string    `json:"hashtag"`
	Language        string     `json:"language"`
	ImageUrl        *string    `json:"image_url"`
	PublishStatus   string     `json:"publish_status"`
	Title           *string    `json:"title"`
	MimeType        *string    `json:"mime_type"`
	SizeBytes       *int64     `json:"size_bytes"`
	SampleRate      *int32     `json:"sample_rate"`
	CreatedBy       uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateVoice(ctx context.Context, arg CreateVoiceParams) (Voice, error) {
	row := q.db.QueryRow(ctx, createVoice,
		arg.SourcePostID,
		arg.AiEngineID,
		arg.VoiceFileUrl,
		arg.DurationSeconds,
		arg.Hashtag,
		arg.Language,
		arg.ImageUrl,
		arg.PublishStatus,
		arg.Title,
		arg.MimeType,
		arg.SizeBytes,
		arg.SampleRate,
		arg.CreatedBy,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
	)
	return i, err
}

const deleteVoice = `-- name: DeleteVoice :execrows
DELETE FROM voice WHERE id = $1
`

func (q *Queries) DeleteVoice(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVoice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishVoice = `-- name: FinishVoice :one
UPDATE voice
SET ai_engine_id     = $1,
    voice_file_url   = $2,
    duration_seconds = $3,
    title            = COALESCE($4, title),
    hashtag          = COALESCE($5, hashtag),
    image_url        = COALESCE($6, image_url),
    language         = $7,
    mime_type        = $8,
    size_bytes       = $9,
    sample_rate      = $10,
    publish_status   = 'draft',
    last_error       = NULL
WHERE id = $11
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id
`

type FinishVoiceParams struct {
	AiEngineID      *uuid.UUID `json:"ai_engine_id"`
	VoiceFileUrl    *string    `json:"voice_file_url"`
	DurationSeconds *int32     `json:"duration_seconds"`
	Title           *string    `json:"title"`
	Hashtag         *string    `json:"hashtag"`
	ImageUrl        *string    `json:"image_url"`
	Language        string     `json:"language"`
	MimeType        *string    `json:"mime_type"`
	SizeBytes       *int64     `json:"size_bytes"`
	SampleRate      *int32     `json:"sample_rate"`
	ID              uuid.UUID  `json:"id"`
}

// Worker điền kết quả vào record `processing` đã tạo sẵn lúc enqueue.
// Metadata dùng COALESCE: fetch không ra tiêu đề thì giữ nguyên phần đã điền
// sẵn từ Bài Post, không xoá trắng.
func (q *Queries) FinishVoice(ctx context.Context, arg FinishVoiceParams) (Voice, error) {
	row := q.db.QueryRow(ctx, finishVoice,
		arg.AiEngineID,
		arg.VoiceFileUrl,
		arg.DurationSeconds,
		arg.Title,
		arg.Hashtag,
		arg.ImageUrl,
		arg.Language,
		arg.MimeType,
		arg.SizeBytes,
		arg.SampleRate,
		arg.ID,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
	)
	return i, err
}

const getVoice = `-- name: GetVoice :one
SELECT id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id FROM voice WHERE id = $1
`

func (q *Queries) GetVoice(ctx context.Context, id uuid.UUID) (Voice, error) {
	row := q.db.QueryRow(ctx, getVoice, id)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
	)
	return i, err
}

const listVoices = `-- name: ListVoices :many
SELECT v.id, v.source_post_id, v.ai_engine_id, v.voice_file_url, v.duration_seconds, v.hashtag, v.language, v.image_url, v.publish_status, v.multime_post_url, v.last_error, v.created_by, v.created_at, v.published_at, v.title, v.mime_type, v.size_bytes, v.sample_rate, v.input_text, v.collect_mode, v.prompt_id,
       sp.platform     AS platform,
       sp.source_url   AS source_url,
       sp.title        AS source_title,
       sp.collect_mode AS source_collect_mode,
       sp.prompt_id    AS source_prompt_id,
       u.email         AS created_by_email
FROM voice v
LEFT JOIN source_post sp ON sp.id = v.source_post_id
JOIN app_user u     ON u.id = v.created_by
WHERE ($1::varchar IS NULL OR v.publish_status = $1)
  AND ($2::uuid    IS NULL OR v.source_post_id = $2)
  AND ($3::varchar       IS NULL OR sp.platform      = $3)
  AND ($4::varchar       IS NULL OR v.language       = $4)
  AND ($5::uuid        IS NULL OR v.created_by     = $5)
  AND ($6::timestamptz   IS NULL OR v.created_at   >= $6)
  AND ($7::timestamptz     IS NULL OR v.created_at   <= $7)
  AND ($8::timestamptz IS NULL OR v.published_at >= $8)
  AND ($9::timestamptz   IS NULL OR v.published_at <= $9)
ORDER BY
  CASE WHEN $10::text = 'published_at' AND $11::text = 'asc'
       THEN v.published_at END ASC NULLS LAST,
  CASE WHEN $10::text = 'published_at' AND $11::text = 'desc'
       THEN v.published_at END DESC NULLS LAST,
  CASE WHEN $11::text = 'asc' AND $10::text <> 'published_at'
       THEN v.created_at END ASC,
  v.created_at DESC
LIMIT $13 OFFSET $12
`

type ListVoicesParams struct {
	PublishStatus *string    `json:"publish_status"`
	SourcePostID  *uuid.UUID `json:"source_post_id"`
	Platform      *string    `json:"platform"`
	Language      *string    `json:"language"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedFrom   *time.Time `json:"created_from"`
	CreatedTo     *time.Time `json:"created_to"`
	PublishedFrom *time.Time `json:"published_from"`
	PublishedTo   *time.Time `json:"published_to"`
	Sort          string     `json:"sort"`
	Dir           string     `json:"dir"`
	Off           int32      `json:"off"`
	Lim           int32      `json:"lim"`
}

type ListVoicesRow struct {
	ID                uuid.UUID  `json:"id"`
	SourcePostID      *uuid.UUID `json:"source_post_id"`
	AiEngineID        *uuid.UUID `json:"ai_engine_id"`
	VoiceFileUrl      *string    `json:"voice_file_url"`
	DurationSeconds   *int32     `json:"duration_seconds"`
	Hashtag           *string    `json:"hashtag"`
	Language          string     `json:"language"`
	ImageUrl          *string    `json:"image_url"`
	PublishStatus     string     `json:"publish_status"`
	MultimePostUrl    *string    `json:"multime_post_url"`
	LastError         *string    `json:"last_error"`
	CreatedBy         uuid.UUID  `json:"created_by"`
	CreatedAt         time.Time  `json:"created_at"`
	PublishedAt       *time.Time `json:"published_at"`
	Title             *string    `json:"title"`
	MimeType          *string    `json:"mime_type"`
	SizeBytes         *int64     `json:"size_bytes"`
	SampleRate        *int32     `json:"sample_rate"`
	InputText         *string    `json:"input_text"`
	CollectMode       *string    `json:"collect_mode"`
	PromptID          *uuid.UUID `json:"prompt_id"`
	Platform          *string    `json:"platform"`
	SourceUrl         *string    `json:"source_url"`
	SourceTitle       *string    `json:"source_title"`
	SourceCollectMode *string    `json:"source_collect_mode"`
	SourcePromptID    *uuid.UUID `json:"source_prompt_id"`
	CreatedByEmail    string     `json:"created_by_email"`
}

// Trả kèm nền tảng nguồn + email người tạo để bảng Voice hiển thị và lọc được
// mà không phải gọi thêm API (prompt.md mục 3, 4, 8).
// Sắp xếp động: mỗi nhánh CASE chỉ có giá trị khi đúng cột + đúng chiều đang
// chọn, các nhánh còn lại toàn NULL nên không ảnh hưởng thứ tự. Dòng cuối là
// mặc định (mới nhất trước) và cũng là nhánh sort=created_at + dir=desc.
func (q *Queries) ListVoices(ctx context.Context, arg ListVoicesParams) ([]ListVoicesRow, error) {
	rows, err := q.db.Query(ctx, listVoices,
		arg.PublishStatus,
		arg.SourcePostID,
		arg.Platform,
		arg.Language,
		arg.CreatedBy,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.PublishedFrom,
		arg.PublishedTo,
		arg.Sort,
		arg.Dir,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVoicesRow{}
	for rows.Next() {
		var i ListVoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourcePostID,
			&i.AiEngineID,
			&i.VoiceFileUrl,
			&i.DurationSeconds,
			&i.Hashtag,
			&i.Language,
			&i.ImageUrl,
			&i.PublishStatus,
			&i.MultimePostUrl,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Title,
			&i.MimeType,
			&i.SizeBytes,
			&i.SampleRate,
			&i.InputText,
			&i.CollectMode,
			&i.PromptID,
			&i.Platform,
			&i.SourceUrl,
			&i.SourceTitle,
			&i.SourceCollectMode,
			&i.SourcePromptID,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoicesBySourcePost = `-- name: ListVoicesBySourcePost :many
SELECT id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id FROM voice WHERE source_post_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVoicesBySourcePost(ctx context.Context, sourcePostID *uuid.UUID) ([]Voice, error) {
	rows, err := q.db.Query(ctx, listVoicesBySourcePost, sourcePostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voice{}
	for rows.Next() {
		var i Voice
		if err := rows.Scan(
			&i.ID,
			&i.SourcePostID,
			&i.AiEngineID,
			&i.VoiceFileUrl,
			&i.DurationSeconds,
			&i.Hashtag,
			&i.Language,
			&i.ImageUrl,
			&i.PublishStatus,
			&i.MultimePostUrl,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Title,
			&i.MimeType,
			&i.SizeBytes,
			&i.SampleRate,
			&i.InputText,
			&i.CollectMode,
			&i.PromptID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVoicePublished = `-- name: MarkVoicePublished :one
UPDATE voice
SET publish_status   = 'published',
    multime_post_url = $1,
    voice_file_url   = NULL,
    last_error       = NULL,
    published_at     = now()
WHERE id = $2
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id
`

type MarkVoicePublishedParams struct {
	MultimePostUrl *string   `json:"multime_post_url"`
	ID             uuid.UUID `json:"id"`
}

// Business rule #2: publish thành công -> xoá file S3 và set voice_file_url = NULL,
// chỉ giữ multime_post_url làm nguồn tham chiếu duy nhất.
func (q *Queries) MarkVoicePublished(ctx context.Context, arg MarkVoicePublishedParams) (Voice, error) {
	row := q.db.QueryRow(ctx, markVoicePublished, arg.MultimePostUrl, arg.ID)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
	)
	return i, err
}

const setVoiceContent = `-- name: SetVoiceContent :one
UPDATE voice
SET input_text     = $1,
    collect_mode   = $2,
    prompt_id      = $3,
    language       = COALESCE($4, language),
    publish_status = 'processing',
    last_error     = NULL
WHERE id = $5 AND publish_status <> 'published'
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id
`

type SetVoiceContentParams struct {
	InputText   *string    `json:"input_text"`
	CollectMode *string    `json:"collect_mode"`
	PromptID    *uuid.UUID `json:"prompt_id"`
	Language    *string    `json:"language"`
	ID          uuid.UUID  `json:"id"`
}

// Chốt lời đọc mới cho 1 Voice rồi đưa lại vào hàng đợi.
//
// Đặt luôn publish_status='processing' trong cùng câu lệnh: người dùng bấm
// "Tạo lại" là thấy dòng voice chuyển sang đang xử lý ngay, không có khoảng
// giữa mà bảng vẫn hiện voice cũ như chưa có gì xảy ra.
func (q *Queries) SetVoiceContent(ctx context.Context, arg SetVoiceContentParams) (Voice, error) {
	row := q.db.QueryRow(ctx, setVoiceContent,
		arg.InputText,
		arg.CollectMode,
		arg.PromptID,
		arg.Language,
		arg.ID,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
	)
	return i, err
}

const setVoicePublishStatus = `-- name: SetVoicePublishStatus :one
UPDATE voice
SET publish_status = $1, last_error = $2
WHERE id = $3
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id
`

type SetVoicePublishStatusParams struct {
	PublishStatus string    `json:"publish_status"`
	LastError     *string   `json:"last_error"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) SetVoicePublishStatus(ctx context.Context, arg SetVoicePublishStatusParams) (Voice, error) {
	row := q.db.QueryRow(ctx, setVoicePublishStatus, arg.PublishStatus, arg.LastError, arg.ID)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
	)
	return i, err
}

const updateVoiceMetadata = `-- name: UpdateVoiceMetadata :one
UPDATE voice
SET hashtag     = COALESCE($1, hashtag),
    language    = COALESCE($2, language),
    image_url   = COALESCE($3, image_url),
    title       = COALESCE($4, title)
WHERE id = $5
RETURNING id, source_post_id, ai_engine_id, voice_file_url, duration_seconds, hashtag, language, image_url, publish_status, multime_post_url, last_error, created_by, created_at, published_at, title, mime_type, size_bytes, sample_rate, input_text, collect_mode, prompt_id
`

type UpdateVoiceMetadataParams struct {
	Hashtag  *string   `json:"hashtag"`
	Language *string   `json:"language"`
	ImageUrl *string   `json:"image_url"`
	Title    *string   `json:"title"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateVoiceMetadata(ctx context.Context, arg UpdateVoiceMetadataParams) (Voice, error) {
	row := q.db.QueryRow(ctx, updateVoiceMetadata,
		arg.Hashtag,
		arg.Language,
		arg.ImageUrl,
		arg.Title,
		arg.ID,
	)
	var i Voice
	err := row.Scan(
		&i.ID,
		&i.SourcePostID,
		&i.AiEngineID,
		&i.VoiceFileUrl,
		&i.DurationSeconds,
		&i.Hashtag,
		&i.Language,
		&i.ImageUrl,
		&i.PublishStatus,
		&i.MultimePostUrl,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Title,
		&i.MimeType,
		&i.SizeBytes,
		&i.SampleRate,
		&i.InputText,
		&i.CollectMode,
		&i.PromptID,
	)
	return i, err
}
